/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: mathlib-initiative
-/

import Mathlib
import RepresentationTheory.InductionAndCoinduction
import RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions

/-!
# Auxiliary monoid-algebra constructions for the symmetric group

This module identifies an induced permutation representation with a subrepresentation of the
permutation monoid algebra generated by an auxiliary partition-indexed element.
-/

set_option maxHeartbeats 800000

open Representation TensorProduct

open scoped Classical

namespace RepresentationTheory.SymmetricGroup.AuxiliaryMonoidAlgebra

open RepresentationTheory.InductionAndCoinduction
open RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions

variable (n : ℕ) (la : Nat.Partition n)

/-- A linear equivalence from the complex permutation monoid algebra to finitely supported
coefficient functions. -/
noncomputable def monoidAlgebraCoeffLinearEquiv :
    MonoidAlgebra ℂ (Equiv.Perm (Fin n)) ≃ₗ[ℂ] (Equiv.Perm (Fin n) →₀ ℂ) :=
  MonoidAlgebra.coeffLinearEquiv ℂ

/-- The coefficient linear equivalence evaluates to the monoid-algebra coefficient function. -/
@[simp] lemma monoidAlgebraCoeffLinearEquiv_apply
    (z : MonoidAlgebra ℂ (Equiv.Perm (Fin n))) :
    monoidAlgebraCoeffLinearEquiv n z = z.coeff := rfl

/-- An auxiliary complex representation of the displayed permutation subgroup on the complex
numbers. -/
noncomputable abbrev auxiliaryScalarRepresentation :
    Representation ℂ (↥(auxiliaryPartitionPermutationSubgroupB n la)) ℂ :=
  Representation.trivial ℂ (↥(auxiliaryPartitionPermutationSubgroupB n la)) ℂ

/-- An auxiliary complex representation of the displayed permutation subgroup on the tensor
product of the permutation monoid algebra with the scalars. -/
noncomputable abbrev auxiliaryTensorProductRepresentation :=
  Representation.tprod
    ((leftRegular ℂ (Equiv.Perm (Fin n))).comp
      (auxiliaryPartitionPermutationSubgroupB n la).subtype)
    (auxiliaryScalarRepresentation n la)

/-- An auxiliary type indexed by a natural number and a partition of that number. -/
noncomputable abbrev AuxiliaryCarrier :=
  Representation.IndV (auxiliaryPartitionPermutationSubgroupB n la).subtype
    (auxiliaryScalarRepresentation n la)

/-- An auxiliary partition-indexed complex submodule of the monoid algebra of permutations. -/
noncomputable abbrev auxiliaryMonoidAlgebraSubmodule :
    Submodule ℂ (MonoidAlgebra ℂ (Equiv.Perm (Fin n))) :=
  LinearMap.range
    (LinearMap.mulRight ℂ (auxiliaryPartitionGroupAlgebraElementB n la))

/-- Left multiplication by the basis element of a subgroup permutation fixes the auxiliary
monoid-algebra element. -/
theorem subgroup_mul_auxiliaryElement {q : Equiv.Perm (Fin n)}
    (hq : q ∈ auxiliaryPartitionPermutationSubgroupB n la) :
    MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) q *
        auxiliaryPartitionGroupAlgebraElementB n la =
      auxiliaryPartitionGroupAlgebraElementB n la := by
  simp only [auxiliaryPartitionGroupAlgebraElementB, Finset.mul_sum]
  refine Fintype.sum_bijective
    (Equiv.mulLeft (⟨q, hq⟩ : ↥(auxiliaryPartitionPermutationSubgroupB n la)))
    (Equiv.mulLeft _).bijective _ _ (fun g => ?_)
  change MonoidAlgebra.of ℂ _ q * MonoidAlgebra.of ℂ _ (g : Equiv.Perm (Fin n)) =
    MonoidAlgebra.of ℂ _
      ((⟨q, hq⟩ * g : ↥(auxiliaryPartitionPermutationSubgroupB n la)) :
        Equiv.Perm (Fin n))
  rw [← map_mul, Subgroup.coe_mul]

set_option backward.isDefEq.respectTransparency false in
/-- The left regular representation acts on the permutation monoid algebra by left multiplication
with the corresponding basis element. -/
theorem leftRegular_apply (g : Equiv.Perm (Fin n))
    (x : MonoidAlgebra ℂ (Equiv.Perm (Fin n))) :
    leftRegular ℂ (Equiv.Perm (Fin n)) g x =
      MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g * x := by
  induction x using MonoidAlgebra.induction_linear with
  | zero => simp
  | add u v hu hv => simp only [map_add, mul_add, hu, hv]
  | single y r =>
      rw [MonoidAlgebra.of_apply, MonoidAlgebra.single_mul_single, one_mul]
      simp [leftRegular, Representation.ofMulAction_single, smul_eq_mul]

/-- A linear endomorphism of the complex monoid algebra of permutations. -/
noncomputable def inversePermutationLinearMap :
    MonoidAlgebra ℂ (Equiv.Perm (Fin n)) →ₗ[ℂ]
      MonoidAlgebra ℂ (Equiv.Perm (Fin n)) :=
  (Finsupp.lsum ℂ fun h =>
    LinearMap.smulRight (LinearMap.id : ℂ →ₗ[ℂ] ℂ)
      (MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) h⁻¹)) ∘ₗ
    (MonoidAlgebra.coeffLinearEquiv ℂ).toLinearMap

set_option backward.isDefEq.respectTransparency false in
/-- The linear map sends a single permutation term to the term indexed by the inverse permutation
with the same coefficient. -/
@[simp] lemma inversePermutationLinearMap_single (h : Equiv.Perm (Fin n)) (r : ℂ) :
    inversePermutationLinearMap n (MonoidAlgebra.single h r) =
      MonoidAlgebra.single h⁻¹ r := by
  rw [inversePermutationLinearMap, LinearMap.comp_apply]
  change (Finsupp.lsum ℂ fun h =>
      LinearMap.smulRight (LinearMap.id : ℂ →ₗ[ℂ] ℂ)
        (MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) h⁻¹)) (Finsupp.single h r) = _
  rw [Finsupp.lsum_single, LinearMap.smulRight_apply, LinearMap.id_apply,
    MonoidAlgebra.of_apply, MonoidAlgebra.smul_single', mul_one]

/-- An auxiliary partition-indexed linear endomorphism of the complex monoid algebra of
permutations. -/
noncomputable def auxiliaryMonoidAlgebraEndomorphism :
    MonoidAlgebra ℂ (Equiv.Perm (Fin n)) →ₗ[ℂ]
      MonoidAlgebra ℂ (Equiv.Perm (Fin n)) :=
  LinearMap.mulRight ℂ (auxiliaryPartitionGroupAlgebraElementB n la) ∘ₗ
    inversePermutationLinearMap n

/-- The auxiliary endomorphism sends a single permutation term to the inverse-permutation term
multiplied by the auxiliary group-algebra element. -/
@[simp] lemma auxiliaryMonoidAlgebraEndomorphism_single
    (h : Equiv.Perm (Fin n)) (r : ℂ) :
    auxiliaryMonoidAlgebraEndomorphism n la (MonoidAlgebra.single h r) =
      MonoidAlgebra.single h⁻¹ r * auxiliaryPartitionGroupAlgebraElementB n la := by
  rw [auxiliaryMonoidAlgebraEndomorphism, LinearMap.comp_apply,
    inversePermutationLinearMap_single, LinearMap.mulRight_apply]

set_option backward.isDefEq.respectTransparency false in
/-- The auxiliary endomorphism is unchanged after left multiplication by the basis element of a
subgroup permutation. -/
theorem auxiliaryMonoidAlgebraEndomorphism_mul_subgroup
    (p : ↥(auxiliaryPartitionPermutationSubgroupB n la))
    (x : MonoidAlgebra ℂ (Equiv.Perm (Fin n))) :
    auxiliaryMonoidAlgebraEndomorphism n la
        (MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) (p : Equiv.Perm (Fin n)) * x) =
      auxiliaryMonoidAlgebraEndomorphism n la x := by
  induction x using MonoidAlgebra.induction_linear with
  | zero => simp
  | add u v hu hv => rw [mul_add, map_add, map_add, hu, hv]
  | single y r =>
      rw [MonoidAlgebra.of_apply, MonoidAlgebra.single_mul_single, one_mul,
        auxiliaryMonoidAlgebraEndomorphism_single,
        auxiliaryMonoidAlgebraEndomorphism_single, mul_inv_rev]
      rw [show MonoidAlgebra.single (y⁻¹ * (p : Equiv.Perm (Fin n))⁻¹) r =
            MonoidAlgebra.single y⁻¹ r *
              MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) ((p : Equiv.Perm (Fin n))⁻¹) by
            rw [MonoidAlgebra.of_apply, MonoidAlgebra.single_mul_single, mul_one]]
      rw [mul_assoc, subgroup_mul_auxiliaryElement n la (inv_mem p.2)]

/-- Every value of the auxiliary monoid-algebra endomorphism lies in the associated submodule. -/
theorem auxiliaryMonoidAlgebraEndomorphism_mem
    (y : MonoidAlgebra ℂ (Equiv.Perm (Fin n))) :
    auxiliaryMonoidAlgebraEndomorphism n la y ∈ auxiliaryMonoidAlgebraSubmodule n la := by
  induction y using MonoidAlgebra.induction_linear with
  | zero => simp
  | add u v hu hv => rw [map_add]; exact add_mem hu hv
  | single h r =>
      rw [auxiliaryMonoidAlgebraEndomorphism_single]
      exact ⟨MonoidAlgebra.single h⁻¹ r, by rw [LinearMap.mulRight_apply]⟩

/-- A partition-indexed linear map from the tensor product of the permutation monoid algebra with
the scalars to the monoid algebra. -/
noncomputable def tensorToMonoidAlgebra :
    TensorProduct ℂ (MonoidAlgebra ℂ (Equiv.Perm (Fin n))) ℂ →ₗ[ℂ]
      MonoidAlgebra ℂ (Equiv.Perm (Fin n)) :=
  TensorProduct.lift
    ((LinearMap.lsmul ℂ (MonoidAlgebra ℂ (Equiv.Perm (Fin n)))).flip ∘ₗ
      auxiliaryMonoidAlgebraEndomorphism n la)

/-- On a pure tensor, the tensor-to-monoid-algebra map is scalar multiplication of the associated
auxiliary endomorphism value. -/
@[simp] lemma tensorToMonoidAlgebra_tmul
    (x : MonoidAlgebra ℂ (Equiv.Perm (Fin n))) (c : ℂ) :
    tensorToMonoidAlgebra n la (x ⊗ₜ[ℂ] c) =
      c • auxiliaryMonoidAlgebraEndomorphism n la x := by
  simp [tensorToMonoidAlgebra, TensorProduct.lift.tmul]

/-- The tensor-to-monoid-algebra map takes every tensor into the associated auxiliary submodule. -/
theorem tensorToMonoidAlgebra_mem
    (t : TensorProduct ℂ (MonoidAlgebra ℂ (Equiv.Perm (Fin n))) ℂ) :
    tensorToMonoidAlgebra n la t ∈ auxiliaryMonoidAlgebraSubmodule n la := by
  induction t using TensorProduct.induction_on with
  | zero => simp
  | tmul x c =>
      rw [tensorToMonoidAlgebra_tmul]
      exact Submodule.smul_mem _ _ (auxiliaryMonoidAlgebraEndomorphism_mem n la x)
  | add u v hu hv => rw [map_add]; exact add_mem hu hv

/-- Composing the tensor-to-monoid-algebra map with the action of a subgroup element leaves the map
unchanged. -/
theorem tensorToMonoidAlgebra_comp_subgroupAction
    (p : ↥(auxiliaryPartitionPermutationSubgroupB n la)) :
    tensorToMonoidAlgebra n la ∘ₗ (auxiliaryTensorProductRepresentation n la) p =
      tensorToMonoidAlgebra n la := by
  apply TensorProduct.ext'
  intro x c
  simp only [LinearMap.comp_apply, Representation.tprod_apply, TensorProduct.map_tmul,
    MonoidHom.comp_apply, Subgroup.coe_subtype, Representation.trivial_apply,
    tensorToMonoidAlgebra_tmul]
  rw [leftRegular_apply, auxiliaryMonoidAlgebraEndomorphism_mul_subgroup]

/-- An auxiliary linear map from the partition-indexed carrier to the complex monoid algebra of
permutations. -/
noncomputable def auxiliaryCarrierToMonoidAlgebra :
    AuxiliaryCarrier n la →ₗ[ℂ] MonoidAlgebra ℂ (Equiv.Perm (Fin n)) :=
  Coinvariants.lift (auxiliaryTensorProductRepresentation n la)
    (tensorToMonoidAlgebra n la) (tensorToMonoidAlgebra_comp_subgroupAction n la)

/-- After passing a tensor through the coinvariants map, the auxiliary carrier map agrees with the
tensor-to-monoid-algebra map. -/
@[simp] lemma auxiliaryCarrierToMonoidAlgebra_coinvariants_mk
    (t : TensorProduct ℂ (MonoidAlgebra ℂ (Equiv.Perm (Fin n))) ℂ) :
    auxiliaryCarrierToMonoidAlgebra n la
        (Coinvariants.mk (auxiliaryTensorProductRepresentation n la) t) =
      tensorToMonoidAlgebra n la t :=
  Coinvariants.lift_mk _ _ _ t

/-- An induced-representation generator equals the coinvariants class of the corresponding
permutation basis term tensored with its scalar. -/
theorem indV_mk_eq_coinvariants_mk_tmul (h : Equiv.Perm (Fin n)) (c : ℂ) :
    Representation.IndV.mk (auxiliaryPartitionPermutationSubgroupB n la).subtype
        (auxiliaryScalarRepresentation n la) h c =
      Coinvariants.mk (auxiliaryTensorProductRepresentation n la)
        (MonoidAlgebra.single h 1 ⊗ₜ[ℂ] c) := rfl

/-- The auxiliary carrier map sends an induced-representation generator to the stated scalar
multiple of an inverse permutation basis element times the auxiliary vector. -/
theorem auxiliaryCarrierToMonoidAlgebra_indV_mk
    (h : Equiv.Perm (Fin n)) (c : ℂ) :
    auxiliaryCarrierToMonoidAlgebra n la
        (Representation.IndV.mk (auxiliaryPartitionPermutationSubgroupB n la).subtype
          (auxiliaryScalarRepresentation n la) h c) =
      c • (MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) h⁻¹ *
        auxiliaryPartitionGroupAlgebraElementB n la) := by
  rw [indV_mk_eq_coinvariants_mk_tmul,
    auxiliaryCarrierToMonoidAlgebra_coinvariants_mk, tensorToMonoidAlgebra_tmul,
    auxiliaryMonoidAlgebraEndomorphism_single, MonoidAlgebra.of_apply]

/-- Every value of the auxiliary carrier map belongs to the associated monoid-algebra submodule. -/
theorem auxiliaryCarrierToMonoidAlgebra_mem (y : AuxiliaryCarrier n la) :
    auxiliaryCarrierToMonoidAlgebra n la y ∈ auxiliaryMonoidAlgebraSubmodule n la := by
  induction y using Coinvariants.induction_on with
  | h t =>
      rw [auxiliaryCarrierToMonoidAlgebra_coinvariants_mk]
      exact tensorToMonoidAlgebra_mem n la t

/-- The auxiliary linear map from the partition-indexed carrier to the associated monoid-algebra
submodule. -/
noncomputable def auxiliaryCarrierToSubmodule :
    AuxiliaryCarrier n la →ₗ[ℂ] ↥(auxiliaryMonoidAlgebraSubmodule n la) :=
  (auxiliaryCarrierToMonoidAlgebra n la).codRestrict _
    (auxiliaryCarrierToMonoidAlgebra_mem n la)

/-- The underlying monoid-algebra value of the auxiliary submodule map agrees with the
corresponding ambient linear map. -/
@[simp] lemma coe_auxiliaryCarrierToSubmodule (y : AuxiliaryCarrier n la) :
    (auxiliaryCarrierToSubmodule n la y : MonoidAlgebra ℂ (Equiv.Perm (Fin n))) =
      auxiliaryCarrierToMonoidAlgebra n la y := rfl

/-- An auxiliary linear map from the complex permutation monoid algebra to the partition-indexed
carrier. -/
noncomputable def monoidAlgebraToAuxiliaryCarrier :
    MonoidAlgebra ℂ (Equiv.Perm (Fin n)) →ₗ[ℂ] AuxiliaryCarrier n la :=
  (Finsupp.linearCombination ℂ
    (fun x => Representation.IndV.mk
      (auxiliaryPartitionPermutationSubgroupB n la).subtype
      (auxiliaryScalarRepresentation n la) x⁻¹ 1)) ∘ₗ
    (monoidAlgebraCoeffLinearEquiv n).toLinearMap

/-- The auxiliary map sends a single permutation term to the corresponding scalar multiple of an
induced-representation generator at the inverse permutation. -/
@[simp] lemma monoidAlgebraToAuxiliaryCarrier_single
    (x : Equiv.Perm (Fin n)) (r : ℂ) :
    monoidAlgebraToAuxiliaryCarrier n la (MonoidAlgebra.single x r) =
      r • Representation.IndV.mk
        (auxiliaryPartitionPermutationSubgroupB n la).subtype
        (auxiliaryScalarRepresentation n la) x⁻¹ 1 := by
  rw [monoidAlgebraToAuxiliaryCarrier, LinearMap.comp_apply, LinearEquiv.coe_coe,
    monoidAlgebraCoeffLinearEquiv_apply, MonoidAlgebra.coeff_single]
  exact Finsupp.linearCombination_single ℂ r x

/-- An auxiliary linear map from the complex permutation monoid algebra to the partition-indexed
carrier. -/
noncomputable def normalizedMonoidAlgebraToAuxiliaryCarrier :
    MonoidAlgebra ℂ (Equiv.Perm (Fin n)) →ₗ[ℂ] AuxiliaryCarrier n la :=
  (Finsupp.linearCombination ℂ
    (fun x =>
      (Fintype.card (↥(auxiliaryPartitionPermutationSubgroupB n la)) : ℂ)⁻¹ •
        Representation.IndV.mk (auxiliaryPartitionPermutationSubgroupB n la).subtype
          (auxiliaryScalarRepresentation n la) x⁻¹ 1)) ∘ₗ
    (monoidAlgebraCoeffLinearEquiv n).toLinearMap

/-- The normalized map on a single permutation basis term is the stated scalar multiple of an
induced-representation generator at the inverse permutation. -/
@[simp] lemma normalizedMonoidAlgebraToAuxiliaryCarrier_single
    (x : Equiv.Perm (Fin n)) (r : ℂ) :
    normalizedMonoidAlgebraToAuxiliaryCarrier n la (MonoidAlgebra.single x r) =
      r • ((Fintype.card (↥(auxiliaryPartitionPermutationSubgroupB n la)) : ℂ)⁻¹ •
        Representation.IndV.mk (auxiliaryPartitionPermutationSubgroupB n la).subtype
          (auxiliaryScalarRepresentation n la) x⁻¹ 1) := by
  rw [normalizedMonoidAlgebraToAuxiliaryCarrier, LinearMap.comp_apply, LinearEquiv.coe_coe,
    monoidAlgebraCoeffLinearEquiv_apply, MonoidAlgebra.coeff_single]
  exact Finsupp.linearCombination_single ℂ r x

/-- Left multiplication of the permutation parameter by a subgroup element does not change the
induced-representation generator. -/
theorem indV_mk_mul_subgroup
    (p : ↥(auxiliaryPartitionPermutationSubgroupB n la))
    (h : Equiv.Perm (Fin n)) (c : ℂ) :
    Representation.IndV.mk (auxiliaryPartitionPermutationSubgroupB n la).subtype
        (auxiliaryScalarRepresentation n la) ((p : Equiv.Perm (Fin n)) * h) c =
      Representation.IndV.mk (auxiliaryPartitionPermutationSubgroupB n la).subtype
        (auxiliaryScalarRepresentation n la) h c := by
  have hkey : (auxiliaryTensorProductRepresentation n la) p
      (MonoidAlgebra.single h 1 ⊗ₜ[ℂ] c) =
        MonoidAlgebra.single ((p : Equiv.Perm (Fin n)) * h) 1 ⊗ₜ[ℂ] c := by
    simp only [Representation.tprod_apply, TensorProduct.map_tmul, MonoidHom.comp_apply,
      Subgroup.coe_subtype, Representation.trivial_apply]
    rw [leftRegular_apply, MonoidAlgebra.of_apply, MonoidAlgebra.single_mul_single, one_mul]
  rw [indV_mk_eq_coinvariants_mk_tmul, indV_mk_eq_coinvariants_mk_tmul,
    ← hkey, Coinvariants.mk_self_apply]

set_option backward.isDefEq.respectTransparency false in
/-- The composite from the monoid algebra through the auxiliary carrier is right multiplication by
the auxiliary group-algebra element. -/
theorem auxiliaryCarrierToMonoidAlgebra_comp_monoidAlgebraToCarrier
    (z : MonoidAlgebra ℂ (Equiv.Perm (Fin n))) :
    auxiliaryCarrierToMonoidAlgebra n la (monoidAlgebraToAuxiliaryCarrier n la z) =
      z * auxiliaryPartitionGroupAlgebraElementB n la := by
  induction z using MonoidAlgebra.induction_linear with
  | zero => simp
  | add u v hu hv => rw [map_add, map_add, add_mul, hu, hv]
  | single x r =>
      rw [monoidAlgebraToAuxiliaryCarrier_single, map_smul,
        auxiliaryCarrierToMonoidAlgebra_indV_mk, one_smul, inv_inv,
        MonoidAlgebra.of_apply, ← smul_mul_assoc, MonoidAlgebra.smul_single', mul_one]

set_option backward.isDefEq.respectTransparency false in
/-- The normalized map back to the auxiliary carrier is a left inverse of the
carrier-to-monoid-algebra map. -/
theorem normalizedMonoidAlgebraToAuxiliaryCarrier_comp :
    normalizedMonoidAlgebraToAuxiliaryCarrier n la ∘ₗ
        auxiliaryCarrierToMonoidAlgebra n la =
      LinearMap.id := by
  haveI : Nonempty (↥(auxiliaryPartitionPermutationSubgroupB n la)) := ⟨1⟩
  have hcard :
      (Fintype.card (↥(auxiliaryPartitionPermutationSubgroupB n la)) : ℂ) ≠ 0 := by
    exact_mod_cast Fintype.card_ne_zero
  apply Representation.IndV.hom_ext
  intro h
  apply LinearMap.ext_ring
  change normalizedMonoidAlgebraToAuxiliaryCarrier n la
      (auxiliaryCarrierToMonoidAlgebra n la
        (Representation.IndV.mk (auxiliaryPartitionPermutationSubgroupB n la).subtype
          (auxiliaryScalarRepresentation n la) h 1)) =
    Representation.IndV.mk (auxiliaryPartitionPermutationSubgroupB n la).subtype
      (auxiliaryScalarRepresentation n la) h 1
  rw [auxiliaryCarrierToMonoidAlgebra_indV_mk, one_smul,
    show MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) h⁻¹ *
        auxiliaryPartitionGroupAlgebraElementB n la =
      ∑ g : ↥(auxiliaryPartitionPermutationSubgroupB n la),
        MonoidAlgebra.single (h⁻¹ * (g : Equiv.Perm (Fin n))) 1 by
      simp only [auxiliaryPartitionGroupAlgebraElementB, Finset.mul_sum]
      refine Finset.sum_congr rfl (fun g _ => ?_)
      rw [← map_mul, MonoidAlgebra.of_apply]]
  rw [map_sum, Finset.sum_congr rfl
    (fun g (_ : g ∈ Finset.univ) => by
      rw [normalizedMonoidAlgebraToAuxiliaryCarrier_single, one_smul, mul_inv_rev,
        inv_inv, ← Subgroup.coe_inv, indV_mk_mul_subgroup])]
  rw [Finset.sum_const, Finset.card_univ, smul_comm, ← Nat.cast_smul_eq_nsmul ℂ,
    smul_smul, inv_mul_cancel₀ hcard, one_smul]

/-- The auxiliary linear map from the carrier to the permutation monoid algebra is injective. -/
theorem auxiliaryCarrierToMonoidAlgebra_injective :
    Function.Injective (auxiliaryCarrierToMonoidAlgebra n la) := by
  have hL : Function.LeftInverse (normalizedMonoidAlgebraToAuxiliaryCarrier n la)
      (auxiliaryCarrierToMonoidAlgebra n la) := fun x => by
    have := LinearMap.congr_fun (normalizedMonoidAlgebraToAuxiliaryCarrier_comp n la) x
    simpa using this
  exact hL.injective

/-- The auxiliary linear map into the monoid-algebra submodule is injective. -/
theorem auxiliaryCarrierToSubmodule_injective :
    Function.Injective (auxiliaryCarrierToSubmodule n la) := by
  intro a b hab
  apply auxiliaryCarrierToMonoidAlgebra_injective n la
  have :
      (auxiliaryCarrierToSubmodule n la a : MonoidAlgebra ℂ (Equiv.Perm (Fin n))) =
        (auxiliaryCarrierToSubmodule n la b :
          MonoidAlgebra ℂ (Equiv.Perm (Fin n))) := congrArg _ hab
  simpa only [coe_auxiliaryCarrierToSubmodule] using this

/-- The auxiliary linear map onto the monoid-algebra submodule is surjective. -/
theorem auxiliaryCarrierToSubmodule_surjective :
    Function.Surjective (auxiliaryCarrierToSubmodule n la) := by
  intro y
  obtain ⟨z, hz⟩ := LinearMap.mem_range.mp y.2
  refine ⟨monoidAlgebraToAuxiliaryCarrier n la z, ?_⟩
  apply Subtype.ext
  rw [coe_auxiliaryCarrierToSubmodule,
    auxiliaryCarrierToMonoidAlgebra_comp_monoidAlgebraToCarrier]
  simpa [LinearMap.mulRight_apply] using hz

/-- A complex representation of the permutation group on its monoid algebra. -/
noncomputable def leftMultiplicationRepresentation :
    Representation ℂ (Equiv.Perm (Fin n))
      (MonoidAlgebra ℂ (Equiv.Perm (Fin n))) where
  toFun g := LinearMap.mulLeft ℂ (MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g)
  map_one' := by ext x; simp
  map_mul' g h := by ext x; simp [map_mul, mul_assoc]

/-- The displayed representation acts by left multiplication with the monoid-algebra basis element
of the permutation. -/
@[simp] lemma leftMultiplicationRepresentation_apply (g : Equiv.Perm (Fin n))
    (x : MonoidAlgebra ℂ (Equiv.Perm (Fin n))) :
    leftMultiplicationRepresentation n g x =
      MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g * x := rfl

/-- The auxiliary monoid-algebra submodule is contained in its inverse image under each permutation
action. -/
theorem auxiliarySubmodule_le_comap_action (g : Equiv.Perm (Fin n)) :
    auxiliaryMonoidAlgebraSubmodule n la ≤
      (auxiliaryMonoidAlgebraSubmodule n la).comap
        (leftMultiplicationRepresentation n g) := by
  rintro _ ⟨z, rfl⟩
  refine Submodule.mem_comap.2
    ⟨MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g * z, ?_⟩
  rw [leftMultiplicationRepresentation_apply, LinearMap.mulRight_apply,
    LinearMap.mulRight_apply, mul_assoc]

/-- An auxiliary complex representation of the permutation group on the associated monoid-algebra
submodule. -/
noncomputable def auxiliarySubmoduleRepresentation :
    Representation ℂ (Equiv.Perm (Fin n)) ↥(auxiliaryMonoidAlgebraSubmodule n la) :=
  Representation.subrepresentation (leftMultiplicationRepresentation n)
    (auxiliaryMonoidAlgebraSubmodule n la) (auxiliarySubmodule_le_comap_action n la)

/-- The auxiliary carrier map intertwines the displayed permutation actions as linear maps. -/
theorem auxiliaryCarrierToMonoidAlgebra_intertwines (g : Equiv.Perm (Fin n)) :
    auxiliaryCarrierToMonoidAlgebra n la ∘ₗ
        (finiteIndexInduced (auxiliaryPartitionPermutationSubgroupB n la)
          (auxiliaryScalarRepresentation n la) g) =
      leftMultiplicationRepresentation n g ∘ₗ auxiliaryCarrierToMonoidAlgebra n la := by
  apply Representation.IndV.hom_ext
  intro h
  apply LinearMap.ext_ring
  change auxiliaryCarrierToMonoidAlgebra n la
      (Representation.ind (auxiliaryPartitionPermutationSubgroupB n la).subtype
        (auxiliaryScalarRepresentation n la) g
        (Representation.IndV.mk (auxiliaryPartitionPermutationSubgroupB n la).subtype
          (auxiliaryScalarRepresentation n la) h 1)) =
    MonoidAlgebra.of ℂ (Equiv.Perm (Fin n)) g *
      auxiliaryCarrierToMonoidAlgebra n la
        (Representation.IndV.mk (auxiliaryPartitionPermutationSubgroupB n la).subtype
          (auxiliaryScalarRepresentation n la) h 1)
  rw [Representation.ind_mk, auxiliaryCarrierToMonoidAlgebra_indV_mk,
    auxiliaryCarrierToMonoidAlgebra_indV_mk, one_smul, one_smul, mul_inv_rev,
    inv_inv, map_mul, mul_assoc]

/-- The auxiliary carrier map commutes pointwise with the displayed permutation actions. -/
theorem auxiliaryCarrierToMonoidAlgebra_action_apply
    (g : Equiv.Perm (Fin n)) (y : AuxiliaryCarrier n la) :
    auxiliaryCarrierToMonoidAlgebra n la
        (finiteIndexInduced (auxiliaryPartitionPermutationSubgroupB n la)
          (auxiliaryScalarRepresentation n la) g y) =
      leftMultiplicationRepresentation n g (auxiliaryCarrierToMonoidAlgebra n la y) :=
  LinearMap.congr_fun (auxiliaryCarrierToMonoidAlgebra_intertwines n la g) y

/-- An auxiliary linear equivalence between the partition-indexed carrier and the associated
monoid-algebra submodule. -/
noncomputable def auxiliaryCarrierSubmoduleEquiv :
    AuxiliaryCarrier n la ≃ₗ[ℂ] ↥(auxiliaryMonoidAlgebraSubmodule n la) :=
  LinearEquiv.ofBijective (auxiliaryCarrierToSubmodule n la)
    ⟨auxiliaryCarrierToSubmodule_injective n la,
      auxiliaryCarrierToSubmodule_surjective n la⟩

/-- The auxiliary carrier-submodule equivalence intertwines the displayed permutation
representations. -/
theorem auxiliaryCarrierSubmoduleEquiv_intertwines (g : Equiv.Perm (Fin n)) :
    (auxiliaryCarrierSubmoduleEquiv n la :
        AuxiliaryCarrier n la →ₗ[ℂ] ↥(auxiliaryMonoidAlgebraSubmodule n la)) ∘ₗ
        (finiteIndexInduced (auxiliaryPartitionPermutationSubgroupB n la)
          (auxiliaryScalarRepresentation n la) g) =
      auxiliarySubmoduleRepresentation n la g ∘ₗ auxiliaryCarrierSubmoduleEquiv n la := by
  apply LinearMap.ext
  intro x
  simp only [LinearMap.comp_apply, LinearEquiv.coe_coe, auxiliaryCarrierSubmoduleEquiv,
    LinearEquiv.ofBijective_apply]
  apply Subtype.ext
  change auxiliaryCarrierToMonoidAlgebra n la
      (finiteIndexInduced (auxiliaryPartitionPermutationSubgroupB n la)
        (auxiliaryScalarRepresentation n la) g x) =
    leftMultiplicationRepresentation n g (auxiliaryCarrierToMonoidAlgebra n la x)
  exact auxiliaryCarrierToMonoidAlgebra_action_apply n la g x

/-- An auxiliary equivalence between the two displayed complex representations. -/
@[source_ref"Chapter5/Introduction_5.14"(role:=supporting)]
noncomputable def auxiliaryRepresentationEquiv :
    (finiteIndexInduced (auxiliaryPartitionPermutationSubgroupB n la)
      (Representation.trivial ℂ (↥(auxiliaryPartitionPermutationSubgroupB n la)) ℂ)).Equiv
        (auxiliarySubmoduleRepresentation n la) :=
  Representation.Equiv.mk (auxiliaryCarrierSubmoduleEquiv n la)
    (auxiliaryCarrierSubmoduleEquiv_intertwines n la)

end RepresentationTheory.SymmetricGroup.AuxiliaryMonoidAlgebra
