name = "RepresentationTheoryFormalization"
version = "0.1.0"
defaultTargets = ["RepresentationTheory"]
enableArtifactCache = true

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.backward.isDefEq.respectTransparency = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[lean_lib]]
name = "RepresentationTheory"

[[lean_exe]]
name = "alignmentExport"
root = "AlignmentExport"
