/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENCE.
Authors: mathlib-initiative
-/

import RepresentationTheory.Auxiliary.ComponentEquivalences
import RepresentationTheory.Auxiliary.PolynomialModuleIndexedTypes
import RepresentationTheory.Alignment.Attribute

namespace RepresentationTheory.Auxiliary.PolynomialModuleQuotientEquivalences

open _root_.CategoryTheory _root_.CategoryTheory.Limits Polynomial

attribute [local instance] RepresentationTheory.PolynomialQuotientZModAuxiliary.quotientOppositePolynomialModule

variable {k : Type} [Field k]

/-- The auxiliary isomorphism from the displayed component to the quotient by the ideal generated by its indexed element. -/
noncomputable def auxiliaryQuotientIso {M : Type} [AddCommGroup M] [Module k[X] M]
    (D : RepresentationTheory.Algebra.Module.DirectSumData.Module.DirectSumData k[X] M)
    (j : D.summandIndex) :
    D.oppositeSummand j ≅
      ModuleCat.of (k[X])ᵐᵒᵖ (k[X] ⧸ Ideal.span {D.combined_coefficient j}) :=
  D.componentIso j ≪≫
    RepresentationTheory.Algebra.Module.DirectSumData.polynomialQuotientOppositeModuleIso
      (D.combined_coefficient j)

/-- The auxiliary linear equivalence from the displayed carrier to the quotient by the ideal generated by its indexed element. -/
noncomputable def auxiliaryQuotientLinearEquiv {N : Type} [AddCommGroup N] [Module k[X] N]
    (E : RepresentationTheory.Algebra.Module.DirectSumData.Module.DirectSumData k[X] N)
    (l : E.summandIndex) :
    (E.summand l : Type) ≃ₗ[k[X]] (k[X] ⧸ Ideal.span {E.combined_coefficient l}) :=
  (E.component_iso_quotient_span l).toLinearEquiv

variable {M N : Type} [AddCommGroup M] [Module k[X] M] [AddCommGroup N] [Module k[X] N]

/-- Shows that the displayed component in every degree offset by two has at most one element. -/
theorem auxiliaryHigherDegreeSubsingleton [Module.Finite k[X] M] (Y : Type) [AddCommGroup Y]
    [Module k[X] Y] (n : ℕ) :
    Subsingleton (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup
      k[X] Y (RepresentationTheory.Algebra.Module.DirectSumData.commRingModuleAsOpposite k[X] M)
      (n + 2)) := by
  obtain ⟨D⟩ := RepresentationTheory.Algebra.Module.DirectSumData.nonempty_directSumData k[X] M
  refine RepresentationTheory.Auxiliary.ComponentEquivalences.subsingleton_of_componentSubsingleton
    D Y (n + 2) fun j => ?_
  exact AddCommGrpCat.subsingleton_of_isZero
    ((RepresentationTheory.PolynomialQuotientZModAuxiliary.auxiliaryPolynomialQuotientModuleDegreeSuccSuccIsZero
      (D.combined_coefficient j) Y n).of_iso
      (RepresentationTheory.Auxiliary.ComponentEquivalences.mapIso Y
        (RepresentationTheory.Auxiliary.PolynomialModuleQuotientEquivalences.auxiliaryQuotientIso D j)
        (n + 2)))

/-- Constructs the displayed degree-zero additive equivalence indexed by the two supplied data objects. -/
theorem auxiliaryDegreeZeroEquiv
    (D : RepresentationTheory.Algebra.Module.DirectSumData.Module.DirectSumData k[X] M)
    (E : RepresentationTheory.Algebra.Module.DirectSumData.Module.DirectSumData k[X] N) :
    Nonempty (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup
      k[X] N (RepresentationTheory.Algebra.Module.DirectSumData.commRingModuleAsOpposite k[X] M) 0 ≃+
      ∀ (j : D.summandIndex) (l : E.summandIndex),
        (k[X] ⧸ Ideal.span {D.combined_coefficient j, E.combined_coefficient l})) := by
  refine ⟨(RepresentationTheory.Auxiliary.ComponentEquivalences.addEquivPi D E 0).trans
    (AddEquiv.piCongrRight fun j => AddEquiv.piCongrRight fun l => ?_)⟩
  exact ((RepresentationTheory.Auxiliary.ComponentEquivalences.mapLinearEquiv
      (RepresentationTheory.Auxiliary.PolynomialModuleQuotientEquivalences.auxiliaryQuotientLinearEquiv E l)
      (D.oppositeSummand j) 0) ≪≫
    (RepresentationTheory.Auxiliary.ComponentEquivalences.mapIso
      (k[X] ⧸ Ideal.span {E.combined_coefficient l})
      (RepresentationTheory.Auxiliary.PolynomialModuleQuotientEquivalences.auxiliaryQuotientIso D j) 0) ≪≫
    (RepresentationTheory.PolynomialQuotientZModAuxiliary.auxiliaryPolynomialQuotientDegreeZeroIso
      k (D.combined_coefficient j) (E.combined_coefficient l)).some).addCommGroupIsoToAddEquiv

/-- Constructs the displayed degree-one additive equivalence when every listed element on both sides is nonzero. -/
theorem auxiliaryDegreeOneEquiv
    (D : RepresentationTheory.Algebra.Module.DirectSumData.Module.DirectSumData k[X] M)
    (E : RepresentationTheory.Algebra.Module.DirectSumData.Module.DirectSumData k[X] N)
    (hD : ∀ i, D.quotientGenerator i ≠ 0) (hE : ∀ l, E.quotientGenerator l ≠ 0) :
    Nonempty (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup
      k[X] N (RepresentationTheory.Algebra.Module.DirectSumData.commRingModuleAsOpposite k[X] M) 1 ≃+
      ∀ (i : D.Index) (l : E.Index),
        (k[X] ⧸ Ideal.span {D.quotientGenerator i, E.quotientGenerator l})) := by
  haveI : ∀ i : Fin D.natParameter,
      Subsingleton (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup
        k[X] N (D.oppositeSummand (Sum.inl i)) 1) := fun _ =>
    AddCommGrpCat.subsingleton_of_isZero
      ((RepresentationTheory.PolynomialQuotientZModAuxiliary.auxiliaryPolynomialModuleDegreeSuccIsZero
        k N 0).of_iso
        (RepresentationTheory.Auxiliary.ComponentEquivalences.mapIso N
          (RepresentationTheory.Algebra.Module.DirectSumData.regularModuleAsOppositeIso k[X]) 1))
  haveI := RepresentationTheory.HomologicalAlgebra.ProjectiveDimension.FiniteModulesOverPID.subsingleton_pi
    fun i : Fin D.natParameter =>
      (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup
        k[X] N (D.oppositeSummand (Sum.inl i)) 1 : Type)
  refine ⟨(RepresentationTheory.Auxiliary.ComponentEquivalences.addEquiv D N 1).trans
    (((RepresentationTheory.HomologicalAlgebra.ProjectiveDimension.FiniteModulesOverPID.AddEquiv.pi_sum _).trans
      (RepresentationTheory.HomologicalAlgebra.ProjectiveDimension.FiniteModulesOverPID.AddEquiv.prod_right_of_subsingleton _ _)).trans
      (AddEquiv.piCongrRight fun i => ?_))⟩
  refine (RepresentationTheory.Auxiliary.ComponentEquivalences.mapIso N
    (RepresentationTheory.Auxiliary.PolynomialModuleQuotientEquivalences.auxiliaryQuotientIso
      D (Sum.inr i)) 1).addCommGroupIsoToAddEquiv.trans ?_
  haveI : ∀ l : Fin E.natParameter,
      Subsingleton (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup
        k[X] (E.summand (Sum.inl l))
        (ModuleCat.of (k[X])ᵐᵒᵖ
          (k[X] ⧸ Ideal.span {D.combined_coefficient (Sum.inr i)})) 1) := fun _ =>
    AddCommGrpCat.subsingleton_of_isZero
      (RepresentationTheory.PolynomialQuotientZModAuxiliary.auxiliaryPolynomialQuotientDegreeOneIsZero
        _ (hD i))
  haveI := RepresentationTheory.HomologicalAlgebra.ProjectiveDimension.FiniteModulesOverPID.subsingleton_pi
    fun l : Fin E.natParameter =>
      (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup
        k[X] (E.summand (Sum.inl l))
        (ModuleCat.of (k[X])ᵐᵒᵖ
          (k[X] ⧸ Ideal.span {D.combined_coefficient (Sum.inr i)})) 1 : Type)
  refine (RepresentationTheory.Auxiliary.ComponentEquivalences.addEquivComponents E _ 1).trans
    (((RepresentationTheory.HomologicalAlgebra.ProjectiveDimension.FiniteModulesOverPID.AddEquiv.pi_sum _).trans
      (RepresentationTheory.HomologicalAlgebra.ProjectiveDimension.FiniteModulesOverPID.AddEquiv.prod_right_of_subsingleton _ _)).trans
      (AddEquiv.piCongrRight fun l => ?_))
  exact ((RepresentationTheory.Auxiliary.ComponentEquivalences.mapLinearEquiv
      (RepresentationTheory.Auxiliary.PolynomialModuleQuotientEquivalences.auxiliaryQuotientLinearEquiv
        E (Sum.inr l)) _ 1) ≪≫
    (RepresentationTheory.PolynomialQuotientZModAuxiliary.auxiliaryPolynomialQuotientDegreeOneIso
      (D.quotientGenerator i) (E.quotientGenerator l) (hD i) (hE l)).some).addCommGroupIsoToAddEquiv

/-- Provides auxiliary data with prescribed degree-zero and degree-one equivalences and triviality in all higher displayed degrees. -/
@[source_ref "Chapter8/Problem8.2.7" (role := supporting)]
theorem auxiliaryDegreeZeroDegreeOneAndHigherSubsingleton
    [Module.Finite k[X] M] [Module.Finite k[X] N] :
    ∃ (D : RepresentationTheory.Algebra.Module.DirectSumData.Module.DirectSumData k[X] M)
      (E : RepresentationTheory.Algebra.Module.DirectSumData.Module.DirectSumData k[X] N),
      Nonempty (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup
        k[X] N (RepresentationTheory.Algebra.Module.DirectSumData.commRingModuleAsOpposite k[X] M) 0 ≃+
        ∀ (j : D.summandIndex) (l : E.summandIndex),
          (k[X] ⧸ Ideal.span {D.combined_coefficient j, E.combined_coefficient l})) ∧
      Nonempty (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup
        k[X] N (RepresentationTheory.Algebra.Module.DirectSumData.commRingModuleAsOpposite k[X] M) 1 ≃+
        ∀ (i : D.Index) (l : E.Index),
          (k[X] ⧸ Ideal.span {D.quotientGenerator i, E.quotientGenerator l})) ∧
      ∀ n : ℕ, Subsingleton
        (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup
          k[X] N (RepresentationTheory.Algebra.Module.DirectSumData.commRingModuleAsOpposite k[X] M)
          (n + 2)) := by
  obtain ⟨D, hD⟩ := RepresentationTheory.HomologicalAlgebra.ProjectiveDimension.FiniteModulesOverPID.Auxiliary.exists_data_with_nonzero_coefficients k[X] M
  obtain ⟨E, hE⟩ := RepresentationTheory.HomologicalAlgebra.ProjectiveDimension.FiniteModulesOverPID.Auxiliary.exists_data_with_nonzero_coefficients k[X] N
  exact ⟨D, E,
    RepresentationTheory.Auxiliary.PolynomialModuleQuotientEquivalences.auxiliaryDegreeZeroEquiv D E,
    RepresentationTheory.Auxiliary.PolynomialModuleQuotientEquivalences.auxiliaryDegreeOneEquiv D E hD hE,
    fun n => RepresentationTheory.Auxiliary.PolynomialModuleQuotientEquivalences.auxiliaryHigherDegreeSubsingleton N n⟩

section Examples

example : True := by
  have := RepresentationTheory.Auxiliary.PolynomialModuleQuotientEquivalences.auxiliaryDegreeZeroDegreeOneAndHigherSubsingleton
    (k := ℚ) (M := ℚ[X]) (N := ℚ[X])
  trivial

end Examples

end RepresentationTheory.Auxiliary.PolynomialModuleQuotientEquivalences
