/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENCE.
Authors: mathlib-initiative
-/

import Mathlib.LinearAlgebra.Finsupp.VectorSpace
import Mathlib.RingTheory.Adjoin.Basic
import RepresentationTheory.Alignment.Attribute

/-!
# Twisted lattice shifts

Integer-pair-indexed endomorphisms with a unit-valued twisting factor and the
subalgebra that they generate.
-/

namespace RepresentationTheory.Algebra.Module.TwistedLatticeShifts

open Finsupp

variable (k : Type*) [CommRing k] (q : kˣ)

/-- An auxiliary type associated with a commutative ring. -/
abbrev Auxiliary : Type _ := (ℤ × ℤ) →₀ k

/-- The endomorphism indexed by an integer pair, with twisting parameter a unit of the coefficient ring. -/
noncomputable def twistedLatticeShift (p : ℤ × ℤ) : Module.End k (Auxiliary k) :=
  Finsupp.lsum k fun mn : ℤ × ℤ =>
    (↑(q ^ (p.2 * mn.1)) : k) • Finsupp.lsingle (mn.1 + p.1, mn.2 + p.2)

/-- Applying a twisted shift to a singleton translates its integer-pair index and scales its coefficient by the prescribed power of the twisting unit. -/
theorem twistedLatticeShift_apply_single (p : ℤ × ℤ) (m n : ℤ) (c : k) :
    twistedLatticeShift k q p (Finsupp.single (m, n) c) =
      Finsupp.single (m + p.1, n + p.2) ((↑(q ^ (p.2 * m)) : k) * c) := by
  rw [twistedLatticeShift, Finsupp.lsum_single]
  simp [Finsupp.smul_single, smul_eq_mul]

/-- The twisted shift indexed by the zero integer pair is the identity endomorphism. -/
@[simp] theorem twistedLatticeShift_zero_zero : twistedLatticeShift k q (0, 0) = 1 := by
  apply Finsupp.lhom_ext
  intro a c
  obtain ⟨m, n⟩ := a
  rw [twistedLatticeShift_apply_single]
  simp

/-- The product of two twisted shifts is a scalar multiple of the shift indexed by the sum of their integer pairs. -/
@[source_ref "Chapter2/Proposition2.7.1" (role := primary)]
theorem twistedLatticeShift_mul (p p' : ℤ × ℤ) :
    twistedLatticeShift k q p * twistedLatticeShift k q p' =
      (↑(q ^ (p.2 * p'.1)) : k) • twistedLatticeShift k q (p.1 + p'.1, p.2 + p'.2) := by
  apply Finsupp.lhom_ext
  intro a c
  obtain ⟨m, n⟩ := a
  rw [Module.End.mul_apply, twistedLatticeShift_apply_single, twistedLatticeShift_apply_single,
    LinearMap.smul_apply, twistedLatticeShift_apply_single, Finsupp.smul_single]
  congr 1
  · ext <;> simp <;> ring
  · dsimp only
    have hL : (q ^ (p.2 * (m + p'.1)) * q ^ (p'.2 * m) : kˣ) =
        q ^ (p.2 * m + p.2 * p'.1 + p'.2 * m) := by rw [← zpow_add]; congr 1; ring
    have hR : (q ^ (p.2 * p'.1) * q ^ ((p.2 + p'.2) * m) : kˣ) =
        q ^ (p.2 * m + p.2 * p'.1 + p'.2 * m) := by rw [← zpow_add]; congr 1; ring
    simp only [smul_eq_mul, ← mul_assoc, ← Units.val_mul]
    rw [hL, hR]

/-- The subalgebra of endomorphisms generated by the integer-pair-indexed twisted shifts. -/
@[source_ref "Chapter2/Discussion_2.7_intro" (role := supporting)]
noncomputable def twistedLatticeShiftSubalgebra : Subalgebra k (Module.End k (Auxiliary k)) :=
  Algebra.adjoin k
    {twistedLatticeShift k q (1, 0), twistedLatticeShift k q (-1, 0),
      twistedLatticeShift k q (0, 1), twistedLatticeShift k q (0, -1)}

/-- The shifts in the two coordinate directions commute up to multiplication by the twisting unit. -/
@[source_ref "Chapter2/Discussion_2.7_intro" (role := supporting)]
theorem twistedLatticeShift_generators_commute_up_to_unit :
    twistedLatticeShift k q (0, 1) * twistedLatticeShift k q (1, 0) =
      (↑q : k) • (twistedLatticeShift k q (1, 0) * twistedLatticeShift k q (0, 1)) := by
  rw [twistedLatticeShift_mul, twistedLatticeShift_mul]
  simp

/-- An auxiliary result. -/
@[source_ref "Chapter2/Discussion_2.7_intro" (role := supporting)]
theorem auxiliaryThree :
    twistedLatticeShift k q (1, 0) * twistedLatticeShift k q (-1, 0) = 1 := by
  rw [twistedLatticeShift_mul];
  simp

/-- An auxiliary result. -/
@[source_ref "Chapter2/Discussion_2.7_intro" (role := supporting)]
theorem auxiliaryOne :
    twistedLatticeShift k q (-1, 0) * twistedLatticeShift k q (1, 0) = 1 := by
  rw [twistedLatticeShift_mul];
  simp

/-- An auxiliary result. -/
@[source_ref "Chapter2/Discussion_2.7_intro" (role := supporting)]
theorem auxiliaryFour :
    twistedLatticeShift k q (0, 1) * twistedLatticeShift k q (0, -1) = 1 := by
  rw [twistedLatticeShift_mul];
  simp

/-- An auxiliary result. -/
@[source_ref "Chapter2/Discussion_2.7_intro" (role := supporting)]
theorem auxiliaryTwo :
    twistedLatticeShift k q (0, -1) * twistedLatticeShift k q (0, 1) = 1 := by
  rw [twistedLatticeShift_mul];
  simp

/-- Every indexed twisted shift belongs to the subalgebra generated by the family. -/
theorem twistedLatticeShift_mem_generatedSubalgebra (p : ℤ × ℤ) :
    twistedLatticeShift k q p ∈ twistedLatticeShiftSubalgebra k q := by
  obtain ⟨i, j⟩ := p
  have hx : twistedLatticeShift k q (1, 0) ∈ twistedLatticeShiftSubalgebra k q :=
    Algebra.subset_adjoin (by simp)
  have hx' : twistedLatticeShift k q (-1, 0) ∈ twistedLatticeShiftSubalgebra k q :=
    Algebra.subset_adjoin (by simp)
  have hy : twistedLatticeShift k q (0, 1) ∈ twistedLatticeShiftSubalgebra k q :=
    Algebra.subset_adjoin (by simp)
  have hy' : twistedLatticeShift k q (0, -1) ∈ twistedLatticeShiftSubalgebra k q :=
    Algebra.subset_adjoin (by simp)
  suffices h0 : ∀ a : ℤ, twistedLatticeShift k q (a, 0) ∈ twistedLatticeShiftSubalgebra k q by
    induction j using Int.induction_on with
    | zero => simpa using h0 i
    | succ n ih =>
        have hrec : twistedLatticeShift k q (i, (n : ℤ) + 1) =
            twistedLatticeShift k q (i, (n : ℤ)) * twistedLatticeShift k q (0, 1) := by
          rw [twistedLatticeShift_mul];
          simp
        rw [hrec];
        exact mul_mem ih hy
    | pred n ih =>
        have hrec : twistedLatticeShift k q (i, -(n : ℤ) - 1) =
            twistedLatticeShift k q (i, -(n : ℤ)) * twistedLatticeShift k q (0, -1) := by
          rw [twistedLatticeShift_mul];
          simp;
          ring_nf
        rw [hrec];
        exact mul_mem ih hy'
  intro a
  induction a using Int.induction_on with
  | zero =>
      simp only [twistedLatticeShift_zero_zero];
      exact one_mem (twistedLatticeShiftSubalgebra k q)
  | succ n ih =>
      have hrec : twistedLatticeShift k q ((n : ℤ) + 1, 0) =
          twistedLatticeShift k q (1, 0) * twistedLatticeShift k q ((n : ℤ), 0) := by
        rw [twistedLatticeShift_mul];
        simp [add_comm]
      rw [hrec];
      exact mul_mem hx ih
  | pred n ih =>
      have hrec : twistedLatticeShift k q (-(n : ℤ) - 1, 0) =
          twistedLatticeShift k q (-1, 0) * twistedLatticeShift k q (-(n : ℤ), 0) := by
        rw [twistedLatticeShift_mul];
        simp;
        ring_nf
      rw [hrec];
      exact mul_mem hx' ih

private theorem span_mul_mem {a b : Module.End k (Auxiliary k)}
    (ha : a ∈ Submodule.span k (Set.range (twistedLatticeShift k q)))
    (hb : b ∈ Submodule.span k (Set.range (twistedLatticeShift k q))) :
    a * b ∈ Submodule.span k (Set.range (twistedLatticeShift k q)) := by
  apply Submodule.span_induction
    (p := fun b (_ : b ∈ Submodule.span k (Set.range (twistedLatticeShift k q))) =>
      a * b ∈ Submodule.span k (Set.range (twistedLatticeShift k q)))
  · rintro x ⟨p', rfl⟩
    apply Submodule.span_induction
      (p := fun a (_ : a ∈ Submodule.span k (Set.range (twistedLatticeShift k q))) =>
        a * twistedLatticeShift k q p' ∈ Submodule.span k (Set.range (twistedLatticeShift k q)))
    · rintro y ⟨p, rfl⟩
      rw [twistedLatticeShift_mul]
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨_, rfl⟩)
    · rw [zero_mul];
      exact Submodule.zero_mem _
    · intro u v _ _ hu hv;
      rw [add_mul];
      exact Submodule.add_mem _ hu hv
    · intro c u _ hu;
      rw [smul_mul_assoc];
      exact Submodule.smul_mem _ c hu
    · exact ha
  · rw [mul_zero];
    exact Submodule.zero_mem _
  · intro u v _ _ hu hv;
    rw [mul_add];
    exact Submodule.add_mem _ hu hv
  · intro c u _ hu;
    rw [mul_smul_comm];
    exact Submodule.smul_mem _ c hu
  · exact hb

/-- The underlying submodule of the generated subalgebra is the span of the twisted shift family. -/
theorem twistedLatticeShiftSubalgebra_toSubmodule :
    (twistedLatticeShiftSubalgebra k q).toSubmodule =
      Submodule.span k (Set.range (twistedLatticeShift k q)) := by
  apply le_antisymm
  · intro a ha
    rw [Subalgebra.mem_toSubmodule] at ha
    replace ha : a ∈ Algebra.adjoin k
        ({twistedLatticeShift k q (1, 0), twistedLatticeShift k q (-1, 0),
          twistedLatticeShift k q (0, 1), twistedLatticeShift k q (0, -1)} :
          Set (Module.End k (Auxiliary k))) := ha
    induction ha using Algebra.adjoin_induction with
    | mem x hx =>
        simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
        rcases hx with rfl | rfl | rfl | rfl <;>
          exact Submodule.subset_span ⟨_, rfl⟩
    | algebraMap r =>
        rw [Algebra.algebraMap_eq_smul_one, ← twistedLatticeShift_zero_zero k q]
        exact Submodule.smul_mem _ r (Submodule.subset_span ⟨_, rfl⟩)
    | add x y _ _ ihx ihy => exact Submodule.add_mem _ ihx ihy
    | mul x y _ _ ihx ihy => exact span_mul_mem k q ihx ihy
  · rw [Submodule.span_le]
    rintro a ⟨p, rfl⟩
    rw [SetLike.mem_coe, Subalgebra.mem_toSubmodule]
    exact twistedLatticeShift_mem_generatedSubalgebra k q p

/-- The family of twisted shift endomorphisms indexed by pairs of integers is linearly independent. -/
theorem twistedLatticeShift_linearIndependent : LinearIndependent k (twistedLatticeShift k q) := by
  have hsingle : (fun p : ℤ × ℤ => twistedLatticeShift k q p (Finsupp.single (0, 0) 1)) =
      fun p : ℤ × ℤ => Finsupp.single p 1 := by
    funext p
    obtain ⟨i, j⟩ := p
    rw [twistedLatticeShift_apply_single];
    simp
  have hev : LinearIndependent k
      (fun p : ℤ × ℤ => twistedLatticeShift k q p (Finsupp.single (0, 0) 1)) := by
    rw [hsingle]
    have := (Finsupp.basisSingleOne (ι := ℤ × ℤ) (R := k)).linearIndependent
    rwa [Finsupp.coe_basisSingleOne] at this
  exact hev.of_comp (LinearMap.applyₗ (Finsupp.single (0, 0) 1))

/-- The indexed twisted shifts are linearly independent, and their span is the underlying module of the generated subalgebra. -/
@[source_ref "Chapter2/Proposition2.7.1" (role := supporting)]
theorem twistedLatticeShifts_linearIndependent_and_span :
    LinearIndependent k (twistedLatticeShift k q) ∧
    (twistedLatticeShiftSubalgebra k q).toSubmodule =
      Submodule.span k (Set.range (twistedLatticeShift k q)) :=
  ⟨twistedLatticeShift_linearIndependent k q,
    twistedLatticeShiftSubalgebra_toSubmodule k q⟩

end RepresentationTheory.Algebra.Module.TwistedLatticeShifts
