/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENCE.
Authors: mathlib-initiative
-/

import Mathlib
import RepresentationTheory.Algebra.MvPolynomial.WeightedComponents
import RepresentationTheory.TensorPolynomial.Contraction
import RepresentationTheory.LinearAlgebra.TensorPower.PermutationTrace
import RepresentationTheory.Alignment.Attribute

/-!
# Generation of a trace algebra
-/


noncomputable section

namespace RepresentationTheory.TraceAlgebra.Generation

open scoped Classical TensorProduct
open MvPolynomial Module

variable (k N : ℕ)

/-- The trace of the matrix built from a permutation, a finite word, and a selected position belongs to the range of the distinguished family. -/
theorem trace_permutation_construction_mem_range (n : ℕ) (σ : Equiv.Perm (Fin n))
    (letter : Fin n → Fin k) (r : Fin n) :
    Matrix.trace (RepresentationTheory.LinearAlgebra.TensorPower.PermutationTrace.Matrix.permutationCycleProduct σ (fun i => RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.finIndexedMatrix k N (letter i)) r)
      ∈ Set.range (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.listIndexedElement k N) := by
  refine ⟨(List.range (RepresentationTheory.LinearAlgebra.TensorPower.PermutationTrace.Equiv.Perm.cycleLengthAt σ r)).map (fun t => letter ((σ⁻¹ ^ t) r)), ?_⟩
  rw [RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.listIndexedElement, RepresentationTheory.LinearAlgebra.TensorPower.PermutationTrace.Matrix.permutationCycleProduct, List.map_map]
  rfl

/-- Applying the slot-indexed map to the linear map obtained from a permutation equivalence yields an element of the algebra generated by the specified range. -/
theorem mapped_permutation_equiv_mem_adjoin_range (n : ℕ) (slot : Fin n → Fin k)
    (σ : Equiv.Perm (Fin n)) :
    RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.endomorphismToPolynomial k N n slot (RepresentationTheory.Auxiliary.MutualCentralizers.auxiliarySpacePermutationEquiv ℂ (RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.AuxiliaryIndexType N) n σ).toLinearMap
      ∈ Algebra.adjoin ℂ (Set.range (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.listIndexedElement k N)) := by
  classical


  have hval : RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.endomorphismToPolynomial k N n slot (RepresentationTheory.Auxiliary.MutualCentralizers.auxiliarySpacePermutationEquiv ℂ (RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.AuxiliaryIndexType N) n σ).toLinearMap
      = ∑ g : Fin n → Fin N, ∏ i : Fin n,
          RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.finIndexedMatrix k N (slot (σ i)) (g (σ i)) (g i) := by
    rw [RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.endomorphismToPolynomial_apply, Finset.sum_comm]
    refine Finset.sum_congr rfl fun g _ => ?_

    have hcollapse : (∑ f : Fin n → Fin N,
          algebraMap ℂ (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType k N)
            (LinearMap.toMatrix (RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.piTensorProductBasis N n) (RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.piTensorProductBasis N n)
              (RepresentationTheory.Auxiliary.MutualCentralizers.auxiliarySpacePermutationEquiv ℂ (RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.AuxiliaryIndexType N) n σ).toLinearMap f g)
            * RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.contractionMatrix k N n slot g f)
        = RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.contractionMatrix k N n slot g (g ∘ σ.symm) := by
      have hterm : ∀ f : Fin n → Fin N,
          algebraMap ℂ (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType k N)
              (LinearMap.toMatrix (RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.piTensorProductBasis N n) (RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.piTensorProductBasis N n)
                (RepresentationTheory.Auxiliary.MutualCentralizers.auxiliarySpacePermutationEquiv ℂ (RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.AuxiliaryIndexType N) n σ).toLinearMap f g)
              * RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.contractionMatrix k N n slot g f
            = if f = g ∘ σ.symm then RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.contractionMatrix k N n slot g f else 0 := by
        intro f
        rw [RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.toMatrix_tensorPermutation_apply, Equiv.Perm.inv_def,
          apply_ite (algebraMap ℂ (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType k N)),
          map_one, map_zero, ite_mul, one_mul, zero_mul]
      simp_rw [hterm]
      rw [Finset.sum_ite_eq' Finset.univ (g ∘ σ.symm)
        (fun f => RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.contractionMatrix k N n slot g f)]
      simp
    rw [hcollapse]

    simp only [RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.contractionMatrix]
    rw [← Equiv.prod_comp σ (fun j => MvPolynomial.X (R := ℂ)
      ((slot j, g j, (g ∘ σ.symm) j) : Fin k × Fin N × Fin N))]
    refine Finset.prod_congr rfl fun i _ => ?_
    simp only [Function.comp_apply, Equiv.symm_apply_apply, RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.finIndexedMatrix]
  rw [hval, RepresentationTheory.LinearAlgebra.TensorPower.PermutationTrace.Matrix.sum_permutationWeights_eq_prod_cycleTraces σ (fun i => RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.finIndexedMatrix k N (slot (σ i)))]
  refine Subalgebra.prod_mem _ fun r _ => ?_
  exact Algebra.subset_adjoin
    (trace_permutation_construction_mem_range k N n σ (fun i => slot (σ i)) r)

/-- Every finitely supported family of natural numbers on a finite type is realized as the fiber cardinalities of a map between finite types. -/
theorem exists_fin_map_fiber_card_eq (d : Fin k →₀ ℕ) :
    ∃ (n : ℕ) (slot : Fin n → Fin k),
      ∀ i : Fin k, (Finset.univ.filter fun j => slot j = i).card = d i := by
  classical

  refine ⟨∑ i : Fin k, d i, fun j => (finSigmaFinEquiv.symm j).1, fun i => ?_⟩

  have E : {j : Fin (∑ i : Fin k, d i) // (finSigmaFinEquiv.symm j).1 = i} ≃ Fin (d i) :=
    (finSigmaFinEquiv.symm.subtypeEquiv (q := fun t => t.1 = i) (fun _ => Iff.rfl)).trans
      (Equiv.sigmaSubtype (β := fun i' : Fin k => Fin (d i')) i)
  rw [← Fintype.card_subtype (fun j => (finSigmaFinEquiv.symm j).1 = i),
    Fintype.card_congr E, Fintype.card_fin]

/-- A weighted homogeneous polynomial in the designated subalgebra belongs to the algebra generated by the range of the distinguished family. -/
theorem mem_adjoin_range_of_isWeightedHomogeneous_of_mem_subalgebra (d : Fin k →₀ ℕ)
    {p : RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType k N}
    (hhom : IsWeightedHomogeneous (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.variableWeight k N) p d)
    (hinv : p ∈ RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.complexSubalgebra k N) :
    p ∈ Algebra.adjoin ℂ (Set.range (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.listIndexedElement k N)) := by

  obtain ⟨n, slot, hslot⟩ := exists_fin_map_fiber_card_eq k d

  obtain ⟨M, hM, hMp⟩ :=
    RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.exists_auxiliaryEndomorphism_preimage k N n d slot hslot hhom hinv

  rw [← RepresentationTheory.Auxiliary.MutualCentralizers.range_permutationGroupAlgebraAction] at hM
  obtain ⟨x, rfl⟩ := hM

  rw [← hMp]

  have hxsum : RepresentationTheory.Auxiliary.MutualCentralizers.permutationGroupAlgebraAction ℂ (RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.AuxiliaryIndexType N) n x
      = ∑ σ ∈ x.coeff.support,
        x.coeff σ • (RepresentationTheory.Auxiliary.MutualCentralizers.auxiliarySpacePermutationEquiv ℂ (RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.AuxiliaryIndexType N) n σ).toLinearMap := by
    rw [RepresentationTheory.Auxiliary.MutualCentralizers.permutationGroupAlgebraAction]
    rw [MonoidAlgebra.lift_apply]
    simp only [RepresentationTheory.Auxiliary.MutualCentralizers.permutationAction, MonoidHom.coe_mk, OneHom.coe_mk]
    rw [Finsupp.sum]
  suffices h : RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.endomorphismToPolynomial k N n slot (RepresentationTheory.Auxiliary.MutualCentralizers.permutationGroupAlgebraAction ℂ (RepresentationTheory.TensorPolynomial.Contraction.TensorPolynomial.AuxiliaryIndexType N) n x)
      ∈ Algebra.adjoin ℂ (Set.range (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.listIndexedElement k N)) by exact h
  rw [hxsum, map_sum]
  refine Subalgebra.sum_mem _ fun σ _ => ?_
  rw [map_smul]
  exact Subalgebra.smul_mem _ (mapped_permutation_equiv_mem_adjoin_range k N n slot σ) _

/-- The designated subalgebra is contained in the algebra generated by the range of the distinguished family. -/
theorem designated_subalgebra_le_adjoin_range :
    RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.complexSubalgebra k N ≤ Algebra.adjoin ℂ (Set.range (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.listIndexedElement k N)) := by
  intro f hf
  set S := Algebra.adjoin ℂ (Set.range (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.listIndexedElement k N)) with hS
  rw [← sum_weightedHomogeneousComponent (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.variableWeight k N) f]

  set s : Finset (Fin k →₀ ℕ) := f.support.image (Finsupp.weight (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.variableWeight k N)) with hs
  have hsub : (Function.support fun m => weightedHomogeneousComponent (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.variableWeight k N) m f)
      ⊆ (s : Set (Fin k →₀ ℕ)) := by
    intro m hm
    simp only [Function.mem_support] at hm
    by_contra hmem
    apply hm
    apply weightedHomogeneousComponent_eq_zero'
    intro d hd hweq
    apply hmem
    rw [hs, Finset.coe_image, Set.mem_image]
    exact ⟨d, hd, hweq⟩
  rw [finsum_eq_finsetSum_of_support_subset _ hsub]
  refine Subalgebra.sum_mem _ ?_
  intro d _
  exact mem_adjoin_range_of_isWeightedHomogeneous_of_mem_subalgebra k N d
    (weightedHomogeneousComponent_isWeightedHomogeneous d f)
    (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.weightedHomogeneousComponent_mem_complexSubalgebra k N d hf)

/-- The algebra generated by the range of the distinguished family agrees with the designated subalgebra. -/
@[source_ref "Chapter5/Problem5.24.2" (role := primary)]
theorem adjoin_range_eq_designated_subalgebra :
    Algebra.adjoin ℂ (Set.range (RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.listIndexedElement k N)) = RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.complexSubalgebra k N :=
  le_antisymm
    (Algebra.adjoin_le (by rintro _ ⟨w, rfl⟩; exact RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.listIndexedElement_mem_complexSubalgebra k N w))
    (designated_subalgebra_le_adjoin_range k N)

end RepresentationTheory.TraceAlgebra.Generation
