/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENCE.
Authors: Kim Morrison
-/
import Mathlib.Algebra.FreeAlgebra
import Mathlib.RingTheory.Congruence.Hom
import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import RepresentationTheory.Alignment.Attribute

/-! # Auxiliary free-algebra constructions -/

namespace RepresentationTheory.FreeAlgebra.RelationQuotient

section Presentation

variable (k : Type*) [CommRing k] (X R : Type*) (rel : R → FreeAlgebra k X)

/-- The ring congruence on a free algebra generated by a family of relations. -/
abbrev FreeAlgebra.relationRingCon : RingCon (FreeAlgebra k X) :=
  (TwoSidedIdeal.span (Set.range rel)).ringCon

/-- An auxiliary type depending on a free algebra and a family of its elements. -/
@[source_ref "Chapter2/Discussion_2.1_overview/Derived4" (role := supporting),
  source_ref "Chapter2/Discussion_2.6" (role := supporting)]
abbrev FreeAlgebra.AuxiliaryType : Type _ := (_root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.relationRingCon k X R rel).Quotient

end Presentation

variable {k : Type*} [CommRing k] {X R : Type*} (rel : R → FreeAlgebra k X)

/-- The canonical algebra homomorphism from the free algebra to the auxiliary algebra. -/
noncomputable def FreeAlgebra.AuxiliaryType.auxiliaryAlgHom : FreeAlgebra k X →ₐ[k] _root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.AuxiliaryType k X R rel :=
  (_root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.relationRingCon k X R rel).mkₐ k

/-- The auxiliary algebra homomorphism from the free algebra is surjective. -/
theorem FreeAlgebra.AuxiliaryType.auxiliaryAlgHom_surjective : Function.Surjective (auxiliaryAlgHom rel) :=
  (_root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.relationRingCon k X R rel).mkₐ_surjective (α := k)

/-- The canonical map from the generator type into the auxiliary type. -/
@[source_ref "Chapter2/Discussion_2.6" (role := supporting)]
noncomputable def FreeAlgebra.AuxiliaryType.of (x : X) : _root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.AuxiliaryType k X R rel :=
  auxiliaryAlgHom rel (FreeAlgebra.ι k x)

/-- The canonical generator map agrees with the auxiliary algebra homomorphism applied to the free-algebra inclusion. -/
theorem FreeAlgebra.AuxiliaryType.of_eq_auxiliaryAlgHom_generator (x : X) : of rel x = auxiliaryAlgHom rel (FreeAlgebra.ι k x) := rfl

/-- The images of the generators algebraically generate the enclosing auxiliary algebra. -/
@[source_ref "Chapter2/Discussion_2.6" (role := primary)]
theorem FreeAlgebra.AuxiliaryType.algebra_adjoin_generators_eq_top : Algebra.adjoin k (Set.range (of rel)) = ⊤ := by
  rw [Algebra.adjoin_range_eq_range_freeAlgebra_lift]
  have h : FreeAlgebra.lift k (of rel) = auxiliaryAlgHom rel := by
    apply FreeAlgebra.hom_ext
    funext x
    simp [of_eq_auxiliaryAlgHom_generator]
  rw [h, AlgHom.range_eq_top]
  exact auxiliaryAlgHom_surjective rel

/-- Each specified element maps to zero under the auxiliary algebra homomorphism. -/
@[simp, source_ref "Chapter2/Discussion_2.6" (role := primary)]
theorem FreeAlgebra.AuxiliaryType.auxiliaryAlgHom_relation (r : R) : auxiliaryAlgHom rel (rel r) = 0 := by
  have h : _root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.relationRingCon k X R rel (rel r) 0 := by
    rw [TwoSidedIdeal.rel_iff, sub_zero]
    exact TwoSidedIdeal.subset_span ⟨r, rfl⟩
  have : (_root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.relationRingCon k X R rel).mk' (rel r) = (_root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.relationRingCon k X R rel).mk' 0 :=
    (RingCon.eq _).mpr h
  simpa [auxiliaryAlgHom] using this

section Lift

variable {A : Type*} [Ring A] [Algebra k A]

/-- A free-algebra lift killing the relations has a kernel containing their generated ring congruence. -/
theorem FreeAlgebra.AuxiliaryType.relationRingCon_le_ker_freeLift (a : X → A) (ha : ∀ r, FreeAlgebra.lift k a (rel r) = 0) :
    _root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.relationRingCon k X R rel ≤ RingCon.ker (FreeAlgebra.lift k a).toRingHom := by
  have hsub : TwoSidedIdeal.span (Set.range rel) ≤
      TwoSidedIdeal.ker (FreeAlgebra.lift k a).toRingHom := by
    rw [TwoSidedIdeal.span_le]
    rintro _ ⟨r, rfl⟩
    rw [SetLike.mem_coe, TwoSidedIdeal.mem_ker]
    exact ha r
  intro p q hpq
  rw [RingCon.ker_apply]
  change FreeAlgebra.lift k a p = FreeAlgebra.lift k a q
  rw [← sub_eq_zero, ← map_sub]
  exact (TwoSidedIdeal.mem_ker _).1 (hsub ((TwoSidedIdeal.rel_iff _ _ _).1 hpq))

/-- Constructs an algebra homomorphism from the auxiliary algebra when the proposed generator values annihilate the specified elements. -/
@[source_ref "Chapter2/Discussion_2.1_irreducible_indecomposable/Derived9" (role := supporting)]
noncomputable def FreeAlgebra.AuxiliaryType.lift (a : X → A) (ha : ∀ r, FreeAlgebra.lift k a (rel r) = 0) :
    _root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.AuxiliaryType k X R rel →ₐ[k] A :=
  (_root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.relationRingCon k X R rel).liftₐ (FreeAlgebra.lift k a) (relationRingCon_le_ker_freeLift rel a ha)

/-- Composing the lift with the auxiliary algebra homomorphism agrees with the free-algebra lift. -/
@[simp] theorem FreeAlgebra.AuxiliaryType.lift_auxiliaryAlgHom (a : X → A) (ha : ∀ r, FreeAlgebra.lift k a (rel r) = 0)
    (p : FreeAlgebra k X) : lift rel a ha (auxiliaryAlgHom rel p) = FreeAlgebra.lift k a p := rfl

/-- The lifted homomorphism takes each canonical generator to its prescribed value. -/
@[simp] theorem FreeAlgebra.AuxiliaryType.lift_of (a : X → A) (ha : ∀ r, FreeAlgebra.lift k a (rel r) = 0) (x : X) :
    lift rel a ha (of rel x) = a x := by
  rw [of_eq_auxiliaryAlgHom_generator, lift_auxiliaryAlgHom, FreeAlgebra.lift_ι_apply]

/-- Algebra homomorphisms out of the auxiliary algebra are equal when they agree on generators. -/
@[source_ref "Chapter2/Discussion_2.1_irreducible_indecomposable/Derived9" (role := supporting)]
theorem FreeAlgebra.AuxiliaryType.algHom_ext {F G : _root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.AuxiliaryType k X R rel →ₐ[k] A}
    (h : ∀ x, F (of rel x) = G (of rel x)) : F = G := by
  have hcomp : F.comp (auxiliaryAlgHom rel) = G.comp (auxiliaryAlgHom rel) := FreeAlgebra.hom_ext (funext h)
  refine AlgHom.ext fun q => ?_
  obtain ⟨p, rfl⟩ := auxiliaryAlgHom_surjective rel q
  exact congrArg (fun φ : FreeAlgebra k X →ₐ[k] A => φ p) hcomp

/-- A map from generators whose free extension kills every specified element induces a unique algebra homomorphism from the auxiliary algebra. -/
theorem FreeAlgebra.AuxiliaryType.existsUnique_algHom_of_relations_vanish (a : X → A) (ha : ∀ r, FreeAlgebra.lift k a (rel r) = 0) :
    ∃! F : _root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.AuxiliaryType k X R rel →ₐ[k] A, ∀ x, F (of rel x) = a x :=
  ⟨lift rel a ha, lift_of rel a ha, fun _ hG => algHom_ext rel fun x => (hG x).trans
    (lift_of rel a ha x).symm⟩

/-- The free-algebra lift determined by an algebra homomorphism on the auxiliary algebra vanishes on every specified element. -/
theorem FreeAlgebra.AuxiliaryType.relations_vanish_under_lift (F : _root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.AuxiliaryType k X R rel →ₐ[k] A) (r : R) :
    FreeAlgebra.lift k (fun x => F (of rel x)) (rel r) = 0 := by
  have hcomp : FreeAlgebra.lift k (fun x => F (of rel x)) = F.comp (auxiliaryAlgHom rel) :=
    FreeAlgebra.hom_ext (funext fun x => FreeAlgebra.lift_ι_apply _ _)
  rw [hcomp]
  simp

end Lift

/-- For finite index types, the auxiliary type is equal to the quotient by the ring congruence generated by the specified range. -/
@[source_ref "Chapter2/Discussion_2.6" (role := primary)]
theorem FreeAlgebra.AuxiliaryType.eq_ringConQuotient_span_range (k : Type*) [CommRing k] (n m : ℕ)
    (f : Fin m → FreeAlgebra k (Fin n)) :
    _root_.RepresentationTheory.FreeAlgebra.RelationQuotient.FreeAlgebra.AuxiliaryType k (Fin n) (Fin m) f =
      (TwoSidedIdeal.span (Set.range f)).ringCon.Quotient := rfl

namespace FreeAlgebra.AuxiliaryType

example (k : Type*) [CommRing k] (rel : Fin 1 → FreeAlgebra k (Fin 2))
    (hrel : rel 0 = FreeAlgebra.ι k 1 * FreeAlgebra.ι k 0
      - FreeAlgebra.ι k 0 * FreeAlgebra.ι k 1 - 1) :
    of rel 1 * of rel 0 = of rel 0 * of rel 1 + 1 := by
  have h : auxiliaryAlgHom rel (rel 0) = 0 := auxiliaryAlgHom_relation rel 0
  rw [hrel, map_sub, map_sub, map_mul, map_mul, map_one, sub_sub, sub_eq_zero] at h
  simpa [of_eq_auxiliaryAlgHom_generator] using h

end FreeAlgebra.AuxiliaryType

end RepresentationTheory.FreeAlgebra.RelationQuotient
