/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

import RepresentationTheory.Algebra.Module.Dual.SimpleFamilies

open Module

variable (k : Type*) (A : Type*) (V : Type*)
  [CommRing k] [Ring A] [Algebra k A]
  [AddCommGroup V] [Module k V] [Module A V] [IsScalarTower k A V]
  [Free k V] [Module.Finite k V]

namespace RepresentationTheory.Algebra.Trace.CommutatorQuotient

/-- The trace-valued function of a finite free module action takes the same value on x times y and y times x. -/
theorem representationTrace_mul_comm (x y : A) :
    RepresentationTheory.Algebra.Module.Dual.SimpleFamilies.moduleDualElement k A V (x * y) =
      RepresentationTheory.Algebra.Module.Dual.SimpleFamilies.moduleDualElement k A V (y * x) := by
  simp only [RepresentationTheory.Algebra.Module.Dual.SimpleFamilies.moduleDualElement,
    LinearMap.comp_apply, AlgHom.toLinearMap_apply, map_mul]
  exact LinearMap.trace_mul_comm k _ _

/-- The base-linear submodule of an algebra generated by multiplicative commutators. -/
def commutatorSubmodule : Submodule k A :=
  Submodule.span k {z : A | ∃ x y : A, z = x * y - y * x}

/-- The commutator submodule is contained in the kernel of the trace-valued function of every finite free module action. -/
theorem commutatorSubmodule_le_trace_ker :
    commutatorSubmodule k A ≤ LinearMap.ker
      (RepresentationTheory.Algebra.Module.Dual.SimpleFamilies.moduleDualElement k A V) := by
  rw [commutatorSubmodule, Submodule.span_le]
  rintro z ⟨x, y, rfl⟩
  simp only [SetLike.mem_coe, LinearMap.mem_ker, map_sub]
  rw [representationTrace_mul_comm, sub_self]

/-- The trace-valued function of a finite free module action descends to a linear map from the quotient by the commutator submodule. -/
noncomputable def traceOnCommutatorQuotient : (A ⧸ commutatorSubmodule k A) →ₗ[k] k :=
  Submodule.liftQ _
    (RepresentationTheory.Algebra.Module.Dual.SimpleFamilies.moduleDualElement k A V)
    (commutatorSubmodule_le_trace_ker k A V)

/-- The descended trace map evaluated on the quotient class of an algebra element equals the trace-valued function evaluated on that element. -/
theorem traceOnCommutatorQuotient_mk (a : A) :
    traceOnCommutatorQuotient k A V (Submodule.Quotient.mk a) =
      RepresentationTheory.Algebra.Module.Dual.SimpleFamilies.moduleDualElement k A V a :=
  rfl

end RepresentationTheory.Algebra.Trace.CommutatorQuotient
