/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENCE.
Authors: mathlib-initiative
-/

import RepresentationTheory.Matrix.MvPolynomialRightMul
import RepresentationTheory.Auxiliary.GeneralLinearCoordinateLocalization

namespace RepresentationTheory.LinearAlgebra.Matrix.GeneralLinearGroup.LocalizationAction

open MvPolynomial
open RepresentationTheory.Matrix.MvPolynomialRightMul.Matrix
open RepresentationTheory.Auxiliary.GeneralLinearCoordinateLocalization

variable {k : Type*} [Field k] {N : ℕ}

local notation3 "O" => Localization.Away (auxiliary_matrix_polynomial k N)

/-- Associates a matrix with an algebra homomorphism from the polynomial algebra to the indicated
localization. -/
noncomputable def matrixLocalizationMap (M : Matrix (Fin N) (Fin N) k) :
    MvPolynomial (Fin N × Fin N) k →ₐ[k]
      Localization.Away (auxiliary_matrix_polynomial k N) :=
  (IsScalarTower.toAlgHom k (MvPolynomial (Fin N × Fin N) k)
      (Localization.Away (auxiliary_matrix_polynomial k N))).comp
    (mvPolynomialRightMul M)

/-- On every polynomial, this homomorphism is the algebra-map image of the associated polynomial
transformation. -/
@[simp] theorem matrixLocalizationMap_apply (M : Matrix (Fin N) (Fin N) k)
    (a : MvPolynomial (Fin N × Fin N) k) :
    matrixLocalizationMap M a =
      algebraMap _ (Localization.Away (auxiliary_matrix_polynomial k N))
        (mvPolynomialRightMul M a) :=
  rfl

/-- The polynomial map associated with a matrix sends the localization element to its
determinant-scaled value. -/
theorem matrixPolynomialMap_localizingElement (M : Matrix (Fin N) (Fin N) k) :
    mvPolynomialRightMul M (auxiliary_matrix_polynomial k N) =
      MvPolynomial.C M.det * auxiliary_matrix_polynomial k N :=
  mvPolynomialRightMul_apply_det M

/-- Elements generated by the localization element map to units under the map associated with an
invertible matrix. -/
theorem matrixLocalizationMap_isUnit_on_powers
    (g : Matrix.GeneralLinearGroup (Fin N) k)
    (y : Submonoid.powers (auxiliary_matrix_polynomial k N)) :
    IsUnit (matrixLocalizationMap (g : Matrix (Fin N) (Fin N) k)
      (y : MvPolynomial (Fin N × Fin N) k)) := by
  obtain ⟨n, hn⟩ := y.2
  rw [← hn]
  change IsUnit (matrixLocalizationMap (g : Matrix (Fin N) (Fin N) k)
    (auxiliary_matrix_polynomial k N ^ n))
  rw [matrixLocalizationMap_apply, map_pow, map_pow]
  refine IsUnit.pow n ?_
  rw [matrixPolynomialMap_localizingElement, map_mul]
  refine IsUnit.mul ?_ ?_
  · have hdet : IsUnit ((g : Matrix (Fin N) (Fin N) k).det) :=
      (Matrix.isUnit_iff_isUnit_det _).mp (Units.isUnit g)
    exact (hdet.map (MvPolynomial.C : k →+* MvPolynomial (Fin N × Fin N) k)).map
      (algebraMap (MvPolynomial (Fin N × Fin N) k)
        (Localization.Away (auxiliary_matrix_polynomial k N)))
  · exact IsLocalization.Away.algebraMap_isUnit
      (S := Localization.Away (auxiliary_matrix_polynomial k N))
      (auxiliary_matrix_polynomial k N)

/-- Associates an invertible matrix with an algebra homomorphism of the indicated localization. -/
noncomputable def generalLinearGroupLocalizationMap
    (g : Matrix.GeneralLinearGroup (Fin N) k) :
    Localization.Away (auxiliary_matrix_polynomial k N) →ₐ[k]
      Localization.Away (auxiliary_matrix_polynomial k N) :=
  IsLocalization.liftAlgHom
    (f := matrixLocalizationMap (g : Matrix (Fin N) (Fin N) k))
    (matrixLocalizationMap_isUnit_on_powers g)

/-- The localization map associated with an invertible matrix agrees on polynomial images with the
displayed polynomial transformation. -/
@[simp] theorem generalLinearGroupLocalizationMap_algebraMap_apply
    (g : Matrix.GeneralLinearGroup (Fin N) k)
    (a : MvPolynomial (Fin N × Fin N) k) :
    generalLinearGroupLocalizationMap g
      (algebraMap _ (Localization.Away (auxiliary_matrix_polynomial k N)) a) =
        algebraMap _ _ (mvPolynomialRightMul (g : Matrix (Fin N) (Fin N) k) a) := by
  simp only [generalLinearGroupLocalizationMap, IsLocalization.coe_liftAlgHom,
    IsLocalization.lift_eq]
  rfl

/-- The map attached to the identity invertible matrix is the identity algebra homomorphism. -/
theorem generalLinearGroupLocalizationMap_one :
    generalLinearGroupLocalizationMap
      (1 : Matrix.GeneralLinearGroup (Fin N) k) =
        AlgHom.id k (Localization.Away (auxiliary_matrix_polynomial k N)) := by
  apply IsLocalization.algHom_ext (R := k)
    (A := MvPolynomial (Fin N × Fin N) k)
    (L := Localization.Away (auxiliary_matrix_polynomial k N))
    (B := Localization.Away (auxiliary_matrix_polynomial k N))
    (Submonoid.powers (auxiliary_matrix_polynomial k N))
  apply AlgHom.ext
  intro a
  rw [AlgHom.comp_apply, AlgHom.comp_apply]
  change generalLinearGroupLocalizationMap
      (1 : Matrix.GeneralLinearGroup (Fin N) k)
      (algebraMap (MvPolynomial (Fin N × Fin N) k)
        (Localization.Away (auxiliary_matrix_polynomial k N)) a) =
    AlgHom.id k (Localization.Away (auxiliary_matrix_polynomial k N))
      (algebraMap (MvPolynomial (Fin N × Fin N) k)
        (Localization.Away (auxiliary_matrix_polynomial k N)) a)
  rw [generalLinearGroupLocalizationMap_algebraMap_apply, AlgHom.id_apply,
    Units.val_one, mvPolynomialRightMul_one, AlgHom.id_apply]

/-- The maps attached to a product of invertible matrices compose in the corresponding order. -/
theorem generalLinearGroupLocalizationMap_mul
    (g₁ g₂ : Matrix.GeneralLinearGroup (Fin N) k) :
    generalLinearGroupLocalizationMap (g₁ * g₂) =
      (generalLinearGroupLocalizationMap g₁).comp
        (generalLinearGroupLocalizationMap g₂) := by
  apply IsLocalization.algHom_ext (R := k)
    (A := MvPolynomial (Fin N × Fin N) k)
    (L := Localization.Away (auxiliary_matrix_polynomial k N))
    (B := Localization.Away (auxiliary_matrix_polynomial k N))
    (Submonoid.powers (auxiliary_matrix_polynomial k N))
  apply AlgHom.ext
  intro a
  rw [AlgHom.comp_apply, AlgHom.comp_apply]
  change generalLinearGroupLocalizationMap (g₁ * g₂)
      (algebraMap (MvPolynomial (Fin N × Fin N) k)
        (Localization.Away (auxiliary_matrix_polynomial k N)) a) =
    (generalLinearGroupLocalizationMap g₁).comp
      (generalLinearGroupLocalizationMap g₂)
      (algebraMap (MvPolynomial (Fin N × Fin N) k)
        (Localization.Away (auxiliary_matrix_polynomial k N)) a)
  rw [generalLinearGroupLocalizationMap_algebraMap_apply, AlgHom.comp_apply,
    generalLinearGroupLocalizationMap_algebraMap_apply,
    generalLinearGroupLocalizationMap_algebraMap_apply, Units.val_mul,
    mvPolynomialRightMul_mul, AlgHom.comp_apply]

/-- Packages the general linear group action on the indicated localization as a representation. -/
noncomputable def generalLinearGroupLocalizationRepresentation
    (k : Type*) [Field k] (N : ℕ) :
    Representation k (Matrix.GeneralLinearGroup (Fin N) k)
      (Localization.Away (auxiliary_matrix_polynomial k N)) where
  toFun g := (generalLinearGroupLocalizationMap g).toLinearMap
  map_one' := by
    change (generalLinearGroupLocalizationMap
      (1 : Matrix.GeneralLinearGroup (Fin N) k)).toLinearMap = _
    rw [generalLinearGroupLocalizationMap_one]; rfl
  map_mul' g₁ g₂ := by
    change (generalLinearGroupLocalizationMap (g₁ * g₂)).toLinearMap = _
    rw [generalLinearGroupLocalizationMap_mul]; rfl

/-- The underlying endomorphism of the representation is the localization map attached to the same
invertible matrix. -/
@[simp] theorem generalLinearGroupLocalizationRepresentation_apply_eq_map
    (g : Matrix.GeneralLinearGroup (Fin N) k)
    (x : Localization.Away (auxiliary_matrix_polynomial k N)) :
    generalLinearGroupLocalizationRepresentation k N g x =
      generalLinearGroupLocalizationMap g x :=
  rfl

/-- Evaluating the representation on a polynomial image gives the polynomial transformation
displayed in the formal statement. -/
theorem generalLinearGroupLocalizationRepresentation_algebraMap_apply
    (g : Matrix.GeneralLinearGroup (Fin N) k)
    (a : MvPolynomial (Fin N × Fin N) k) :
    generalLinearGroupLocalizationRepresentation k N g
      (algebraMap _ (Localization.Away (auxiliary_matrix_polynomial k N)) a) =
        algebraMap _ _ (generalLinearGroupMvPolynomialRightMul k N g a) :=
  generalLinearGroupLocalizationMap_algebraMap_apply g a

/-- The representation sends the inverse of the localization element to the indicated
inverse-determinant scalar multiple. -/
theorem generalLinearGroupLocalizationRepresentation_apply_invSelf
    (g : Matrix.GeneralLinearGroup (Fin N) k) :
    generalLinearGroupLocalizationRepresentation k N g
      (IsLocalization.Away.invSelf (auxiliary_matrix_polynomial k N)) =
        ((g : Matrix (Fin N) (Fin N) k).det)⁻¹ •
          IsLocalization.Away.invSelf (auxiliary_matrix_polynomial k N) := by
  rw [generalLinearGroupLocalizationRepresentation_apply_eq_map]
  have hd_ne : (g : Matrix (Fin N) (Fin N) k).det ≠ 0 :=
    ((Matrix.isUnit_iff_isUnit_det _).mp (Units.isUnit g)).ne_zero
  set d := (g : Matrix (Fin N) (Fin N) k).det with hd
  set dpoly := algebraMap (MvPolynomial (Fin N × Fin N) k)
    (Localization.Away (auxiliary_matrix_polynomial k N))
    (auxiliary_matrix_polynomial k N) with hdpoly
  set inv : Localization.Away (auxiliary_matrix_polynomial k N) :=
    IsLocalization.Away.invSelf (auxiliary_matrix_polynomial k N) with hinv
  set u := algebraMap k (Localization.Away (auxiliary_matrix_polynomial k N)) d *
    dpoly with hu
  have hCd : algebraMap (MvPolynomial (Fin N × Fin N) k)
        (Localization.Away (auxiliary_matrix_polynomial k N))
        (MvPolynomial.C d) =
      algebraMap k (Localization.Away (auxiliary_matrix_polynomial k N)) d := by
    rw [← MvPolynomial.algebraMap_eq, ← IsScalarTower.algebraMap_apply]
  have key1 : generalLinearGroupLocalizationMap g dpoly = u := by
    rw [hdpoly, generalLinearGroupLocalizationMap_algebraMap_apply,
      matrixPolynomialMap_localizingElement, map_mul, hCd, hu, ← hdpoly]
  have hmulinv : dpoly * inv = 1 := by
    rw [hdpoly, hinv]; exact
      IsLocalization.Away.mul_invSelf (auxiliary_matrix_polynomial k N)
  have hE1 : u * generalLinearGroupLocalizationMap g inv = 1 := by
    have h := congrArg (generalLinearGroupLocalizationMap g) hmulinv
    rwa [map_mul, map_one, key1] at h
  have hE2 : u * (d⁻¹ • inv) = 1 := by
    rw [hu, Algebra.smul_def,
      show algebraMap k (Localization.Away (auxiliary_matrix_polynomial k N)) d *
          dpoly *
          (algebraMap k (Localization.Away (auxiliary_matrix_polynomial k N)) d⁻¹ *
            inv) =
        (algebraMap k (Localization.Away (auxiliary_matrix_polynomial k N)) d *
          algebraMap k (Localization.Away (auxiliary_matrix_polynomial k N)) d⁻¹) *
            (dpoly * inv) by ring,
      hmulinv, mul_one, ← map_mul, mul_inv_cancel₀ hd_ne, map_one]
  calc generalLinearGroupLocalizationMap g inv =
      generalLinearGroupLocalizationMap g inv * (u * (d⁻¹ • inv)) := by
        rw [hE2, mul_one]
    _ = u * generalLinearGroupLocalizationMap g inv * (d⁻¹ • inv) := by ring
    _ = d⁻¹ • inv := by rw [hE1, one_mul]

end RepresentationTheory.LinearAlgebra.Matrix.GeneralLinearGroup.LocalizationAction
