/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENCE.
Authors: mathlib-initiative
-/

import Mathlib
import RepresentationTheory.Alignment.Attribute
import RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions
import RepresentationTheory.SymmetricGroup.PartitionGroupAlgebra
import RepresentationTheory.Partitions.SquareScalar
import RepresentationTheory.PartitionAuxiliary

/-!
# Auxiliary submodules from partition projectors

This module compares left ideals generated by normalized and unnormalized products of two
partition-indexed group-algebra elements. Right multiplication by either factor gives maps
between the two spans. Their nonzero scalar composites yield a linear equivalence, and scalar
normalization leaves the generated submodule unchanged.
-/

namespace RepresentationTheory.AuxiliarySubmodules

noncomputable section

/-- A submodule indexed by a natural number and a partition of that number. -/
noncomputable def indexedSubmodule (n : ℕ) (la : Nat.Partition n) :
    Submodule (RepresentationTheory.PartitionAuxiliary.natIndexedType n) (RepresentationTheory.PartitionAuxiliary.natIndexedType n) :=
  Submodule.span (RepresentationTheory.PartitionAuxiliary.natIndexedType n) {RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementD n la}

/-- Right multiplication `x ↦ x·y`, as a left-`ℂ[Sₙ]`-module homomorphism. Left multiplication
commutes past it, so it is `ℂ[Sₙ]`-linear for the left regular action. -/
private def rMul (n : ℕ) (y : RepresentationTheory.PartitionAuxiliary.natIndexedType n) :
    RepresentationTheory.PartitionAuxiliary.natIndexedType n →ₗ[RepresentationTheory.PartitionAuxiliary.natIndexedType n] RepresentationTheory.PartitionAuxiliary.natIndexedType n where
  toFun x := x * y
  map_add' x₁ x₂ := add_mul x₁ x₂ y
  map_smul' r x := by simp only [smul_eq_mul, RingHom.id_apply, mul_assoc]

/-! ## The two Lemma 5.13.1 scalars and their nonvanishing -/

/-- `b_λ·a_λ = YoungSymmetrizer` is nonzero (its square is nonzero). -/
private lemma youngSym_ne (n : ℕ) (la : Nat.Partition n) :
    RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la ≠ 0 :=
  fun h => RepresentationTheory.PartitionAuxiliary.self_mul_ne_zero n la (by rw [h, mul_zero])

/-- `(b_λ a_λ)² = α·(b_λ a_λ)` with `α ≠ 0` (Lemma 5.13.3 plus `(b_λ a_λ)² ≠ 0`). -/
private lemma youngSym_sq (n : ℕ) (la : Nat.Partition n) :
    ∃ α : ℂ, α ≠ 0 ∧
      RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la = α • RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la := by
  obtain ⟨α, hα⟩ := RepresentationTheory.Partitions.SquareScalar.exists_mul_self_eq_smul n la
  exact ⟨α, fun h => RepresentationTheory.PartitionAuxiliary.self_mul_ne_zero n la (by rw [hα, h, zero_smul]), hα⟩

/-- There exists a nonzero scalar such that the square of the displayed product equals its scalar
multiple. -/
@[source_ref "Chapter5/Discussion_proof_of_Theorem5.12.2" (role := supporting)]
theorem product_sq_eq_smul (n : ℕ) (la : Nat.Partition n) :
    ∃ β : ℂ, β ≠ 0 ∧
      (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) *
        (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) =
        β • (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) := by
  obtain ⟨ℓ, hℓ⟩ := RepresentationTheory.SymmetricGroup.PartitionGroupAlgebra.exists_fixed_sign_sandwich_eq_smul_mul n la
  obtain ⟨α, hαne, hα⟩ := youngSym_sq n la
  have hsq : (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) *
      (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) =
      ℓ (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la) • (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) := by
    have h := hℓ (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la)
    rw [show RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la
        = (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) *
          (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) from by
        simp only [RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC, mul_assoc]] at h
    exact h
  refine ⟨ℓ (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la), ?_, hsq⟩
  intro hβ0
  rw [hβ0, zero_smul] at hsq
  have hcube0 : RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la = 0 := by
    rw [show RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la
        = RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la *
          ((RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) *
           (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la)) * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la from by
        simp only [RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC, mul_assoc], hsq, mul_zero, zero_mul]
  have hcube_eq : RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la
      = (α * α) • RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la := by
    rw [hα, smul_mul_assoc, hα, smul_smul]
  rw [hcube_eq] at hcube0
  exact (fun h => RepresentationTheory.PartitionAuxiliary.self_mul_ne_zero n la (by rw [h, mul_zero]))
    ((smul_eq_zero.mp hcube0).resolve_left (mul_ne_zero hαne hαne))

/-! ## The composites of the right-multiplication maps -/

/-- `(x·b_λ)·a_λ = α·x` for `x ∈ ℂ[Sₙ]·(b_λ a_λ)`: the "there and back" composite on the
Specht module is multiplication by the Lemma 5.13.3 scalar `α`. -/
private lemma comp_left (n : ℕ) (la : Nat.Partition n) (α : ℂ)
    (hα : RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la = α • RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la) :
    ∀ z ∈ RepresentationTheory.PartitionAuxiliary.partitionSubmodule n la,
      z * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la = α • z := by
  intro z hz
  simp only [RepresentationTheory.PartitionAuxiliary.partitionSubmodule, Submodule.mem_span_singleton] at hz
  obtain ⟨x, rfl⟩ := hz
  rw [smul_eq_mul,
    show x * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la
      = x * (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la) from by
        simp only [RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC, mul_assoc],
    hα, mul_smul_comm]

/-- `(w·a_λ)·b_λ = β·w` for `w ∈ ℂ[Sₙ]·(a_λ b_λ)`: the "there and back" composite on the
source ideal is multiplication by the dual scalar `β`. -/
private lemma comp_right (n : ℕ) (la : Nat.Partition n) (β : ℂ)
    (hβ : (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) *
          (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) =
          β • (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la)) :
    ∀ w ∈ Submodule.span (RepresentationTheory.PartitionAuxiliary.natIndexedType n)
        {RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la},
      w * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la = β • w := by
  intro w hw
  simp only [Submodule.mem_span_singleton] at hw
  obtain ⟨y, rfl⟩ := hw
  rw [smul_eq_mul,
    show y * (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la
        * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la
      = y * ((RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) *
             (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la)) from by
        simp only [mul_assoc],
    hβ, mul_smul_comm]

/-! ## The two right-multiplication maps land in the opposite ideal -/

/-- Right multiplication by `b_λ` carries `ℂ[Sₙ]·(b_λ a_λ)` into `ℂ[Sₙ]·(a_λ b_λ)`. -/
private lemma fwd_maps (n : ℕ) (la : Nat.Partition n) :
    ∀ z ∈ RepresentationTheory.PartitionAuxiliary.partitionSubmodule n la, z * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la ∈
      Submodule.span (RepresentationTheory.PartitionAuxiliary.natIndexedType n)
        {RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la} := by
  intro z hz
  simp only [RepresentationTheory.PartitionAuxiliary.partitionSubmodule, Submodule.mem_span_singleton] at hz ⊢
  obtain ⟨x, rfl⟩ := hz
  refine ⟨x * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la, ?_⟩
  rw [smul_eq_mul, smul_eq_mul]
  simp only [RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC, mul_assoc]

/-- Right multiplication by `a_λ` carries `ℂ[Sₙ]·(a_λ b_λ)` back into `ℂ[Sₙ]·(b_λ a_λ)`. -/
private lemma bwd_maps (n : ℕ) (la : Nat.Partition n) :
    ∀ w ∈ Submodule.span (RepresentationTheory.PartitionAuxiliary.natIndexedType n)
        {RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la},
      w * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la ∈ RepresentationTheory.PartitionAuxiliary.partitionSubmodule n la := by
  intro w hw
  simp only [RepresentationTheory.PartitionAuxiliary.partitionSubmodule, Submodule.mem_span_singleton] at hw ⊢
  obtain ⟨y, rfl⟩ := hw
  refine ⟨y * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la, ?_⟩
  rw [smul_eq_mul, smul_eq_mul]
  simp only [RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC, mul_assoc]

/-! ## The isomorphism to the reversed-order span, then to the source ideal -/

/-- A linear equivalence from the auxiliary submodule to the span of the singleton containing the
displayed product. -/
noncomputable def auxiliarySubmoduleLinearEquivProductSpan (n : ℕ) (la : Nat.Partition n) :
    RepresentationTheory.PartitionAuxiliary.partitionSubmodule n la ≃ₗ[RepresentationTheory.PartitionAuxiliary.natIndexedType n]
      Submodule.span (RepresentationTheory.PartitionAuxiliary.natIndexedType n)
        {RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la} := by
  refine LinearEquiv.ofBijective
    ((rMul n (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la)).restrict (fwd_maps n la)) ⟨?_, ?_⟩
  · -- injective: `G ∘ F = α • id` with `α ≠ 0`
    obtain ⟨α, hαne, hα⟩ := youngSym_sq n la
    intro z₁ z₂ h
    have hFG : ∀ z : RepresentationTheory.PartitionAuxiliary.partitionSubmodule n la,
        ((rMul n (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la)).restrict (bwd_maps n la))
          ((rMul n (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la)).restrict (fwd_maps n la) z) = α • z :=
      fun z => Subtype.ext (comp_left n la α hα _ z.2)
    have h2 : α • z₁ = α • z₂ := by rw [← hFG z₁, ← hFG z₂, h]
    calc z₁ = α⁻¹ • (α • z₁) := by rw [smul_smul, inv_mul_cancel₀ hαne, one_smul]
      _ = α⁻¹ • (α • z₂) := by rw [h2]
      _ = z₂ := by rw [smul_smul, inv_mul_cancel₀ hαne, one_smul]
  · -- surjective: `F ∘ G = β • id` with `β ≠ 0`
    obtain ⟨β, hβne, hβ⟩ := product_sq_eq_smul n la
    intro w
    have hGF : ((rMul n (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la)).restrict (fwd_maps n la))
        (((rMul n (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la)).restrict (bwd_maps n la)) w) = β • w :=
      Subtype.ext (comp_right n la β hβ _ w.2)
    exact ⟨β⁻¹ • ((rMul n (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la)).restrict (bwd_maps n la)) w, by
      rw [LinearMap.map_smul_of_tower, hGF, smul_smul, inv_mul_cancel₀ hβne, one_smul]⟩

/-- `youngProjector = (|P_λ||Q_λ|)⁻¹·(a_λ b_λ)`: the source projector is the row-then-column
sum divided by the positive scalar `|P_λ|·|Q_λ|`. -/
private lemma youngProjector_eq_smul (n : ℕ) (la : Nat.Partition n) :
    RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementD n la =
      ((Nat.card (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionPermutationSubgroupB n la) : ℂ)⁻¹ * (Nat.card (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionPermutationSubgroupA n la) : ℂ)⁻¹) •
        (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la) := by
  rw [RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementD, RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementF, RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementE, Algebra.smul_mul_assoc,
    Algebra.mul_smul_comm, smul_smul]

/-- Scaling the generator by a nonzero complex number does not change the left ideal it spans. -/
private lemma span_smul_scalar_eq (n : ℕ) {c : ℂ} (hc : c ≠ 0) (y : RepresentationTheory.PartitionAuxiliary.natIndexedType n) :
    Submodule.span (RepresentationTheory.PartitionAuxiliary.natIndexedType n) {c • y} =
      Submodule.span (RepresentationTheory.PartitionAuxiliary.natIndexedType n) {y} := by
  rw [show c • y = (algebraMap ℂ (RepresentationTheory.PartitionAuxiliary.natIndexedType n) c) • y from
    (algebraMap_smul (RepresentationTheory.PartitionAuxiliary.natIndexedType n) c y).symm]
  exact Submodule.span_singleton_smul_eq
    ((isUnit_iff_ne_zero.mpr hc).map (algebraMap ℂ (RepresentationTheory.PartitionAuxiliary.natIndexedType n))) y

/-- The indexed submodule equals the span of the singleton containing the displayed product. -/
lemma indexedSubmodule_eq_span_product (n : ℕ) (la : Nat.Partition n) :
    indexedSubmodule n la =
      Submodule.span (RepresentationTheory.PartitionAuxiliary.natIndexedType n)
        {RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementB n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementA n la} := by
  rw [show indexedSubmodule n la =
      Submodule.span (RepresentationTheory.PartitionAuxiliary.natIndexedType n) {RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementD n la} from rfl,
    youngProjector_eq_smul]
  exact span_smul_scalar_eq n
    (mul_ne_zero (inv_ne_zero (Nat.cast_ne_zero.mpr Nat.card_pos.ne'))
      (inv_ne_zero (Nat.cast_ne_zero.mpr Nat.card_pos.ne'))) _

/-- The auxiliary submodule equals the span of the singleton containing the displayed product. -/
lemma auxiliarySubmodule_eq_span_product (n : ℕ) (la : Nat.Partition n) :
    RepresentationTheory.PartitionAuxiliary.partitionSubmodule n la =
      Submodule.span (RepresentationTheory.PartitionAuxiliary.natIndexedType n) {RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementE n la * RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementF n la} := by
  rw [show RepresentationTheory.PartitionAuxiliary.partitionSubmodule n la =
      Submodule.span (RepresentationTheory.PartitionAuxiliary.natIndexedType n) {RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la} from rfl,
    RepresentationTheory.SymmetricGroup.PartitionGroupAlgebra.right_idempotent_mul_left_idempotent]
  exact (span_smul_scalar_eq n
    (inv_ne_zero (mul_ne_zero (Nat.cast_ne_zero.mpr Nat.card_pos.ne')
      (Nat.cast_ne_zero.mpr Nat.card_pos.ne'))) (RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementC n la)).symm

/-- A linear equivalence from the auxiliary submodule to the indexed submodule. -/
@[source_ref "Chapter5/Discussion_Young_projectors" (role := supporting)]
noncomputable def auxiliarySubmoduleLinearEquivIndexedSubmodule (n : ℕ) (la : Nat.Partition n) :
    RepresentationTheory.PartitionAuxiliary.partitionSubmodule n la ≃ₗ[RepresentationTheory.PartitionAuxiliary.natIndexedType n] indexedSubmodule n la :=
  (auxiliarySubmoduleLinearEquivProductSpan n la).trans
    (LinearEquiv.ofEq _ _ (indexedSubmodule_eq_span_product n la).symm)

/-- The module carried by the indexed submodule is simple. -/
@[source_ref "Chapter5/Discussion_proof_of_Theorem5.12.2" (role := supporting)]
theorem indexedSubmodule_isSimple (n : ℕ) (la : Nat.Partition n) :
    IsSimpleModule (RepresentationTheory.PartitionAuxiliary.natIndexedType n) (indexedSubmodule n la) :=
  (auxiliarySubmoduleLinearEquivIndexedSubmodule n la).isSimpleModule_iff.mp
    (RepresentationTheory.PartitionAuxiliary.partitionSubmodule_isSimpleModule n la)

/-- The displayed auxiliary element does not vanish. -/
@[source_ref "Chapter5/Discussion_Young_projectors" (role := primary)]
theorem auxiliaryElement_ne_zero (n : ℕ) (la : Nat.Partition n) :
    RepresentationTheory.SymmetricGroup.PartitionAuxiliaryConstructions.auxiliaryPartitionGroupAlgebraElementD n la ≠ 0 := by
  intro hzero
  haveI : IsSimpleModule (RepresentationTheory.PartitionAuxiliary.natIndexedType n) (indexedSubmodule n la) :=
    indexedSubmodule_isSimple n la
  have hne : indexedSubmodule n la ≠ ⊥ :=
    Submodule.nontrivial_iff_ne_bot.mp
      (IsSimpleModule.nontrivial (RepresentationTheory.PartitionAuxiliary.natIndexedType n) (indexedSubmodule n la))
  apply hne
  simp [indexedSubmodule, hzero]

end

end RepresentationTheory.AuxiliarySubmodules
