/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENCE.
Authors: mathlib-initiative
-/
import Mathlib.Algebra.Homology.DerivedCategory.Ext.ExactSequences
import Mathlib.Algebra.Category.ModuleCat.Ext.HasExt
import Mathlib.Algebra.Category.ModuleCat.Projective
import Mathlib.Algebra.Homology.ShortComplex.ModuleCat
import Mathlib.CategoryTheory.Abelian.Projective.Dimension
import Mathlib.Algebra.Module.Opposite
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.Data.ZMod.Basic
import Mathlib.Data.ZMod.QuotientRing
import Mathlib.LinearAlgebra.TensorProduct.Quotient
import Mathlib.LinearAlgebra.Isomorphisms
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.RingTheory.EuclideanDomain
import Mathlib.Algebra.Polynomial.FieldDivision
import RepresentationTheory.Algebra.Homology.TensorProductConstruction
import RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses
import RepresentationTheory.CategoryTheory.LeftDerivedFunctor.ConnectingMorphisms
import RepresentationTheory.DerivedFunctorExactness

set_option backward.isDefEq.respectTransparency false

namespace RepresentationTheory.PolynomialQuotientZModAuxiliary

open _root_.CategoryTheory

universe u

private def opRegularEquiv (A : Type*) [Ring A] : A ≃ₗ[Aᵐᵒᵖ] Aᵐᵒᵖ where
  toFun := MulOpposite.op
  map_add' _ _ := rfl
  map_smul' c x := by
    change MulOpposite.op (x * MulOpposite.unop c) = c * MulOpposite.op x
    rw [MulOpposite.op_mul, MulOpposite.op_unop]
  invFun := MulOpposite.unop
  left_inv _ := rfl
  right_inv _ := rfl

private instance opRegularProjective (A : Type*) [Ring A] : Module.Projective Aᵐᵒᵖ A :=
  have : Module.Free Aᵐᵒᵖ A := Module.Free.of_equiv (opRegularEquiv A).symm
  Module.Projective.of_free

open Limits in

/-- In a short exact sequence, projectivity of the first two objects bounds the projective dimension of the third by one. -/
lemma hasProjectiveDimensionLT_two_of_shortExact
    {R : Type u} [Ring R] [Small.{u} R] {S : ShortComplex (ModuleCat.{u} R)}
    (hS : S.ShortExact) (h₁ : Projective S.X₁) (h₂ : Projective S.X₂) :
    HasProjectiveDimensionLT S.X₃ 2 := by
  haveI : HasProjectiveDimensionLT S.X₁ 1 := projective_iff_hasProjectiveDimensionLT_one.mp h₁
  haveI : HasProjectiveDimensionLT S.X₂ 1 := projective_iff_hasProjectiveDimensionLT_one.mp h₂
  haveI : HasProjectiveDimensionLT S.X₂ 2 := hasProjectiveDimensionLT_of_ge S.X₂ 1 2 (by omega)
  exact hS.hasProjectiveDimensionLT_X₃ 1 ‹_› ‹_›

open Limits in

private lemma isZero_obj_two_of_sixTerm_exact
    {D : Type*} [Category D] [Abelian D] {W : ComposableArrows D 5}
    (hW : W.Exact) (h1 : IsZero (W.obj 1)) (h3 : IsZero (W.obj 3)) :
    IsZero (W.obj 2) := by
  have e : (W.sc' hW.toIsComplex 1 2 3).Exact := hW.exact' 1 2 3
  exact e.isZero_X₂ (h1.eq_of_src _ _) (h3.eq_of_tgt _ _)

open scoped TensorProduct

noncomputable section

/-- The canonical integer-linear map from a cyclic module to the cyclic module of the gcd. -/
def zModToGcdLinearMap (a b : ℕ) : ZMod b →ₗ[ℤ] ZMod (Nat.gcd a b) :=
  (ZMod.castHom (Nat.gcd_dvd_right a b) (ZMod (Nat.gcd a b))).toAddMonoidHom.toIntLinearMap

/-- The canonical map to the gcd cyclic module agrees with the corresponding cast map. -/
@[simp] lemma zModToGcdLinearMap_apply (a b : ℕ) (x : ZMod b) :
    zModToGcdLinearMap a b x = ZMod.castHom (Nat.gcd_dvd_right a b) (ZMod (Nat.gcd a b)) x := rfl

/-- The kernel of the canonical map to the gcd cyclic module is the submodule generated by the first modulus. -/
lemma ker_zModToGcdLinearMap (a b : ℕ) [NeZero b] :
    Ideal.span {(a : ℤ)} • (⊤ : Submodule ℤ (ZMod b)) = LinearMap.ker (zModToGcdLinearMap a b) := by
  set g := Nat.gcd a b with hg
  apply le_antisymm
  · rw [Submodule.smul_le]
    intro r hr n _
    rw [Ideal.mem_span_singleton] at hr
    obtain ⟨c, rfl⟩ := hr
    rw [LinearMap.mem_ker, map_smul]

    have hga : (a : ZMod g) = 0 := (ZMod.natCast_eq_zero_iff a g).mpr (Nat.gcd_dvd_left a b)
    rw [zsmul_eq_mul]
    push_cast
    rw [hga]
    ring
  · intro x hx
    rw [LinearMap.mem_ker, zModToGcdLinearMap_apply, ZMod.castHom_apply, ← ZMod.natCast_val x,
      ZMod.natCast_eq_zero_iff] at hx

    obtain ⟨t, ht⟩ := hx
    rw [Submodule.ideal_span_singleton_smul, Submodule.mem_smul_pointwise_iff_exists]

    obtain ⟨u, v, huv⟩ : ∃ u v : ℤ, (g : ℤ) = a * u + b * v :=
      ⟨Nat.gcdA a b, Nat.gcdB a b, by rw [hg]; exact_mod_cast Nat.gcd_eq_gcd_ab a b⟩
    refine ⟨(u : ZMod b) * (t : ZMod b), Submodule.mem_top, ?_⟩

    rw [zsmul_eq_mul]
    have hx' : x = (x.val : ZMod b) := (ZMod.natCast_zmod_val x).symm
    rw [hx', ht]
    have hbz : (b : ZMod b) = 0 := ZMod.natCast_self b
    have : (g : ZMod b) = (a : ZMod b) * (u : ZMod b) := by
      have := congrArg (fun z : ℤ => (z : ZMod b)) huv
      push_cast at this ⊢
      rw [this, hbz]; ring
    push_cast
    rw [this]
    ring

/-- A quotient of a cyclic module by the indicated generated submodule is linearly equivalent to the gcd cyclic module. -/
def quotientZModLinearEquivGcd (a b : ℕ) [NeZero b] :
    (ZMod b ⧸ (Ideal.span {(a : ℤ)} • (⊤ : Submodule ℤ (ZMod b)))) ≃ₗ[ℤ] ZMod (Nat.gcd a b) :=
  (Submodule.quotEquivOfEq _ _ (ker_zModToGcdLinearMap a b)).trans
    ((zModToGcdLinearMap a b).quotKerEquivOfSurjective (by
      intro y
      obtain ⟨x, rfl⟩ := ZMod.castHom_surjective (Nat.gcd_dvd_right a b) y
      exact ⟨x, rfl⟩))

/-- The integer-linear endomorphism of an additive group given by multiplication by a natural number. -/
def natScalarLinearMap (a : ℕ) (Y : Type*) [AddCommGroup Y] : Y →ₗ[ℤ] Y := (a : ℤ) • LinearMap.id

/-- Evaluating the natural scalar map gives the natural-number action. -/
@[simp] lemma natScalarLinearMap_apply (a : ℕ) {Y : Type*} [AddCommGroup Y] (x : Y) :
    natScalarLinearMap a Y x = (a : ℤ) • x := rfl

/-- The range of multiplication by a natural number is the submodule generated by that number. -/
lemma range_natScalarLinearMap (a : ℕ) (Y : Type*) [AddCommGroup Y] :
    LinearMap.range (natScalarLinearMap a Y) = Ideal.span {(a : ℤ)} • (⊤ : Submodule ℤ Y) := by
  rw [Submodule.ideal_span_singleton_smul]
  ext x
  simp only [LinearMap.mem_range, natScalarLinearMap_apply, Submodule.mem_smul_pointwise_iff_exists]
  exact ⟨fun ⟨y, hy⟩ => ⟨y, Submodule.mem_top, hy⟩, fun ⟨y, _, hy⟩ => ⟨y, hy⟩⟩

/-- The scalar-multiplication endomorphism of a cyclic integer module. -/
def zModNatScalarLinearMap (a b : ℕ) : ZMod b →ₗ[ℤ] ZMod b := natScalarLinearMap a (ZMod b)

/-- Evaluating the cyclic scalar map gives multiplication by the selected natural number. -/
@[simp] lemma zModNatScalarLinearMap_apply (a b : ℕ) (x : ZMod b) : zModNatScalarLinearMap a b x = (a : ℤ) • x := rfl

/-- The integer-linear map from the gcd cyclic module into the second cyclic module. -/
def zModGcdToZModLinearMap (a b : ℕ) [NeZero b] : ZMod (Nat.gcd a b) →ₗ[ℤ] ZMod b :=
  (ZMod.lift (Nat.gcd a b)
    ⟨zmultiplesHom (ZMod b) ((b / Nat.gcd a b : ℕ) : ZMod b), by
      simp only [zmultiplesHom_apply, zsmul_eq_mul]
      rw [Int.cast_natCast, ← Nat.cast_mul, Nat.mul_div_cancel' (Nat.gcd_dvd_right a b),
        ZMod.natCast_self]⟩).toIntLinearMap

/-- The map from the gcd cyclic module sends an integer class to the corresponding scaled integer. -/
lemma zModGcdToZModLinearMap_intCast (a b : ℕ) [NeZero b] (m : ℤ) :
    zModGcdToZModLinearMap a b (m : ZMod (Nat.gcd a b)) = m • ((b / Nat.gcd a b : ℕ) : ZMod b) := by
  simp only [zModGcdToZModLinearMap, AddMonoidHom.coe_toIntLinearMap, ZMod.lift_coe, zmultiplesHom_apply]

/-- The map from the gcd cyclic module sends a natural representative to the prescribed multiple. -/
lemma zModGcdToZModLinearMap_apply (a b : ℕ) [NeZero b] (y : ZMod (Nat.gcd a b)) :
    zModGcdToZModLinearMap a b y = (y.val : ℤ) • ((b / Nat.gcd a b : ℕ) : ZMod b) := by
  haveI : NeZero (Nat.gcd a b) := ⟨Nat.gcd_ne_zero_right (NeZero.ne b)⟩
  conv_lhs => rw [← ZMod.natCast_zmod_val y]
  rw [show ((y.val : ℕ) : ZMod (Nat.gcd a b)) = (((y.val : ℕ) : ℤ) : ZMod (Nat.gcd a b)) by
      push_cast; rfl, zModGcdToZModLinearMap_intCast]

/-- The kernel of cyclic scalar multiplication is linearly equivalent to the cyclic module of the gcd. -/
def kerZModNatScalarLinearEquivGcd (a b : ℕ) [NeZero b] :
    (LinearMap.ker (zModNatScalarLinearMap a b)) ≃ₗ[ℤ] ZMod (Nat.gcd a b) := by
  haveI : NeZero (Nat.gcd a b) := ⟨Nat.gcd_ne_zero_right (NeZero.ne b)⟩
  set g := Nat.gcd a b with hg
  have hgpos : 0 < g := Nat.pos_of_ne_zero (Nat.gcd_ne_zero_right (NeZero.ne b))
  have hb'pos : 0 < b / g :=
    Nat.div_pos (Nat.le_of_dvd (Nat.pos_of_ne_zero (NeZero.ne b)) (Nat.gcd_dvd_right a b)) hgpos
  have hinj : Function.Injective (zModGcdToZModLinearMap a b) := by
    rw [← LinearMap.ker_eq_bot, Submodule.eq_bot_iff]
    intro x hx
    rw [LinearMap.mem_ker, zModGcdToZModLinearMap_apply, zsmul_eq_mul, Int.cast_natCast, ← Nat.cast_mul,
      ZMod.natCast_eq_zero_iff] at hx

    rw [← ZMod.natCast_zmod_val x, ZMod.natCast_eq_zero_iff]
    refine (Nat.mul_dvd_mul_iff_right hb'pos).mp ?_
    rwa [Nat.mul_div_cancel' (Nat.gcd_dvd_right a b)]
  have hz : (a : ℤ) • ((b / g : ℕ) : ZMod b) = 0 := by
    rw [zsmul_eq_mul, Int.cast_natCast, ← Nat.cast_mul, ZMod.natCast_eq_zero_iff]
    conv_lhs => rw [← Nat.mul_div_cancel' (Nat.gcd_dvd_right a b)]
    exact mul_dvd_mul_right (Nat.gcd_dvd_left a b) _
  have hrange : LinearMap.range (zModGcdToZModLinearMap a b) = LinearMap.ker (zModNatScalarLinearMap a b) := by
    apply le_antisymm
    · rintro _ ⟨y, rfl⟩
      rw [LinearMap.mem_ker, zModNatScalarLinearMap_apply, zModGcdToZModLinearMap_apply,
        smul_smul, mul_comm, ← smul_smul, hz, smul_zero]
    · intro x hx
      rw [LinearMap.mem_ker, zModNatScalarLinearMap_apply] at hx
      have h1 : b ∣ a * x.val := by
        rwa [← ZMod.natCast_zmod_val x, zsmul_eq_mul, Int.cast_natCast, ← Nat.cast_mul,
          ZMod.natCast_eq_zero_iff] at hx
      have haga' : a = g * (a / g) := (Nat.mul_div_cancel' (Nat.gcd_dvd_left a b)).symm
      have hcop : Nat.Coprime (b / g) (a / g) := (Nat.coprime_div_gcd_div_gcd hgpos).symm
      have hb'dvd : (b / g) ∣ x.val := by
        have hstep : (b / g) ∣ (a / g) * x.val := by
          apply Nat.dvd_of_mul_dvd_mul_left hgpos
          calc g * (b / g) = b := Nat.mul_div_cancel' (Nat.gcd_dvd_right a b)
            _ ∣ a * x.val := h1
            _ = g * ((a / g) * x.val) := by rw [← mul_assoc, ← haga']
        exact hcop.dvd_of_dvd_mul_left hstep
      obtain ⟨s, hs⟩ := hb'dvd
      refine ⟨((s : ℤ) : ZMod g), ?_⟩
      rw [zModGcdToZModLinearMap_intCast, zsmul_eq_mul, Int.cast_natCast, ← ZMod.natCast_zmod_val x, hs,
        Nat.cast_mul]
      ring
  exact ((LinearEquiv.ofInjective (zModGcdToZModLinearMap a b) hinj).trans
    (LinearEquiv.ofEq _ _ hrange)).symm

/-- The tensor product of two cyclic integer modules is linearly equivalent to the cyclic module of their gcd. -/
def tensorZModLinearEquivGcd (a b : ℕ) [NeZero b] :
    TensorProduct ℤ (ZMod a) (ZMod b) ≃ₗ[ℤ] ZMod (Nat.gcd a b) :=
  let e_a : ZMod a ≃ₗ[ℤ] (ℤ ⧸ Ideal.span {(a : ℤ)}) :=
    ((Int.quotientSpanNatEquivZMod a).symm.toAddEquiv).toIntLinearEquiv
  (TensorProduct.congr e_a (LinearEquiv.refl ℤ (ZMod b))) ≪≫ₗ
    (TensorProduct.quotTensorEquivQuotSMul (ZMod b) (Ideal.span {(a : ℤ)})) ≪≫ₗ
    quotientZModLinearEquivGcd a b

/-- Maps out of a cyclic module with nonzero modulus are additively equivalent to the kernel of multiplication by its modulus. -/
def linearMapZModKerAddEquiv (a : ℕ) (Y : Type*) [AddCommGroup Y] [NeZero a] :
    (ZMod a →ₗ[ℤ] Y) ≃+ LinearMap.ker (natScalarLinearMap a Y) where
  toFun f := ⟨f 1, by
    rw [LinearMap.mem_ker, natScalarLinearMap_apply, ← map_smul]
    have h1 : (a : ℤ) • (1 : ZMod a) = 0 := by
      rw [zsmul_eq_mul, mul_one, Int.cast_natCast, ZMod.natCast_self]
    rw [h1, map_zero]⟩
  invFun x := (ZMod.lift a ⟨zmultiplesHom Y (x : Y), by
    have hx := LinearMap.mem_ker.mp x.2
    rw [natScalarLinearMap_apply] at hx
    simpa only [zmultiplesHom_apply] using hx⟩).toIntLinearMap
  left_inv f := by
    ext z
    obtain ⟨n, rfl⟩ : ∃ n : ℤ, (n : ZMod a) = z :=
      ⟨(z.val : ℤ), by rw [Int.cast_natCast, ZMod.natCast_zmod_val]⟩
    rw [AddMonoidHom.coe_toIntLinearMap, ZMod.lift_coe]
    simp only [zmultiplesHom_apply]
    rw [← zsmul_one n, map_zsmul]
  right_inv x := by
    apply Subtype.ext
    change (ZMod.lift a ⟨zmultiplesHom Y (x : Y), _⟩).toIntLinearMap 1 = (x : Y)
    rw [AddMonoidHom.coe_toIntLinearMap,
      show (1 : ZMod a) = ((1 : ℤ) : ZMod a) by push_cast; rfl, ZMod.lift_coe]
    simp only [zmultiplesHom_apply, one_zsmul]
  map_add' f g := rfl

/-- Integer-linear maps between cyclic modules with nonzero moduli are additively equivalent to the cyclic module of their gcd. -/
def linearMapZModAddEquivGcd (a b : ℕ) [NeZero a] [NeZero b] :
    (ZMod a →ₗ[ℤ] ZMod b) ≃+ ZMod (Nat.gcd a b) :=
  (linearMapZModKerAddEquiv a (ZMod b)).trans (kerZModNatScalarLinearEquivGcd a b).toAddEquiv

/-- The kernel of nonzero natural-number multiplication on the integers is subsingleton. -/
lemma subsingleton_ker_natScalarLinearMapInt (a : ℕ) [NeZero a] :
    Subsingleton (LinearMap.ker (natScalarLinearMap a ℤ)) := by
  have hker : ∀ z : LinearMap.ker (natScalarLinearMap a ℤ), (z : ℤ) = 0 := by
    intro z
    have hz : (a : ℤ) • (z : ℤ) = 0 := LinearMap.mem_ker.mp z.2
    rw [smul_eq_mul, mul_eq_zero] at hz
    exact hz.resolve_left (Int.natCast_ne_zero.mpr (NeZero.ne a))
  exact ⟨fun x y => Subtype.ext (by rw [hker x, hker y])⟩

/-- Integer-linear maps from a cyclic module with nonzero modulus to the integers form a subsingleton. -/
lemma subsingleton_linearMapZModToInt (a : ℕ) [NeZero a] : Subsingleton (ZMod a →ₗ[ℤ] ℤ) := by
  haveI := subsingleton_ker_natScalarLinearMapInt a
  exact (linearMapZModKerAddEquiv a ℤ).toEquiv.subsingleton

end

/-- A cyclic integer module carries the displayed module structure over opposite integers. -/
noncomputable local instance zModOppositeIntModule (a : ℕ) : Module ℤᵐᵒᵖ (ZMod a) :=
  Module.compHom (ZMod a) ((RingHom.id ℤ).fromOpposite fun x y => mul_comm x y)

private lemma balancedSubgroup_zmod_eq_bot (a : ℕ) (N : Type) [AddCommGroup N] :
    RepresentationTheory.Algebra.Homology.TensorProductConstruction.integerTensorSubgroup ℤ N (ZMod a) = ⊥ := by
  rw [RepresentationTheory.Algebra.Homology.TensorProductConstruction.integerTensorSubgroup]
  apply le_antisymm _ bot_le
  rw [AddSubgroup.closure_le]
  rintro x ⟨r, m, n, rfl⟩
  simp only [SetLike.mem_coe, AddSubgroup.mem_bot]
  have hop : (MulOpposite.op r • m : ZMod a) = r • m := rfl
  rw [hop, sub_eq_zero]
  exact TensorProduct.smul_tmul r m n

/-- The degree-zero auxiliary categorical object from a cyclic module is isomorphic to the target modulo its generated scalar submodule. -/
theorem auxiliaryIntZModModuleDegreeZeroQuotientIso (a : ℕ) (N : Type) [AddCommGroup N] :
    Nonempty (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup ℤ N (ModuleCat.of ℤᵐᵒᵖ (ZMod a)) 0
      ≅ AddCommGrpCat.of (N ⧸ (Ideal.span {(a : ℤ)} • (⊤ : Submodule ℤ N)))) := by
  obtain ⟨e₀⟩ := RepresentationTheory.DerivedFunctorExactness.AuxiliaryDegreeZeroIso ℤ N (ModuleCat.of ℤᵐᵒᵖ (ZMod a))
  refine ⟨e₀ ≪≫ AddEquiv.toAddCommGrpIso ?_⟩
  let e_a : ZMod a ≃ₗ[ℤ] (ℤ ⧸ Ideal.span {(a : ℤ)}) :=
    ((Int.quotientSpanNatEquivZMod a).symm.toAddEquiv).toIntLinearEquiv
  exact ((QuotientAddGroup.quotientAddEquivOfEq (balancedSubgroup_zmod_eq_bot a N)).trans
    QuotientAddGroup.quotientBot).trans
    (((TensorProduct.congr e_a (LinearEquiv.refl ℤ N)).trans
      (TensorProduct.quotTensorEquivQuotSMul N (Ideal.span {(a : ℤ)}))).toAddEquiv)

/-- The degree-zero auxiliary categorical object of two cyclic modules is isomorphic to the gcd cyclic module. -/
theorem auxiliaryZModDegreeZeroGcdIso (a b : ℕ) (ha : a ≠ 0) (hb : b ≠ 0) :
    Nonempty (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup ℤ (ZMod b) (ModuleCat.of ℤᵐᵒᵖ (ZMod a)) 0
      ≅ AddCommGrpCat.of (ZMod (Nat.gcd a b))) := by
  haveI : NeZero a := ⟨ha⟩
  haveI : NeZero b := ⟨hb⟩

  obtain ⟨e₀⟩ := RepresentationTheory.DerivedFunctorExactness.AuxiliaryDegreeZeroIso ℤ (ZMod b) (ModuleCat.of ℤᵐᵒᵖ (ZMod a))
  refine ⟨e₀ ≪≫ AddEquiv.toAddCommGrpIso ?_⟩
  exact ((QuotientAddGroup.quotientAddEquivOfEq (balancedSubgroup_zmod_eq_bot a (ZMod b))).trans
    QuotientAddGroup.quotientBot).trans (tensorZModLinearEquivGcd a b).toAddEquiv

open scoped TensorProduct in

private lemma balancedSubgroup_int_eq_bot (N : Type) [AddCommGroup N] :
    RepresentationTheory.Algebra.Homology.TensorProductConstruction.integerTensorSubgroup ℤ N ℤ = ⊥ := by
  apply le_antisymm _ bot_le
  rw [RepresentationTheory.Algebra.Homology.TensorProductConstruction.integerTensorSubgroup, AddSubgroup.closure_le]
  rintro x ⟨c, m, n, rfl⟩
  simp only [SetLike.mem_coe, AddSubgroup.mem_bot]
  have hop : (MulOpposite.op c • m : ℤ) = c • m := by
    change m * MulOpposite.unop (MulOpposite.op c) = c • m
    rw [MulOpposite.unop_op, smul_eq_mul, mul_comm]
  rw [hop, sub_eq_zero, TensorProduct.smul_tmul]

open scoped TensorProduct in

private noncomputable def intTensorOverEquiv (N : Type) [AddCommGroup N] :
    RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction ℤ N ℤ ≃+ N :=
  (QuotientAddGroup.quotientAddEquivOfEq (balancedSubgroup_int_eq_bot N)).trans
    (QuotientAddGroup.quotientBot.trans (TensorProduct.lid ℤ N).toAddEquiv)

open scoped TensorProduct in
@[simp] private lemma intTensorOverEquiv_mk (N : Type) [AddCommGroup N]
    (m : ℤ) (n : N) :
    intTensorOverEquiv N (TensorProduct.tmul ℤ m n : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction ℤ N ℤ) = m • n := by
  simp only [intTensorOverEquiv, AddEquiv.trans_apply, LinearEquiv.coe_toAddEquiv]
  rfl

open scoped TensorProduct in

/-- The degree-one auxiliary categorical object of a cyclic module with nonzero modulus is isomorphic to a natural scalar-map kernel. -/
theorem auxiliaryIntZModDegreeOneKerIso (a : ℕ) (ha : a ≠ 0) (N : Type) [AddCommGroup N] :
    Nonempty (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup ℤ N (ModuleCat.of ℤᵐᵒᵖ (ZMod a)) 1
      ≅ AddCommGrpCat.of (LinearMap.ker (natScalarLinearMap a N))) := by
  haveI : NeZero a := ⟨ha⟩
  have ha' : (a : ℤ) ≠ 0 := by exact_mod_cast ha

  let f : ℤ →ₗ[ℤᵐᵒᵖ] ℤ :=
    { toFun := fun x => (a : ℤ) * x
      map_add' := fun x y => by ring
      map_smul' := fun r x => by
        simp only [RingHom.id_apply, MulOpposite.smul_eq_mul_unop]; ring }
  let g : ℤ →ₗ[ℤᵐᵒᵖ] ZMod a :=
    { toFun := fun x => (x : ZMod a)
      map_add' := fun x y => by push_cast; ring
      map_smul' := fun r x => by
        have hsmul : (r • (x : ZMod a)) = MulOpposite.unop r • (x : ZMod a) := rfl
        simp only [RingHom.id_apply, MulOpposite.smul_eq_mul_unop, hsmul, zsmul_eq_mul]
        push_cast; ring }
  have hgf : ∀ x : ℤ, g (f x) = 0 := by
    intro x
    change (((a : ℤ) * x : ℤ) : ZMod a) = 0
    rw [ZMod.intCast_zmod_eq_zero_iff_dvd]; exact dvd_mul_right _ _
  have eq0 : g.comp f = 0 :=
    LinearMap.ext fun x => by rw [LinearMap.comp_apply, hgf x, LinearMap.zero_apply]
  have hexact : Function.Exact f g := by
    rw [LinearMap.exact_iff]; ext y
    simp only [LinearMap.mem_ker, LinearMap.mem_range]
    change (((y : ℤ) : ZMod a) = 0) ↔ _
    rw [ZMod.intCast_zmod_eq_zero_iff_dvd]
    constructor
    · rintro ⟨c, rfl⟩; exact ⟨c, rfl⟩
    · rintro ⟨c, rfl⟩; exact dvd_mul_right _ _
  have hinjf : Function.Injective f := fun x y hxy =>
    mul_left_cancel₀ ha' (by simpa only [f, LinearMap.coe_mk, AddHom.coe_mk] using hxy)
  have hsurjg : Function.Surjective g := by
    intro z; obtain ⟨y, rfl⟩ := ZMod.intCast_surjective z; exact ⟨y, rfl⟩
  set S := ModuleCat.shortComplexOfCompEqZero f g eq0 with hSdef
  have hS : S.ShortExact := ModuleCat.shortComplex_shortExact S hexact hinjf hsurjg
  set F := RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionFunctor ℤ N with hF

  obtain ⟨δ, hExact⟩ := RepresentationTheory.CategoryPair.AssociatedType.exists_connectingMorphism_exact F hS 0 1 rfl
  let φ : (F.leftDerived 0).obj S.X₁ ⟶ (F.leftDerived 0).obj S.X₂ := (F.leftDerived 0).map S.f

  have h1 : Limits.IsZero ((F.leftDerived 1).obj S.X₂) :=
    Functor.isZero_leftDerived_obj_projective_succ F 0 S.X₂
  have hmono : Mono δ := by
    have e123 := hExact.exact' 1 2 3
    rwa [ShortComplex.exact_iff_mono _ (h1.eq_zero_of_src _)] at e123
  have hinjδ : Function.Injective δ.hom := (AddCommGrpCat.mono_iff_injective δ).mp hmono

  have hrk : δ.hom.range = φ.hom.ker := (hExact.exact' 2 3 4).ab_range_eq_ker
  have hcompl : δ ≫ φ = 0 := hExact.toIsComplex.zero' 2 3 4

  let ζ := F.leftDerivedZeroIsoSelf
  let τ₁ : ((F.leftDerived 0).obj S.X₁) ≃+ N :=
    (ζ.app S.X₁).addCommGroupIsoToAddEquiv.trans (intTensorOverEquiv N)
  let τ₂ : ((F.leftDerived 0).obj S.X₂) ≃+ N :=
    (ζ.app S.X₂).addCommGroupIsoToAddEquiv.trans (intTensorOverEquiv N)

  have key : ∀ w : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction ℤ N S.X₁,
      intTensorOverEquiv N (RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionMap ℤ N S.f w)
        = natScalarLinearMap a N (intTensorOverEquiv N w) := by
    intro w
    induction w using QuotientAddGroup.induction_on with
    | _ y =>
      induction y using TensorProduct.induction_on with
      | zero => simp
      | tmul m n =>
        change intTensorOverEquiv N
            (RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionMap ℤ N S.f (TensorProduct.tmul ℤ m n : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction ℤ N S.X₁))
          = natScalarLinearMap a N
            (intTensorOverEquiv N (TensorProduct.tmul ℤ m n : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction ℤ N S.X₁))
        rw [show RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionMap ℤ N S.f
              (TensorProduct.tmul ℤ m n : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction ℤ N S.X₁)
            = (TensorProduct.tmul ℤ (S.f.hom m) n : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction ℤ N S.X₂) from rfl,
          intTensorOverEquiv_mk, intTensorOverEquiv_mk, natScalarLinearMap_apply, smul_smul]
        rfl
      | add p q hp hq =>
        rw [show ((p + q : TensorProduct ℤ S.X₁ N) : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction ℤ N S.X₁)
              = ((p : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction ℤ N S.X₁) + (q : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction ℤ N S.X₁))
            from map_add (QuotientAddGroup.mk' _) p q,
          map_add, map_add, map_add, map_add, hp, hq]
  have hconj : ∀ x, τ₂ (φ.hom x) = natScalarLinearMap a N (τ₁ x) := by
    intro x
    have hn := congrArg (fun (m : (F.leftDerived 0).obj S.X₁ ⟶ F.obj S.X₂) => m.hom x)
      (ζ.hom.naturality S.f)
    simp only [AddCommGrpCat.hom_comp, AddMonoidHom.comp_apply] at hn
    simp only [τ₁, τ₂, AddEquiv.trans_apply, Iso.addCommGroupIsoToAddEquiv_apply]
    calc intTensorOverEquiv N ((ζ.app S.X₂).hom (φ.hom x))
        = intTensorOverEquiv N
            (RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionMap ℤ N S.f ((ζ.app S.X₁).hom x)) :=
          congrArg (intTensorOverEquiv N) hn
      _ = natScalarLinearMap a N (intTensorOverEquiv N ((ζ.app S.X₁).hom x)) :=
          key _

  have mem : ∀ x, τ₁ (δ.hom x) ∈ LinearMap.ker (natScalarLinearMap a N) := by
    intro x
    rw [LinearMap.mem_ker, ← hconj (δ.hom x)]
    have : φ.hom (δ.hom x) = 0 := by
      have := congrArg
        (fun (m : (F.leftDerived 1).obj S.X₃ ⟶ (F.leftDerived 0).obj S.X₂) => m.hom x) hcompl
      simpa only [AddCommGrpCat.hom_comp, AddMonoidHom.comp_apply, AddCommGrpCat.hom_zero,
        AddMonoidHom.zero_apply] using this
    rw [this, map_zero]
  let κ : ((F.leftDerived 1).obj S.X₃) →+ LinearMap.ker (natScalarLinearMap a N) :=
    { toFun := fun x => ⟨τ₁ (δ.hom x), mem x⟩
      map_zero' := by apply Subtype.ext; simp
      map_add' := fun x y => by apply Subtype.ext; simp }
  have hκbij : Function.Bijective κ := by
    constructor
    · intro x y hxy
      apply hinjδ
      apply τ₁.injective
      exact congrArg Subtype.val hxy
    · rintro ⟨z, hz⟩
      have hwker : (τ₁.symm z) ∈ φ.hom.ker := by
        rw [AddMonoidHom.mem_ker]
        apply τ₂.injective
        rw [hconj, map_zero, τ₁.apply_symm_apply]
        exact (LinearMap.mem_ker.mp hz)
      rw [← hrk] at hwker
      obtain ⟨x, hx⟩ := hwker
      exact ⟨x, Subtype.ext (by rw [show ((κ x : _) : N) = τ₁ (δ.hom x) from rfl, hx,
        τ₁.apply_symm_apply])⟩
  exact ⟨(AddEquiv.ofBijective κ hκbij).toAddCommGrpIso⟩

/-- The degree-one auxiliary categorical object of two cyclic modules with nonzero moduli is isomorphic to the gcd cyclic module. -/
theorem auxiliaryZModDegreeOneGcdIso (a b : ℕ) (ha : a ≠ 0) (hb : b ≠ 0) :
    Nonempty (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup ℤ (ZMod b) (ModuleCat.of ℤᵐᵒᵖ (ZMod a)) 1
      ≅ AddCommGrpCat.of (ZMod (Nat.gcd a b))) := by
  haveI : NeZero b := ⟨hb⟩
  obtain ⟨e⟩ := auxiliaryIntZModDegreeOneKerIso a ha (ZMod b)
  exact ⟨e ≪≫ (kerZModNatScalarLinearEquivGcd a b).toAddEquiv.toAddCommGrpIso⟩

/-- The degree-one auxiliary categorical object associated with a cyclic module of nonzero modulus is zero. -/
theorem auxiliaryZModDegreeOneIsZero (a : ℕ) (ha : a ≠ 0) :
    Limits.IsZero (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup ℤ ℤ (ModuleCat.of ℤᵐᵒᵖ (ZMod a)) 1) := by
  haveI : NeZero a := ⟨ha⟩
  haveI := subsingleton_ker_natScalarLinearMapInt a
  obtain ⟨e⟩ := auxiliaryIntZModDegreeOneKerIso a ha ℤ
  exact (AddCommGrpCat.isZero_of_subsingleton _).of_iso e

private noncomputable def zmodMopResolution (a : ℕ) (ha : a ≠ 0) :
    {S : ShortComplex (ModuleCat.{0} ℤᵐᵒᵖ) //
      S.ShortExact ∧ S.X₁ = ModuleCat.of ℤᵐᵒᵖ ℤ ∧ S.X₂ = ModuleCat.of ℤᵐᵒᵖ ℤ ∧
      S.X₃ = ModuleCat.of ℤᵐᵒᵖ (ZMod a)} :=
  have ha' : (a : ℤ) ≠ 0 := by exact_mod_cast ha
  let f : ℤ →ₗ[ℤᵐᵒᵖ] ℤ :=
    { toFun := fun x => (a : ℤ) * x
      map_add' := fun x y => by ring
      map_smul' := fun r x => by
        simp only [RingHom.id_apply, MulOpposite.smul_eq_mul_unop]; ring }
  let g : ℤ →ₗ[ℤᵐᵒᵖ] ZMod a :=
    { toFun := fun x => (x : ZMod a)
      map_add' := fun x y => by push_cast; ring
      map_smul' := fun r x => by
        have hsmul : (r • (x : ZMod a)) = MulOpposite.unop r • (x : ZMod a) := rfl
        simp only [RingHom.id_apply, MulOpposite.smul_eq_mul_unop, hsmul, zsmul_eq_mul]
        push_cast; ring }
  have hf : ∀ x : ℤ, f x = (a : ℤ) * x := fun _ => rfl
  have hg : ∀ x : ℤ, g x = ((x : ℤ) : ZMod a) := fun _ => rfl
  have hgf : ∀ x : ℤ, g (f x) = 0 := by
    intro x; rw [hf, hg, ZMod.intCast_zmod_eq_zero_iff_dvd]; exact dvd_mul_right _ _
  have eq0 : g.comp f = 0 :=
    LinearMap.ext fun x => by rw [LinearMap.comp_apply, hgf x, LinearMap.zero_apply]
  let S := ModuleCat.shortComplexOfCompEqZero f g eq0
  have hexact : Function.Exact f g := by
    rw [LinearMap.exact_iff]; ext y
    simp only [LinearMap.mem_ker, hg, ZMod.intCast_zmod_eq_zero_iff_dvd, LinearMap.mem_range, hf]
    constructor
    · rintro ⟨c, rfl⟩; exact ⟨c, rfl⟩
    · rintro ⟨c, rfl⟩; exact dvd_mul_right _ _
  have hinj : Function.Injective f := fun x y hxy => mul_left_cancel₀ ha' (by rw [← hf, ← hf, hxy])
  have hsurj : Function.Surjective g := by
    intro z; obtain ⟨y, rfl⟩ := ZMod.intCast_surjective z; exact ⟨y, hg y⟩
  ⟨S, ModuleCat.shortComplex_shortExact S hexact hinj hsurj, rfl, rfl, rfl⟩

private noncomputable def zmodZeroOpEquiv : ℤ ≃ₗ[ℤᵐᵒᵖ] (ZMod 0) :=
  { (AddEquiv.refl ℤ) with
    map_smul' := fun r x => by
      rw [MulOpposite.smul_eq_mul_unop]
      change x * MulOpposite.unop r = MulOpposite.unop r • x
      rw [smul_eq_mul, mul_comm] }

open Limits in

/-- The auxiliary categorical object from a cyclic integer module and an additive group vanishes from degree two onward. -/
theorem auxiliaryIntZModModuleDegreeSuccSuccIsZero (a : ℕ) (N : Type) [AddCommGroup N] (n : ℕ) :
    Limits.IsZero (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup ℤ N (ModuleCat.of ℤᵐᵒᵖ (ZMod a)) (n + 2)) := by
  rcases eq_or_ne a 0 with rfl | ha
  ·
    have hz := Functor.isZero_leftDerived_obj_projective_succ
      (RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionFunctor ℤ N) (n + 1) (ModuleCat.of ℤᵐᵒᵖ ℤ)
    exact hz.of_iso
      (((RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionFunctor ℤ N).leftDerived (n + 2)).mapIso
        zmodZeroOpEquiv.symm.toModuleIso)
  · obtain ⟨S, hS, hX₁, hX₂, hX₃⟩ := zmodMopResolution a ha
    set F := RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionFunctor ℤ N with hF
    obtain ⟨δ, hExact⟩ := RepresentationTheory.CategoryPair.AssociatedType.exists_connectingMorphism_exact F hS (n + 1) (n + 2) rfl
    have h1 : IsZero ((F.leftDerived (n + 2)).obj S.X₂) := by
      rw [hX₂]; exact Functor.isZero_leftDerived_obj_projective_succ F (n + 1) _
    have h3 : IsZero ((F.leftDerived (n + 1)).obj S.X₁) := by
      rw [hX₁]; exact Functor.isZero_leftDerived_obj_projective_succ F n _
    have hgoal : IsZero ((F.leftDerived (n + 2)).obj S.X₃) :=
      isZero_obj_two_of_sixTerm_exact hExact h1 h3
    rw [hX₃] at hgoal
    exact hgoal

/-- The auxiliary categorical object of two cyclic modules vanishes in degrees at least two. -/
theorem auxiliaryZModDegreeSuccSuccIsZero (a b : ℕ) (n : ℕ) :
    Limits.IsZero (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup ℤ (ZMod b) (ModuleCat.of ℤᵐᵒᵖ (ZMod a)) (n + 2)) :=
  auxiliaryIntZModModuleDegreeSuccSuccIsZero a (ZMod b) n

/-- The positive-degree auxiliary categorical object with an integer input is zero. -/
theorem auxiliaryIntModuleDegreeSuccIsZero (N : Type) [AddCommGroup N] [Module ℤ N] (n : ℕ) :
    Limits.IsZero (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup ℤ N (ModuleCat.of ℤᵐᵒᵖ ℤ) (n + 1)) :=
  Functor.isZero_leftDerived_obj_projective_succ (RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionFunctor ℤ N) n
    (ModuleCat.of ℤᵐᵒᵖ ℤ)

/-- In degree zero, the auxiliary integer construction on cyclic modules is additively equivalent to the gcd cyclic module. -/
theorem auxiliaryIntZModDegreeZeroGcdAddEquiv (a b : ℕ) (ha : a ≠ 0) (hb : b ≠ 0) :
    Nonempty (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses (ModuleCat.of ℤ (ZMod a)) (ModuleCat.of ℤ (ZMod b)) 0
      ≃+ ZMod (Nat.gcd a b)) := by
  haveI : NeZero a := ⟨ha⟩
  haveI : NeZero b := ⟨hb⟩

  obtain ⟨e₀⟩ := RepresentationTheory.DerivedFunctorExactness.AuxiliaryDegreeZeroAddEquiv ℤ (ModuleCat.of ℤ (ZMod a)) (ModuleCat.of ℤ (ZMod b))
  exact ⟨e₀.trans (ModuleCat.homAddEquiv.trans (linearMapZModAddEquivGcd a b))⟩

/-- The degree-one auxiliary construction from a cyclic module with nonzero modulus is additively equivalent to the target modulo its generated scalar submodule. -/
theorem auxiliaryIntZModDegreeOneQuotientAddEquiv (a : ℕ) (ha : a ≠ 0) (Y : Type) [AddCommGroup Y] :
    Nonempty (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses (ModuleCat.of ℤ (ZMod a)) (ModuleCat.of ℤ Y) 1
      ≃+ (Y ⧸ Ideal.span {(a : ℤ)} • (⊤ : Submodule ℤ Y))) := by
  haveI : NeZero a := ⟨ha⟩
  have ha' : (a : ℤ) ≠ 0 := by exact_mod_cast ha

  let f : ℤ →ₗ[ℤ] ℤ := (a : ℤ) • LinearMap.id
  let g : ℤ →ₗ[ℤ] ZMod a := Algebra.linearMap ℤ (ZMod a)
  have hf : ∀ x : ℤ, f x = (a : ℤ) * x := fun x => by simp [f]
  have hg : ∀ x : ℤ, g x = ((x : ℤ) : ZMod a) := fun x => by
    simp [g, Algebra.linearMap_apply, algebraMap_int_eq, eq_intCast]
  have hgf : ∀ x : ℤ, g (f x) = 0 := by
    intro x; rw [hf, hg, ZMod.intCast_zmod_eq_zero_iff_dvd]; exact dvd_mul_right _ _
  have eq0 : g.comp f = 0 :=
    LinearMap.ext fun x => by rw [LinearMap.comp_apply, hgf x, LinearMap.zero_apply]
  have hexact : Function.Exact f g := by
    rw [LinearMap.exact_iff]; ext y
    simp only [LinearMap.mem_ker, hg, ZMod.intCast_zmod_eq_zero_iff_dvd, LinearMap.mem_range, hf]
    constructor
    · rintro ⟨c, rfl⟩; exact ⟨c, rfl⟩
    · rintro ⟨c, rfl⟩; exact dvd_mul_right _ _
  have hinjf : Function.Injective f :=
    fun x y hxy => mul_left_cancel₀ ha' (by rw [← hf, ← hf, hxy])
  have hsurjg : Function.Surjective g := by
    intro z; obtain ⟨y, rfl⟩ := ZMod.intCast_surjective z; exact ⟨y, hg y⟩
  set S := ModuleCat.shortComplexOfCompEqZero f g eq0 with hSdef
  have hS : S.ShortExact := ModuleCat.shortComplex_shortExact S hexact hinjf hsurjg
  set Yc := ModuleCat.of ℤ Y with hY

  have hExactCS := Abelian.Ext.contravariantSequence_exact hS Yc 0 1 (by norm_num)

  let dhom : RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Yc 0 →+ RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₃ Yc 1 :=
    hS.extClass.precomp Yc (by norm_num)
  let m12 : RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₂ Yc 0 →+ RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Yc 0 :=
    (Abelian.Ext.mk₀ S.f).precomp Yc (zero_add 0)

  have hsurjδ : Function.Surjective dhom := by
    rw [← AddMonoidHom.range_eq_top,
      show dhom.range = _ from (hExactCS.exact' 2 3 4).ab_range_eq_ker]
    ext x
    simp only [AddSubgroup.mem_top, iff_true, AddMonoidHom.mem_ker]
    exact (Abelian.Ext.subsingleton_of_projective S.X₂ Yc 0).elim _ _
  have hkerδ : dhom.ker = m12.range := ((hExactCS.exact' 1 2 3).ab_range_eq_ker).symm

  let e0 : (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Yc 0) ≃+ Y :=
    (Abelian.Ext.addEquiv₀).trans (ModuleCat.homAddEquiv.trans
      (LinearMap.ringLmapEquivSelf ℤ ℤ Y).toAddEquiv)

  have hconj : ∀ β, e0 (m12 β) = natScalarLinearMap a Y (e0 β) := by
    intro β
    have hred : m12 β = (Abelian.Ext.mk₀ S.f).comp β (zero_add 0) := rfl
    have step1 : Abelian.Ext.addEquiv₀ (m12 β) = S.f ≫ Abelian.Ext.addEquiv₀ β := by
      rw [hred]
      apply Abelian.Ext.addEquiv₀.symm.injective
      rw [AddEquiv.symm_apply_apply, Abelian.Ext.addEquiv₀_symm_apply, ← Abelian.Ext.mk₀_comp_mk₀,
        Abelian.Ext.mk₀_addEquiv₀_apply]
    change (LinearMap.ringLmapEquivSelf ℤ ℤ Y)
        (ModuleCat.homAddEquiv (Abelian.Ext.addEquiv₀ (m12 β)))
      = natScalarLinearMap a Y ((LinearMap.ringLmapEquivSelf ℤ ℤ Y)
        (ModuleCat.homAddEquiv (Abelian.Ext.addEquiv₀ β)))
    rw [step1]
    simp only [ModuleCat.homAddEquiv_apply, ModuleCat.hom_comp,
      LinearMap.ringLmapEquivSelf_apply, natScalarLinearMap_apply]
    change (Abelian.Ext.addEquiv₀ β).hom (S.f.hom 1) = (a : ℤ) • (Abelian.Ext.addEquiv₀ β).hom 1
    rw [show S.f.hom (1 : ℤ) = (a : ℤ) • (1 : ℤ) from rfl, map_smul]

  let δL := dhom.toIntLinearMap
  have hsurjδL : Function.Surjective δL := hsurjδ
  let e0L : (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Yc 0) ≃ₗ[ℤ] Y := e0.toIntLinearEquiv
  have he0L : ∀ x, (e0L : (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Yc 0) →ₗ[ℤ] Y) x = e0 x := fun _ => rfl
  have hmap : Submodule.map (e0L : (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Yc 0) →ₗ[ℤ] Y) (LinearMap.ker δL)
      = Ideal.span {(a : ℤ)} • (⊤ : Submodule ℤ Y) := by
    rw [← range_natScalarLinearMap a Y]
    ext z
    simp only [Submodule.mem_map, LinearMap.mem_ker, LinearMap.mem_range, he0L]
    constructor
    · rintro ⟨y, hy, rfl⟩
      have hy' : y ∈ dhom.ker := AddMonoidHom.mem_ker.mpr hy
      rw [hkerδ] at hy'
      obtain ⟨u, hu⟩ := hy'
      exact ⟨e0 u, by rw [← hconj, hu]⟩
    · rintro ⟨w, rfl⟩
      refine ⟨m12 (e0.symm w), ?_, ?_⟩
      · have : m12 (e0.symm w) ∈ dhom.ker :=
          hkerδ.symm ▸ AddMonoidHom.mem_range.mpr ⟨e0.symm w, rfl⟩
        exact AddMonoidHom.mem_ker.mp this
      · rw [hconj, e0.apply_symm_apply]
  exact ⟨((LinearMap.quotKerEquivOfSurjective δL hsurjδL).symm.trans
    (Submodule.Quotient.equiv (LinearMap.ker δL) _ e0L hmap)).toAddEquiv⟩

/-- In degree one, the auxiliary integer construction on two cyclic modules is additively equivalent to their gcd cyclic module. -/
theorem auxiliaryIntZModDegreeOneGcdAddEquiv (a b : ℕ) (ha : a ≠ 0) (hb : b ≠ 0) :
    Nonempty (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses (ModuleCat.of ℤ (ZMod a)) (ModuleCat.of ℤ (ZMod b)) 1
      ≃+ ZMod (Nat.gcd a b)) := by
  haveI : NeZero b := ⟨hb⟩
  obtain ⟨e⟩ := auxiliaryIntZModDegreeOneQuotientAddEquiv a ha (ZMod b)
  exact ⟨e.trans (quotientZModLinearEquivGcd a b).toAddEquiv⟩

private lemma zmod_hasProjectiveDimensionLT_two (a : ℕ) :
    HasProjectiveDimensionLT (ModuleCat.of ℤ (ZMod a)) 2 := by
  rcases eq_or_ne a 0 with rfl | ha
  ·
    haveI : HasProjectiveDimensionLT (ModuleCat.of ℤ ℤ) 1 :=
      projective_iff_hasProjectiveDimensionLT_one.mp inferInstance
    exact hasProjectiveDimensionLT_of_ge (ModuleCat.of ℤ ℤ) 1 2 (by omega)
  ·
    have ha' : (a : ℤ) ≠ 0 := by exact_mod_cast ha
    let f : ℤ →ₗ[ℤ] ℤ := (a : ℤ) • LinearMap.id
    let g : ℤ →ₗ[ℤ] ZMod a := Algebra.linearMap ℤ (ZMod a)
    have hf : ∀ x : ℤ, f x = (a : ℤ) * x := fun x => by simp [f]
    have hg : ∀ x : ℤ, g x = ((x : ℤ) : ZMod a) := fun x => by
      simp [g, Algebra.linearMap_apply, algebraMap_int_eq, eq_intCast]
    have hgf : ∀ x : ℤ, g (f x) = 0 := by
      intro x
      rw [hf, hg, ZMod.intCast_zmod_eq_zero_iff_dvd]
      exact dvd_mul_right _ _
    have eq0 : g.comp f = 0 :=
      LinearMap.ext fun x => by rw [LinearMap.comp_apply, hgf x, LinearMap.zero_apply]
    let S := ModuleCat.shortComplexOfCompEqZero f g eq0
    have hexact : Function.Exact f g := by
      rw [LinearMap.exact_iff]
      ext y
      simp only [LinearMap.mem_ker, hg, ZMod.intCast_zmod_eq_zero_iff_dvd, LinearMap.mem_range, hf]
      constructor
      · rintro ⟨c, rfl⟩; exact ⟨c, rfl⟩
      · rintro ⟨c, rfl⟩; exact dvd_mul_right _ _
    have hinj : Function.Injective f := fun x y hxy =>
      mul_left_cancel₀ ha' (by rw [← hf, ← hf, hxy])
    have hsurj : Function.Surjective g := by
      intro z
      obtain ⟨y, rfl⟩ := ZMod.intCast_surjective z
      exact ⟨y, hg y⟩
    have hS : S.ShortExact := ModuleCat.shortComplex_shortExact S hexact hinj hsurj
    exact hasProjectiveDimensionLT_two_of_shortExact hS inferInstance inferInstance

/-- The auxiliary construction on two integer cyclic modules is subsingleton from degree two onward. -/
theorem auxiliaryIntZModDegreeSuccSuccSubsingleton (a b : ℕ) (n : ℕ) :
    Subsingleton (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses (ModuleCat.of ℤ (ZMod a)) (ModuleCat.of ℤ (ZMod b)) (n + 2)) := by
  haveI := zmod_hasProjectiveDimensionLT_two a
  exact HasProjectiveDimensionLT.subsingleton (ModuleCat.of ℤ (ZMod a)) 2 (n + 2) (by omega) _

/-- The positive-degree auxiliary construction for an integer module has at most one element. -/
theorem auxiliaryIntModuleDegreeSuccSubsingleton (N : ModuleCat.{0} ℤ) (n : ℕ) :
    Subsingleton (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses (ModuleCat.of ℤ ℤ) N (n + 1)) :=
  Abelian.Ext.subsingleton_of_projective (ModuleCat.of ℤ ℤ) N n

open Polynomial

open scoped TensorProduct

noncomputable section

variable {k : Type*} [Field k]

/-- The linear endomorphism of a module induced by scalar multiplication. -/
def moduleScalarLinearMap (f : k[X]) (N : Type*) [AddCommGroup N] [Module k[X] N] : N →ₗ[k[X]] N :=
  f • LinearMap.id

/-- Evaluating the scalar linear map gives the usual scalar action. -/
@[simp] lemma moduleScalarLinearMap_apply (f : k[X]) {N : Type*} [AddCommGroup N] [Module k[X] N] (x : N) :
    moduleScalarLinearMap f N x = f • x := rfl

/-- The linear endomorphism of a polynomial quotient given by multiplication by a polynomial. -/
def quotientScalarLinearMap (f g : k[X]) : (k[X] ⧸ Ideal.span {g}) →ₗ[k[X]] (k[X] ⧸ Ideal.span {g}) :=
  moduleScalarLinearMap f _

/-- Evaluating the quotient scalar map gives multiplication on the quotient. -/
@[simp] lemma quotientScalarLinearMap_apply (f g : k[X]) (x : k[X] ⧸ Ideal.span {g}) :
    quotientScalarLinearMap f g x = f • x := rfl

/-- A nonzero polynomial has trivial scalar-action kernel on the polynomial module. -/
lemma subsingleton_ker_moduleScalarLinearMap (f : k[X]) (hf : f ≠ 0) :
    Subsingleton (LinearMap.ker (moduleScalarLinearMap f k[X])) := by
  refine ⟨fun x y => Subtype.ext ?_⟩
  have h : ∀ z : LinearMap.ker (moduleScalarLinearMap f k[X]), (z : k[X]) = 0 := fun z => by
    have hz : f • (z : k[X]) = 0 := LinearMap.mem_ker.mp z.2
    rw [smul_eq_mul, mul_eq_zero] at hz
    exact hz.resolve_left hf
  rw [h x, h y]

/-- The canonical linear map from the quotient by `g` to the quotient by `f` and `g`. -/
def quotientByPairIdealLinearMap (f g : k[X]) :
    (k[X] ⧸ Ideal.span {g}) →ₗ[k[X]] (k[X] ⧸ Ideal.span {f, g}) :=
  Submodule.mapQ (Ideal.span {g}) (Ideal.span {f, g}) LinearMap.id (by
    rw [Submodule.comap_id]
    exact Ideal.span_mono (Set.subset_insert f {g}))

/-- The quotient map sends a polynomial representative to its corresponding class. -/
@[simp] lemma quotientByPairIdealLinearMap_mk (f g : k[X]) (x : k[X]) :
    quotientByPairIdealLinearMap f g (Submodule.Quotient.mk x) = Submodule.Quotient.mk x := rfl

/-- The canonical map between these polynomial quotients is onto. -/
lemma quotientByPairIdealLinearMap_surjective (f g : k[X]) : Function.Surjective (quotientByPairIdealLinearMap f g) := by
  intro y
  obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ y
  exact ⟨Submodule.Quotient.mk x, rfl⟩

/-- The kernel of the induced quotient map is the submodule generated by the scalar polynomial. -/
lemma ker_quotientScalarLinearMap (f g : k[X]) :
    Ideal.span {f} • (⊤ : Submodule k[X] (k[X] ⧸ Ideal.span {g}))
      = LinearMap.ker (quotientByPairIdealLinearMap f g) := by
  apply le_antisymm
  · rw [Submodule.smul_le]
    intro r hr n _
    rw [Ideal.mem_span_singleton] at hr
    obtain ⟨c, rfl⟩ := hr
    obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ n
    rw [LinearMap.mem_ker, ← Submodule.Quotient.mk_smul, quotientByPairIdealLinearMap_mk,
      Submodule.Quotient.mk_eq_zero]

    rw [smul_eq_mul]
    apply Ideal.mul_mem_right
    apply Ideal.mul_mem_right
    exact Ideal.subset_span (Set.mem_insert f {g})
  · intro n hn
    obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective _ n
    rw [LinearMap.mem_ker, quotientByPairIdealLinearMap_mk, Submodule.Quotient.mk_eq_zero,
      Ideal.mem_span_insert] at hn
    obtain ⟨a, z, hz, hx⟩ := hn
    rw [Ideal.mem_span_singleton] at hz
    obtain ⟨c, rfl⟩ := hz

    rw [hx]
    have : (Submodule.Quotient.mk (a * f + g * c) : k[X] ⧸ Ideal.span {g})
        = Submodule.Quotient.mk (a * f) := by
      rw [Submodule.Quotient.eq]
      have : a * f + g * c - a * f = g * c := by ring
      rw [this]
      exact Ideal.mul_mem_right _ _ (Ideal.subset_span rfl)
    rw [this]
    rw [Submodule.ideal_span_singleton_smul]
    refine ⟨Submodule.Quotient.mk a, Submodule.mem_top, ?_⟩
    change f • (Submodule.Quotient.mk a : k[X] ⧸ Ideal.span {g}) = Submodule.Quotient.mk (a * f)
    rw [← Submodule.Quotient.mk_smul, smul_eq_mul, mul_comm]

/-- Identifies the iterated quotient after imposing `f` with the quotient by both polynomials. -/
def iteratedQuotientLinearEquiv (f g : k[X]) :
    ((k[X] ⧸ Ideal.span {g}) ⧸
        (Ideal.span {f} • (⊤ : Submodule k[X] (k[X] ⧸ Ideal.span {g}))))
      ≃ₗ[k[X]] (k[X] ⧸ Ideal.span {f, g}) :=
  (Submodule.quotEquivOfEq _ _ (ker_quotientScalarLinearMap f g)).trans
    ((quotientByPairIdealLinearMap f g).quotKerEquivOfSurjective (quotientByPairIdealLinearMap_surjective f g))

/-- The tensor product of two principal polynomial quotients is equivalent to their joint quotient. -/
def tensorQuotientLinearEquiv (f g : k[X]) :
    TensorProduct k[X] (k[X] ⧸ Ideal.span {f}) (k[X] ⧸ Ideal.span {g})
      ≃ₗ[k[X]] (k[X] ⧸ Ideal.span {f, g}) :=
  (TensorProduct.quotTensorEquivQuotSMul (k[X] ⧸ Ideal.span {g}) (Ideal.span {f})) ≪≫ₗ
    iteratedQuotientLinearEquiv f g

/-- Under the nonvanishing hypothesis, the scalar-map kernel is equivalent to the joint quotient. -/
def quotientKerLinearEquiv (f g : k[X]) (hg : g ≠ 0) :
    (LinearMap.ker (quotientScalarLinearMap f g)) ≃ₗ[k[X]] (k[X] ⧸ Ideal.span {f, g}) := by

  set d := Submodule.IsPrincipal.generator (Ideal.span {f, g}) with hddef
  have hd : Ideal.span {f, g} = Ideal.span {d} := (Ideal.span_singleton_generator _).symm
  have hdg : d ∣ g := by
    rw [← Ideal.mem_span_singleton, ← hd]; exact Ideal.subset_span (by simp)
  have hdf : d ∣ f := by
    rw [← Ideal.mem_span_singleton, ← hd]; exact Ideal.subset_span (by simp)
  set g' := hdg.choose with hg'def
  have hg'eq : g = d * g' := hdg.choose_spec
  set f' := hdf.choose with hf'def
  have hf'eq : f = d * f' := hdf.choose_spec
  have hd0 : d ≠ 0 := fun h0 => hg (by rw [hg'eq, h0, zero_mul])
  have hg'0 : g' ≠ 0 := fun h0 => hg (by rw [hg'eq, h0, mul_zero])
  have hbez : d ∈ Ideal.span {f, g} := by rw [hd]; exact Ideal.mem_span_singleton_self d
  rw [Ideal.mem_span_pair] at hbez
  set u := hbez.choose with hudef
  have hv : ∃ v, u * f + v * g = d := hbez.choose_spec
  set v := hv.choose with hvdef
  have huv : u * f + v * g = d := hv.choose_spec
  have hcop : IsCoprime f' g' := by
    refine ⟨u, v, ?_⟩
    have : d * (u * f' + v * g') = d * 1 := by
      rw [mul_one, mul_add, ← mul_assoc, ← mul_assoc, mul_comm d u, mul_comm d v,
        mul_assoc u, mul_assoc v, ← hf'eq, ← hg'eq, huv]
    exact mul_left_cancel₀ hd0 this

  set φ : k[X] →ₗ[k[X]] (k[X] ⧸ Ideal.span {g}) :=
    (Ideal.span {g}).mkQ ∘ₗ (g' • LinearMap.id) with hφdef
  have hφ : ∀ r : k[X], φ r = Submodule.Quotient.mk (g' * r) := fun r => by
    simp only [hφdef, LinearMap.comp_apply, LinearMap.smul_apply, LinearMap.id_apply,
      Submodule.mkQ_apply, smul_eq_mul]
  have hφker : Ideal.span {f, g} ≤ LinearMap.ker φ := by
    rw [hd]
    intro x hx
    rw [Ideal.mem_span_singleton] at hx
    obtain ⟨t, rfl⟩ := hx
    rw [LinearMap.mem_ker, hφ, Submodule.Quotient.mk_eq_zero, Ideal.mem_span_singleton]
    exact ⟨t, by rw [hg'eq]; ring⟩
  set kerGen : (k[X] ⧸ Ideal.span {f, g}) →ₗ[k[X]] (k[X] ⧸ Ideal.span {g}) :=
    Submodule.liftQ _ φ hφker with hkerGendef
  have hkerGen : ∀ r : k[X],
      kerGen (Submodule.Quotient.mk r) = Submodule.Quotient.mk (g' * r) := fun r => by
    rw [hkerGendef, Submodule.liftQ_apply, hφ]

  have hinj : Function.Injective kerGen := by
    rw [← LinearMap.ker_eq_bot, Submodule.eq_bot_iff]
    intro x hx
    obtain ⟨r, rfl⟩ := Submodule.Quotient.mk_surjective _ x
    rw [LinearMap.mem_ker, hkerGen, Submodule.Quotient.mk_eq_zero,
      Ideal.mem_span_singleton] at hx
    rw [Submodule.Quotient.mk_eq_zero, hd, Ideal.mem_span_singleton]

    rw [hg'eq, mul_comm d g'] at hx
    exact (mul_dvd_mul_iff_left hg'0).mp hx

  have hrange : LinearMap.range kerGen = LinearMap.ker (quotientScalarLinearMap f g) := by
    apply le_antisymm
    · rintro _ ⟨x, rfl⟩
      obtain ⟨r, rfl⟩ := Submodule.Quotient.mk_surjective _ x
      rw [LinearMap.mem_ker, hkerGen]
      change f • (Submodule.Quotient.mk (g' * r) : k[X] ⧸ Ideal.span {g}) = 0
      rw [← Submodule.Quotient.mk_smul, smul_eq_mul, Submodule.Quotient.mk_eq_zero,
        Ideal.mem_span_singleton]
      exact ⟨f' * r, by rw [hf'eq, hg'eq]; ring⟩
    · intro x hx
      obtain ⟨r, rfl⟩ := Submodule.Quotient.mk_surjective _ x
      rw [LinearMap.mem_ker] at hx
      change f • (Submodule.Quotient.mk r : k[X] ⧸ Ideal.span {g}) = 0 at hx
      rw [← Submodule.Quotient.mk_smul, smul_eq_mul, Submodule.Quotient.mk_eq_zero,
        Ideal.mem_span_singleton] at hx

      obtain ⟨s, hs⟩ : g' ∣ r := by
        rw [hg'eq, hf'eq, mul_assoc] at hx
        exact hcop.symm.dvd_of_dvd_mul_left ((mul_dvd_mul_iff_left hd0).mp hx)
      exact ⟨Submodule.Quotient.mk s, by rw [hkerGen, ← hs]⟩
  exact ((LinearEquiv.ofInjective kerGen hinj).trans (LinearEquiv.ofEq _ _ hrange)).symm

/-- Identifies maps between the two quotients with the kernel of the induced scalar map. -/
def linearMapQuotientKerAddEquiv (f g : k[X]) :
    ((k[X] ⧸ Ideal.span {f}) →ₗ[k[X]] (k[X] ⧸ Ideal.span {g}))
      ≃+ LinearMap.ker (quotientScalarLinearMap f g) where
  toFun ψ := ⟨ψ (Submodule.Quotient.mk 1), by
    rw [LinearMap.mem_ker]
    change f • ψ (Submodule.Quotient.mk 1) = 0
    rw [← map_smul, ← Submodule.Quotient.mk_smul, smul_eq_mul, mul_one,
      (Submodule.Quotient.mk_eq_zero _).2 (Ideal.mem_span_singleton_self f), map_zero]⟩
  invFun x := (Ideal.span {f}).liftQ
    (LinearMap.toSpanSingleton k[X] (k[X] ⧸ Ideal.span {g}) (x : k[X] ⧸ Ideal.span {g})) (by
      intro r hr
      rw [Ideal.mem_span_singleton] at hr
      obtain ⟨s, rfl⟩ := hr
      rw [LinearMap.mem_ker, LinearMap.toSpanSingleton_apply, mul_comm, mul_smul]
      have hx := LinearMap.mem_ker.mp x.2
      change f • (x : k[X] ⧸ Ideal.span {g}) = 0 at hx
      rw [hx, smul_zero])
  left_inv ψ := by
    apply LinearMap.ext
    intro z
    obtain ⟨r, rfl⟩ := Submodule.Quotient.mk_surjective _ z
    rw [Submodule.liftQ_apply, LinearMap.toSpanSingleton_apply, ← map_smul,
      ← Submodule.Quotient.mk_smul, smul_eq_mul, mul_one]
  right_inv x := by
    apply Subtype.ext
    change (Ideal.span {f}).liftQ _ _ (Submodule.Quotient.mk 1) = (x : k[X] ⧸ Ideal.span {g})
    rw [Submodule.liftQ_apply, LinearMap.toSpanSingleton_apply, one_smul]
  map_add' _ _ := rfl

/-- Relates linear maps between principal polynomial quotients to the quotient by both generators. -/
def linearMapQuotientAddEquiv (f g : k[X]) (hg : g ≠ 0) :
    ((k[X] ⧸ Ideal.span {f}) →ₗ[k[X]] (k[X] ⧸ Ideal.span {g}))
      ≃+ (k[X] ⧸ Ideal.span {f, g}) :=
  (linearMapQuotientKerAddEquiv f g).trans (quotientKerLinearEquiv f g hg).toAddEquiv

end

/-- The quotient by a polynomial ideal carries the displayed module structure over the opposite polynomial ring. -/
noncomputable local instance quotientOppositePolynomialModule (k : Type*) [Field k] (f : k[X]) :
    Module (k[X])ᵐᵒᵖ (k[X] ⧸ Ideal.span {f}) :=
  Module.compHom _ ((RingHom.id k[X]).fromOpposite fun x y => mul_comm x y)

/-- The degree-zero auxiliary categorical object of two polynomial quotients is isomorphic to their joint quotient. -/
theorem auxiliaryPolynomialQuotientDegreeZeroIso (k : Type*) [Field k] (f g : k[X]) :
    Nonempty (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup k[X] (k[X] ⧸ Ideal.span {g})
        (ModuleCat.of (k[X])ᵐᵒᵖ (k[X] ⧸ Ideal.span {f})) 0
      ≅ AddCommGrpCat.of (k[X] ⧸ Ideal.span {f, g})) := by

  obtain ⟨e₀⟩ := RepresentationTheory.DerivedFunctorExactness.AuxiliaryDegreeZeroIso k[X] (k[X] ⧸ Ideal.span {g})
    (ModuleCat.of (k[X])ᵐᵒᵖ (k[X] ⧸ Ideal.span {f}))
  refine ⟨e₀ ≪≫ AddEquiv.toAddCommGrpIso
    ((RepresentationTheory.Algebra.Module.BalancedTensorProduct.Adjunction.balancedTensorProductEquivTensorProduct (N := k[X] ⧸ Ideal.span {g}) ?_).trans
      (tensorQuotientLinearEquiv f g).toAddEquiv)⟩
  intro a m

  change (MulOpposite.op a).unop • m = a • m
  rw [MulOpposite.unop_op]

open scoped TensorProduct in

private noncomputable def polyTensorOverEquiv {k : Type u} [Field k] (N : Type u) [AddCommGroup N]
    [Module k[X] N] : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction k[X] N k[X] ≃+ N :=
  (RepresentationTheory.Algebra.Module.BalancedTensorProduct.Adjunction.balancedTensorProductEquivTensorProduct (A := k[X]) (N := N) (M := k[X])
      (fun a x => op_smul_eq_smul a x)).trans (TensorProduct.lid k[X] N).toAddEquiv

open scoped TensorProduct in
@[simp] private lemma polyTensorOverEquiv_mk {k : Type u} [Field k] (N : Type u) [AddCommGroup N]
    [Module k[X] N] (m : k[X]) (n : N) :
    polyTensorOverEquiv N (TensorProduct.tmul ℤ m n : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction k[X] N k[X]) = m • n := by
  simp only [polyTensorOverEquiv, AddEquiv.trans_apply,
    RepresentationTheory.Algebra.Module.BalancedTensorProduct.Adjunction.balancedTensorProductEquivTensorProduct_tmul,
    LinearEquiv.coe_toAddEquiv]
  exact TensorProduct.lid_tmul n m

/-- The degree-one auxiliary categorical object of a quotient by a nonzero polynomial is isomorphic to a scalar-map kernel. -/
theorem auxiliaryPolynomialQuotientDegreeOneKerIso {k : Type u} [Field k] (f : k[X]) (hf : f ≠ 0)
    (N : Type u) [AddCommGroup N] [Module k[X] N] :
    Nonempty (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup k[X] N (ModuleCat.of (k[X])ᵐᵒᵖ (k[X] ⧸ Ideal.span {f})) 1
      ≅ AddCommGrpCat.of (LinearMap.ker (moduleScalarLinearMap f N))) := by

  let mfL : k[X] →ₗ[(k[X])ᵐᵒᵖ] k[X] :=
    { toFun := fun x => f * x
      map_add' := fun x y => by ring
      map_smul' := fun r x => by
        simp only [RingHom.id_apply, MulOpposite.smul_eq_mul_unop]; ring }
  let pfL : k[X] →ₗ[(k[X])ᵐᵒᵖ] (k[X] ⧸ Ideal.span {f}) :=
    { toFun := fun x => (Ideal.span {f}).mkQ x
      map_add' := fun x y => map_add _ x y
      map_smul' := fun r x => by
        rw [MulOpposite.smul_eq_mul_unop, RingHom.id_apply]
        change (Ideal.span {f}).mkQ (x * MulOpposite.unop r)
            = MulOpposite.unop r • (Ideal.span {f}).mkQ x
        rw [← map_smul]; congr 1; rw [smul_eq_mul, mul_comm] }
  have hgfe : ∀ x : k[X], pfL (mfL x) = 0 := by
    intro x
    change (Ideal.span {f}).mkQ (f * x) = 0
    rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero, Ideal.mem_span_singleton]
    exact dvd_mul_right f x
  have eq0 : pfL.comp mfL = 0 :=
    LinearMap.ext fun x => by rw [LinearMap.comp_apply, hgfe x, LinearMap.zero_apply]
  have hexact : Function.Exact mfL pfL := by
    rw [LinearMap.exact_iff]; ext y
    simp only [LinearMap.mem_ker, LinearMap.mem_range]
    change ((Ideal.span {f}).mkQ y = 0) ↔ _
    rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero, Ideal.mem_span_singleton]
    constructor
    · rintro ⟨c, rfl⟩; exact ⟨c, rfl⟩
    · rintro ⟨c, rfl⟩; exact dvd_mul_right f c
  have hinjf : Function.Injective mfL := fun x y hxy =>
    mul_left_cancel₀ hf (by simpa only [mfL, LinearMap.coe_mk, AddHom.coe_mk] using hxy)
  have hsurjg : Function.Surjective pfL := (Ideal.span {f}).mkQ_surjective
  set S := ModuleCat.shortComplexOfCompEqZero mfL pfL eq0 with hSdef
  have hS : S.ShortExact := ModuleCat.shortComplex_shortExact S hexact hinjf hsurjg
  set F := RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionFunctor k[X] N with hF

  obtain ⟨δ, hExact⟩ := RepresentationTheory.CategoryPair.AssociatedType.exists_connectingMorphism_exact F hS 0 1 rfl
  let φ : (F.leftDerived 0).obj S.X₁ ⟶ (F.leftDerived 0).obj S.X₂ := (F.leftDerived 0).map S.f

  have h1 : Limits.IsZero ((F.leftDerived 1).obj S.X₂) :=
    Functor.isZero_leftDerived_obj_projective_succ F 0 S.X₂
  have hmono : Mono δ := by
    have e123 := hExact.exact' 1 2 3
    rwa [ShortComplex.exact_iff_mono _ (h1.eq_zero_of_src _)] at e123
  have hinjδ : Function.Injective δ.hom := (AddCommGrpCat.mono_iff_injective δ).mp hmono

  have hrk : δ.hom.range = φ.hom.ker := (hExact.exact' 2 3 4).ab_range_eq_ker
  have hcompl : δ ≫ φ = 0 := hExact.toIsComplex.zero' 2 3 4

  let ζ := F.leftDerivedZeroIsoSelf
  let τ₁ : ((F.leftDerived 0).obj S.X₁) ≃+ N :=
    (ζ.app S.X₁).addCommGroupIsoToAddEquiv.trans (polyTensorOverEquiv N)
  let τ₂ : ((F.leftDerived 0).obj S.X₂) ≃+ N :=
    (ζ.app S.X₂).addCommGroupIsoToAddEquiv.trans (polyTensorOverEquiv N)

  have key : ∀ w : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction k[X] N S.X₁,
      polyTensorOverEquiv N (RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionMap k[X] N S.f w)
        = moduleScalarLinearMap f N (polyTensorOverEquiv N w) := by
    intro w
    induction w using QuotientAddGroup.induction_on with
    | _ y =>
      induction y using TensorProduct.induction_on with
      | zero => simp
      | tmul m n =>
        rw [show RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionMap k[X] N S.f
              (TensorProduct.tmul ℤ m n : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction k[X] N S.X₁)
            = (TensorProduct.tmul ℤ (S.f.hom m) n : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction k[X] N S.X₂) from rfl,
          polyTensorOverEquiv_mk, polyTensorOverEquiv_mk, moduleScalarLinearMap_apply]
        change (f * m) • n = f • (m • n)
        rw [mul_smul]
      | add p q hp hq =>
        rw [show ((p + q : TensorProduct ℤ S.X₁ N) : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction k[X] N S.X₁)
              = ((p : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction k[X] N S.X₁) + (q : RepresentationTheory.Algebra.Homology.TensorProductConstruction.ModuleConstruction k[X] N S.X₁))
            from map_add (QuotientAddGroup.mk' _) p q,
          map_add, map_add, map_add, map_add, hp, hq]
  have hconj : ∀ x, τ₂ (φ.hom x) = moduleScalarLinearMap f N (τ₁ x) := by
    intro x
    have hn := congrArg (fun (m : (F.leftDerived 0).obj S.X₁ ⟶ F.obj S.X₂) => m.hom x)
      (ζ.hom.naturality S.f)
    simp only [AddCommGrpCat.hom_comp, AddMonoidHom.comp_apply] at hn
    simp only [τ₁, τ₂, AddEquiv.trans_apply, Iso.addCommGroupIsoToAddEquiv_apply]
    calc polyTensorOverEquiv N ((ζ.app S.X₂).hom (φ.hom x))
        = polyTensorOverEquiv N
            (RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionMap k[X] N S.f ((ζ.app S.X₁).hom x)) :=
          congrArg (polyTensorOverEquiv N) hn
      _ = moduleScalarLinearMap f N (polyTensorOverEquiv N ((ζ.app S.X₁).hom x)) := key _

  have mem : ∀ x, τ₁ (δ.hom x) ∈ LinearMap.ker (moduleScalarLinearMap f N) := by
    intro x
    rw [LinearMap.mem_ker, ← hconj (δ.hom x)]
    have : φ.hom (δ.hom x) = 0 := by
      have := congrArg
        (fun (m : (F.leftDerived 1).obj S.X₃ ⟶ (F.leftDerived 0).obj S.X₂) => m.hom x) hcompl
      simpa only [AddCommGrpCat.hom_comp, AddMonoidHom.comp_apply, AddCommGrpCat.hom_zero,
        AddMonoidHom.zero_apply] using this
    rw [this, map_zero]
  let κ : ((F.leftDerived 1).obj S.X₃) →+ LinearMap.ker (moduleScalarLinearMap f N) :=
    { toFun := fun x => ⟨τ₁ (δ.hom x), mem x⟩
      map_zero' := by apply Subtype.ext; simp
      map_add' := fun x y => by apply Subtype.ext; simp }
  have hκbij : Function.Bijective κ := by
    constructor
    · intro x y hxy
      apply hinjδ
      apply τ₁.injective
      exact congrArg Subtype.val hxy
    · rintro ⟨z, hz⟩
      have hwker : (τ₁.symm z) ∈ φ.hom.ker := by
        rw [AddMonoidHom.mem_ker]
        apply τ₂.injective
        rw [hconj, map_zero, τ₁.apply_symm_apply]
        exact (LinearMap.mem_ker.mp hz)
      rw [← hrk] at hwker
      obtain ⟨x, hx⟩ := hwker
      refine ⟨x, Subtype.ext ?_⟩
      rw [show ((κ x : _) : N) = τ₁ (δ.hom x) from rfl, hx, τ₁.apply_symm_apply]
  exact ⟨(AddEquiv.ofBijective κ hκbij).toAddCommGrpIso⟩

/-- The degree-one auxiliary categorical object of two quotients by nonzero polynomials is isomorphic to their joint quotient. -/
theorem auxiliaryPolynomialQuotientDegreeOneIso {k : Type u} [Field k] (f g : k[X]) (hf : f ≠ 0) (hg : g ≠ 0) :
    Nonempty (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup k[X] (k[X] ⧸ Ideal.span {g})
        (ModuleCat.of (k[X])ᵐᵒᵖ (k[X] ⧸ Ideal.span {f})) 1
      ≅ AddCommGrpCat.of (k[X] ⧸ Ideal.span {f, g})) := by
  obtain ⟨e⟩ := auxiliaryPolynomialQuotientDegreeOneKerIso f hf (k[X] ⧸ Ideal.span {g})
  exact ⟨e ≪≫ (quotientKerLinearEquiv f g hg).toAddEquiv.toAddCommGrpIso⟩

/-- The degree-one auxiliary categorical object of a quotient by a nonzero polynomial is zero. -/
theorem auxiliaryPolynomialQuotientDegreeOneIsZero {k : Type u} [Field k] (f : k[X]) (hf : f ≠ 0) :
    Limits.IsZero (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup k[X] k[X] (ModuleCat.of (k[X])ᵐᵒᵖ (k[X] ⧸ Ideal.span {f})) 1) := by
  haveI := subsingleton_ker_moduleScalarLinearMap f hf
  obtain ⟨e⟩ := auxiliaryPolynomialQuotientDegreeOneKerIso f hf k[X]
  exact (AddCommGrpCat.isZero_of_subsingleton _).of_iso e

private noncomputable def polyMopResolution (k : Type u) [Field k] (p : k[X]) (hp : p ≠ 0) :
    {S : ShortComplex (ModuleCat.{u} (k[X])ᵐᵒᵖ) //
      S.ShortExact ∧ S.X₁ = ModuleCat.of (k[X])ᵐᵒᵖ k[X] ∧ S.X₂ = ModuleCat.of (k[X])ᵐᵒᵖ k[X] ∧
      S.X₃ = ModuleCat.of (k[X])ᵐᵒᵖ (k[X] ⧸ Ideal.span {p})} :=
  let f : k[X] →ₗ[(k[X])ᵐᵒᵖ] k[X] :=
    { toFun := fun x => p * x
      map_add' := fun x y => by ring
      map_smul' := fun r x => by
        simp only [RingHom.id_apply, MulOpposite.smul_eq_mul_unop]; ring }
  let g : k[X] →ₗ[(k[X])ᵐᵒᵖ] (k[X] ⧸ Ideal.span {p}) :=
    { toFun := fun x => (Ideal.span {p}).mkQ x
      map_add' := fun x y => map_add _ x y
      map_smul' := fun r x => by
        rw [MulOpposite.smul_eq_mul_unop, RingHom.id_apply]
        change (Ideal.span {p}).mkQ (x * MulOpposite.unop r)
            = MulOpposite.unop r • (Ideal.span {p}).mkQ x
        rw [← map_smul]; congr 1; rw [smul_eq_mul, mul_comm] }
  have hf : ∀ x : k[X], f x = p * x := fun _ => rfl
  have hg : ∀ x : k[X], g x = (Ideal.span {p}).mkQ x := fun _ => rfl
  have hgf : ∀ x : k[X], g (f x) = 0 := by
    intro x
    rw [hf, hg, Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero, Ideal.mem_span_singleton]
    exact dvd_mul_right p x
  have eq0 : g.comp f = 0 :=
    LinearMap.ext fun x => by rw [LinearMap.comp_apply, hgf x, LinearMap.zero_apply]
  let S := ModuleCat.shortComplexOfCompEqZero f g eq0
  have hexact : Function.Exact f g := by
    rw [LinearMap.exact_iff]; ext y
    simp only [LinearMap.mem_ker, hg, Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero,
      Ideal.mem_span_singleton, LinearMap.mem_range, hf]
    constructor
    · rintro ⟨c, rfl⟩; exact ⟨c, rfl⟩
    · rintro ⟨c, rfl⟩; exact dvd_mul_right p c
  have hinj : Function.Injective f := fun x y hxy => mul_left_cancel₀ hp (by rw [← hf, ← hf, hxy])
  have hsurj : Function.Surjective g := Submodule.Quotient.mk_surjective _
  ⟨S, ModuleCat.shortComplex_shortExact S hexact hinj hsurj, rfl, rfl, rfl⟩

private noncomputable def polyZeroOpEquiv (k : Type u) [Field k] :
    (k[X] ⧸ Ideal.span {(0 : k[X])}) ≃ₗ[(k[X])ᵐᵒᵖ] k[X] :=
  let e0 : (k[X] ⧸ Ideal.span {(0 : k[X])}) ≃ₗ[k[X]] k[X] :=
    Submodule.quotEquivOfEqBot _ (by simp)
  { e0.toAddEquiv with
    map_smul' := fun r z => by
      change e0 (MulOpposite.unop r • z) = e0 z * MulOpposite.unop r
      rw [map_smul, smul_eq_mul, mul_comm] }

open Limits in

/-- The auxiliary categorical object from a polynomial quotient and a module vanishes from degree two onward. -/
theorem auxiliaryPolynomialQuotientModuleDegreeSuccSuccIsZero {k : Type u} [Field k] (f : k[X]) (N : Type u) [AddCommGroup N]
    [Module k[X] N] (n : ℕ) :
    Limits.IsZero (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup k[X] N
      (ModuleCat.of (k[X])ᵐᵒᵖ (k[X] ⧸ Ideal.span {f})) (n + 2)) := by
  rcases eq_or_ne f 0 with rfl | hf
  ·
    have hz := Functor.isZero_leftDerived_obj_projective_succ
      (RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionFunctor k[X] N) (n + 1) (ModuleCat.of (k[X])ᵐᵒᵖ k[X])
    exact hz.of_iso
      (((RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionFunctor k[X] N).leftDerived (n + 2)).mapIso (polyZeroOpEquiv k).toModuleIso)
  · obtain ⟨S, hS, hX₁, hX₂, hX₃⟩ := polyMopResolution k f hf
    set F := RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionFunctor k[X] N with hF
    obtain ⟨δ, hExact⟩ := RepresentationTheory.CategoryPair.AssociatedType.exists_connectingMorphism_exact F hS (n + 1) (n + 2) rfl
    have h1 : IsZero ((F.leftDerived (n + 2)).obj S.X₂) := by
      rw [hX₂]; exact Functor.isZero_leftDerived_obj_projective_succ F (n + 1) _
    have h3 : IsZero ((F.leftDerived (n + 1)).obj S.X₁) := by
      rw [hX₁]; exact Functor.isZero_leftDerived_obj_projective_succ F n _
    have hgoal : IsZero ((F.leftDerived (n + 2)).obj S.X₃) :=
      isZero_obj_two_of_sixTerm_exact hExact h1 h3
    rw [hX₃] at hgoal
    exact hgoal

/-- The auxiliary categorical object of a pair of polynomial quotients vanishes from degree two onward. -/
theorem auxiliaryPolynomialQuotientPairDegreeSuccSuccIsZero {k : Type u} [Field k] (f g : k[X]) (n : ℕ) :
    Limits.IsZero (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup k[X] (k[X] ⧸ Ideal.span {g})
      (ModuleCat.of (k[X])ᵐᵒᵖ (k[X] ⧸ Ideal.span {f})) (n + 2)) :=
  auxiliaryPolynomialQuotientModuleDegreeSuccSuccIsZero f (k[X] ⧸ Ideal.span {g}) n

/-- The positive-degree auxiliary categorical object with a polynomial-module input is zero. -/
theorem auxiliaryPolynomialModuleDegreeSuccIsZero (k : Type u) [Field k]
    (N : Type u) [AddCommGroup N] [Module k[X] N] (n : ℕ) :
    Limits.IsZero (RepresentationTheory.Algebra.Homology.TensorProductConstruction.degreewiseModuleGroup k[X] N (ModuleCat.of (k[X])ᵐᵒᵖ k[X]) (n + 1)) :=
  Functor.isZero_leftDerived_obj_projective_succ (RepresentationTheory.Algebra.Homology.TensorProductConstruction.moduleConstructionFunctor k[X] N) n
    (ModuleCat.of (k[X])ᵐᵒᵖ k[X])

/-- In degree zero, the auxiliary construction between polynomial quotients is additively equivalent to their joint quotient. -/
theorem auxiliaryPolynomialQuotientDegreeZeroAddEquiv (k : Type*) [Field k] (f g : k[X]) (hg : g ≠ 0) :
    Nonempty (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses (ModuleCat.of k[X] (k[X] ⧸ Ideal.span {f}))
        (ModuleCat.of k[X] (k[X] ⧸ Ideal.span {g})) 0
      ≃+ (k[X] ⧸ Ideal.span {f, g})) := by

  obtain ⟨e₀⟩ := RepresentationTheory.DerivedFunctorExactness.AuxiliaryDegreeZeroAddEquiv k[X] (ModuleCat.of k[X] (k[X] ⧸ Ideal.span {f}))
    (ModuleCat.of k[X] (k[X] ⧸ Ideal.span {g}))
  exact ⟨e₀.trans (ModuleCat.homAddEquiv.trans (linearMapQuotientAddEquiv f g hg))⟩

/-- In degree one, the auxiliary construction between polynomial quotients is additively equivalent to their joint quotient. -/
theorem auxiliaryPolynomialQuotientDegreeOneAddEquiv (k : Type*) [Field k] (f g : k[X]) (hf : f ≠ 0) :
    Nonempty (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses (ModuleCat.of k[X] (k[X] ⧸ Ideal.span {f}))
        (ModuleCat.of k[X] (k[X] ⧸ Ideal.span {g})) 1
      ≃+ (k[X] ⧸ Ideal.span {f, g})) := by

  let mf : k[X] →ₗ[k[X]] k[X] := f • LinearMap.id
  let pf : k[X] →ₗ[k[X]] (k[X] ⧸ Ideal.span {f}) := Algebra.linearMap k[X] (k[X] ⧸ Ideal.span {f})
  have hmf : ∀ x : k[X], mf x = f * x := fun x => by simp [mf]
  have hpf : ∀ x : k[X], pf x = Submodule.Quotient.mk x := fun x => rfl
  have hgf : ∀ x : k[X], pf (mf x) = 0 := by
    intro x; rw [hmf, hpf, Submodule.Quotient.mk_eq_zero, Ideal.mem_span_singleton]
    exact dvd_mul_right f x
  have eq0 : pf.comp mf = 0 :=
    LinearMap.ext fun x => by rw [LinearMap.comp_apply, hgf x, LinearMap.zero_apply]
  have hexact : Function.Exact mf pf := by
    rw [LinearMap.exact_iff]; ext y
    simp only [LinearMap.mem_ker, hpf, Submodule.Quotient.mk_eq_zero, Ideal.mem_span_singleton,
      LinearMap.mem_range, hmf]
    constructor
    · rintro ⟨c, rfl⟩; exact ⟨c, rfl⟩
    · rintro ⟨c, rfl⟩; exact dvd_mul_right f c
  have hinjf : Function.Injective mf :=
    fun x y hxy => mul_left_cancel₀ hf (by rw [← hmf, ← hmf, hxy])
  have hsurjg : Function.Surjective pf := by
    intro z; obtain ⟨y, rfl⟩ := Submodule.Quotient.mk_surjective _ z; exact ⟨y, hpf y⟩
  set S := ModuleCat.shortComplexOfCompEqZero mf pf eq0 with hSdef
  have hS : S.ShortExact := ModuleCat.shortComplex_shortExact S hexact hinjf hsurjg
  set Y := ModuleCat.of k[X] (k[X] ⧸ Ideal.span {g}) with hY

  have hExactCS := Abelian.Ext.contravariantSequence_exact hS Y 0 1 (by norm_num)
  let dhom : RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Y 0 →+ RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₃ Y 1 := hS.extClass.precomp Y (by norm_num)
  let m12 : RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₂ Y 0 →+ RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Y 0 :=
    (Abelian.Ext.mk₀ S.f).precomp Y (zero_add 0)

  have hsurjδ : Function.Surjective dhom := by
    rw [← AddMonoidHom.range_eq_top,
      show dhom.range = _ from (hExactCS.exact' 2 3 4).ab_range_eq_ker]
    ext x
    simp only [AddSubgroup.mem_top, iff_true, AddMonoidHom.mem_ker]
    exact (Abelian.Ext.subsingleton_of_projective S.X₂ Y 0).elim _ _
  have hkerδ : dhom.ker = m12.range := ((hExactCS.exact' 1 2 3).ab_range_eq_ker).symm

  let e0 : (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Y 0) ≃+ (k[X] ⧸ Ideal.span {g}) :=
    (Abelian.Ext.addEquiv₀).trans (ModuleCat.homAddEquiv.trans
      (LinearMap.ringLmapEquivSelf k[X] k[X] (k[X] ⧸ Ideal.span {g})).toAddEquiv)

  have hconj : ∀ β, e0 (m12 β) = quotientScalarLinearMap f g (e0 β) := by
    intro β
    have hred : m12 β = (Abelian.Ext.mk₀ S.f).comp β (zero_add 0) := rfl
    have step1 : Abelian.Ext.addEquiv₀ (m12 β) = S.f ≫ Abelian.Ext.addEquiv₀ β := by
      rw [hred]
      apply Abelian.Ext.addEquiv₀.symm.injective
      rw [AddEquiv.symm_apply_apply, Abelian.Ext.addEquiv₀_symm_apply, ← Abelian.Ext.mk₀_comp_mk₀,
        Abelian.Ext.mk₀_addEquiv₀_apply]
    change (LinearMap.ringLmapEquivSelf k[X] k[X] (k[X] ⧸ Ideal.span {g}))
        (ModuleCat.homAddEquiv (Abelian.Ext.addEquiv₀ (m12 β)))
      = quotientScalarLinearMap f g ((LinearMap.ringLmapEquivSelf k[X] k[X] (k[X] ⧸ Ideal.span {g}))
        (ModuleCat.homAddEquiv (Abelian.Ext.addEquiv₀ β)))
    rw [step1]
    simp only [ModuleCat.homAddEquiv_apply, ModuleCat.hom_comp,
      LinearMap.ringLmapEquivSelf_apply, quotientScalarLinearMap_apply]
    change (Abelian.Ext.addEquiv₀ β).hom (S.f.hom 1) = f • (Abelian.Ext.addEquiv₀ β).hom 1
    rw [show S.f.hom (1 : k[X]) = f • (1 : k[X]) from rfl, map_smul]

  have hrange : LinearMap.range (quotientScalarLinearMap f g)
      = Ideal.span {f} • (⊤ : Submodule k[X] (k[X] ⧸ Ideal.span {g})) := by
    rw [Submodule.ideal_span_singleton_smul]
    ext x
    simp only [LinearMap.mem_range, quotientScalarLinearMap_apply,
      Submodule.mem_smul_pointwise_iff_exists]
    constructor
    · rintro ⟨y, rfl⟩; exact ⟨y, Submodule.mem_top, rfl⟩
    · rintro ⟨y, _, rfl⟩; exact ⟨y, rfl⟩

  let δL := dhom.toIntLinearMap
  have hsurjδL : Function.Surjective δL := hsurjδ
  let e0L : (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Y 0) ≃ₗ[ℤ] (k[X] ⧸ Ideal.span {g}) := e0.toIntLinearEquiv
  have he0L : ∀ x, (e0L : (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Y 0) →ₗ[ℤ] (k[X] ⧸ Ideal.span {g})) x = e0 x :=
    fun _ => rfl
  have hmap : Submodule.map (e0L : (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses S.X₁ Y 0) →ₗ[ℤ] (k[X] ⧸ Ideal.span {g}))
      (LinearMap.ker δL)
      = (Ideal.span {f} • (⊤ : Submodule k[X] (k[X] ⧸ Ideal.span {g}))).restrictScalars ℤ := by
    rw [← hrange]
    ext z
    simp only [Submodule.mem_map, LinearMap.mem_ker, Submodule.restrictScalars_mem,
      LinearMap.mem_range, he0L]
    constructor
    · rintro ⟨y, hy, rfl⟩
      have hy' : y ∈ dhom.ker := AddMonoidHom.mem_ker.mpr hy
      rw [hkerδ] at hy'
      obtain ⟨u, hu⟩ := hy'
      exact ⟨e0 u, by rw [← hconj, hu]⟩
    · rintro ⟨w, rfl⟩
      refine ⟨m12 (e0.symm w), ?_, ?_⟩
      · have : m12 (e0.symm w) ∈ dhom.ker :=
          hkerδ.symm ▸ AddMonoidHom.mem_range.mpr ⟨e0.symm w, rfl⟩
        exact AddMonoidHom.mem_ker.mp this
      · rw [hconj, e0.apply_symm_apply]
  exact ⟨((LinearMap.quotKerEquivOfSurjective δL hsurjδL).symm.trans
    (Submodule.Quotient.equiv (LinearMap.ker δL) _ e0L hmap)).toAddEquiv.trans
    (iteratedQuotientLinearEquiv f g).toAddEquiv⟩

private lemma polyQuot_hasProjectiveDimensionLT_two (k : Type u) [Field k] (p : k[X]) :
    HasProjectiveDimensionLT (ModuleCat.of k[X] (k[X] ⧸ Ideal.span {p})) 2 := by
  rcases eq_or_ne p 0 with rfl | hp
  ·
    have e : (k[X] ⧸ Ideal.span {(0 : k[X])}) ≃ₗ[k[X]] k[X] :=
      Submodule.quotEquivOfEqBot _ (by simp)
    haveI : HasProjectiveDimensionLT (ModuleCat.of k[X] k[X]) 1 :=
      projective_iff_hasProjectiveDimensionLT_one.mp inferInstance
    haveI : HasProjectiveDimensionLT (ModuleCat.of k[X] k[X]) 2 :=
      hasProjectiveDimensionLT_of_ge (ModuleCat.of k[X] k[X]) 1 2 (by omega)
    exact hasProjectiveDimensionLT_of_iso
      (e.toModuleIso.symm : ModuleCat.of k[X] k[X] ≅ ModuleCat.of k[X] _) 2
  ·
    let f : k[X] →ₗ[k[X]] k[X] := p • LinearMap.id
    let g : k[X] →ₗ[k[X]] (k[X] ⧸ Ideal.span {p}) := (Ideal.span {p}).mkQ
    have hf : ∀ x : k[X], f x = p * x := fun x => by simp [f]
    have eq0 : g.comp f = 0 := by
      refine LinearMap.ext fun x => ?_
      simp only [LinearMap.comp_apply, hf, g, Submodule.mkQ_apply, LinearMap.zero_apply,
        Submodule.Quotient.mk_eq_zero, Ideal.mem_span_singleton]
      exact dvd_mul_right p x
    let S := ModuleCat.shortComplexOfCompEqZero f g eq0
    have hexact : Function.Exact f g := by
      rw [LinearMap.exact_iff]
      ext y
      simp only [g, LinearMap.mem_ker, Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero,
        Ideal.mem_span_singleton, LinearMap.mem_range, hf]
      constructor
      · rintro ⟨c, rfl⟩; exact ⟨c, rfl⟩
      · rintro ⟨c, rfl⟩; exact dvd_mul_right p c
    have hinj : Function.Injective f := fun x y hxy =>
      mul_left_cancel₀ hp (by rw [← hf, ← hf, hxy])
    have hsurj : Function.Surjective g := (Ideal.span {p}).mkQ_surjective
    have hS : S.ShortExact := ModuleCat.shortComplex_shortExact S hexact hinj hsurj
    exact hasProjectiveDimensionLT_two_of_shortExact hS inferInstance inferInstance

/-- The auxiliary construction for a pair of polynomial quotients is subsingleton from degree two onward. -/
theorem auxiliaryPolynomialQuotientPairDegreeSuccSuccSubsingleton (k : Type*) [Field k] (f g : k[X]) (n : ℕ) :
    Subsingleton (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses (ModuleCat.of k[X] (k[X] ⧸ Ideal.span {f}))
      (ModuleCat.of k[X] (k[X] ⧸ Ideal.span {g})) (n + 2)) := by
  haveI := polyQuot_hasProjectiveDimensionLT_two k f
  exact HasProjectiveDimensionLT.subsingleton
    (ModuleCat.of k[X] (k[X] ⧸ Ideal.span {f})) 2 (n + 2) (by omega) _

/-- The positive-degree auxiliary construction from a polynomial module is subsingleton. -/
theorem auxiliaryPolynomialModuleDegreeSuccSubsingleton (k : Type u) [Field k]
    (N : ModuleCat.{u} k[X]) (n : ℕ) :
    Subsingleton (RepresentationTheory.CategoryTheory.Abelian.ExtensionClasses.CategoryTheory.ExtensionClasses (ModuleCat.of k[X] k[X]) N (n + 1)) :=
  Abelian.Ext.subsingleton_of_projective (ModuleCat.of k[X] k[X]) N n

end RepresentationTheory.PolynomialQuotientZModAuxiliary
