/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENCE.
Authors: Kim Morrison
-/

import Mathlib
import RepresentationTheory.Alignment.Attribute

/-!
# Semisimple group algebra cardinality

The cardinality of a finite group whose group algebra over a field is semisimple is a unit in the
field.
-/

namespace RepresentationTheory.SemisimpleGroupAlgebraCardinality

/-- If the group algebra of a finite group over a field is semisimple, then the field-valued cardinality of the group is a unit. -/
@[source_ref "Chapter4/Discussion_before_Proposition4.1.2" (role := primary),
  source_ref "Chapter4/Proposition4.1.2" (role := primary),
  source_ref "Chapter4/Example4.1.3/Derived2" (role := supporting)]
theorem isUnit_card_of_isSemisimpleRing
    (k : Type*) (G : Type*) [Field k] [Group G] [Fintype G]
    [DecidableEq G]
    (h : IsSemisimpleRing (MonoidAlgebra k G)) :
    IsUnit ((Fintype.card G : k)) := by
  by_contra hnu
  -- In a field, ¬IsUnit means = 0
  have hzero : (Fintype.card G : k) = 0 := by
    by_contra hne; exact hnu (IsUnit.mk0 _ hne)
  -- Define Λ = Σ_g single g 1
  set Λ : MonoidAlgebra k G := ∑ g : G, MonoidAlgebra.single g (1 : k) with hΛ_def
  -- Left multiplication: single g 1 * Λ = Λ
  have left_mul : ∀ g : G, MonoidAlgebra.single g (1 : k) * Λ = Λ := by
    intro g
    simp only [hΛ_def, Finset.mul_sum, MonoidAlgebra.single_mul_single, one_mul]
    exact Fintype.sum_equiv (Equiv.mulLeft g) _ _ (fun _ => rfl)
  -- Right multiplication: Λ * single g 1 = Λ
  have right_mul : ∀ g : G, Λ * MonoidAlgebra.single g (1 : k) = Λ := by
    intro g
    simp only [hΛ_def, Finset.sum_mul, MonoidAlgebra.single_mul_single, mul_one]
    exact Fintype.sum_equiv (Equiv.mulRight g) _ _ (fun _ => rfl)
  -- Λ * Λ = |G| • Λ
  have hΛsq : Λ * Λ = (Fintype.card G : k) • Λ := by
    conv_lhs => lhs; rw [hΛ_def]
    rw [Finset.sum_mul]
    simp_rw [left_mul]
    rw [Finset.sum_const, Finset.card_univ, ← Nat.cast_smul_eq_nsmul k]
  -- Hence Λ * Λ = 0
  have hΛnil : Λ * Λ = 0 := by rw [hΛsq, hzero, zero_smul]
  -- Λ ≠ 0
  have hΛne : Λ ≠ 0 := by
    intro heq
    let evalOne : MonoidAlgebra k G →+ k :=
      { toFun := fun x => x.coeff 1
        map_zero' := rfl
        map_add' := by intro x y; rfl }
    have h1 : evalOne Λ = 0 := by rw [heq]; rfl
    have hΛ1 : evalOne Λ = 1 := by
      rw [hΛ_def]
      rw [map_sum]
      simp [evalOne, MonoidAlgebra.single_apply]
    rw [hΛ1] at h1
    exact one_ne_zero h1
  -- Centrality: Λ is in the center
  have hΛcentral : ∀ x : MonoidAlgebra k G, Λ * x = x * Λ := by
    intro x
    have key : ∀ g : G, ∀ c : k,
        Λ * MonoidAlgebra.single g c = MonoidAlgebra.single g c * Λ := by
      intro g c
      have : MonoidAlgebra.single g c = c • MonoidAlgebra.single g (1 : k) := by
        ext h; simp [Finsupp.single_apply]
      rw [this, smul_mul_assoc, mul_smul_comm, right_mul, left_mul]
    rw [show x = x.coeff.sum MonoidAlgebra.single from (MonoidAlgebra.sum_coeff_single x).symm]
    simp only [Finsupp.sum, Finset.mul_sum, Finset.sum_mul]
    exact Finset.sum_congr rfl fun g _ => key g (x.coeff g)
  -- The left ideal generated by Λ has an idempotent generator
  obtain ⟨e, he_idem, he_eq⟩ := IsSemisimpleRing.ideal_eq_span_idempotent (Ideal.span {Λ})
  -- e ∈ Ideal.span {Λ}, so e = r * Λ for some r
  have he_mem : e ∈ Ideal.span ({Λ} : Set (MonoidAlgebra k G)) :=
    he_eq ▸ Ideal.subset_span rfl
  obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.mp he_mem
  -- e * e = 0 using centrality and Λ² = 0
  have he_sq_zero : e * e = 0 := by
    rw [← hr]
    calc r * Λ * (r * Λ)
        = r * (Λ * (r * Λ)) := by rw [mul_assoc]
      _ = r * (r * Λ * Λ) := by rw [hΛcentral (r * Λ)]
      _ = r * (r * (Λ * Λ)) := by rw [mul_assoc r Λ Λ]
      _ = r * (r * 0) := by rw [hΛnil]
      _ = 0 := by rw [mul_zero, mul_zero]
  -- e² = e and e² = 0 implies e = 0
  have he_zero : e = 0 := by
    have := he_idem.eq; rw [he_sq_zero] at this; exact this.symm
  -- Ideal.span {Λ} = ⊥
  have hbot : Ideal.span ({Λ} : Set (MonoidAlgebra k G)) = ⊥ := by
    rw [he_eq, he_zero, Set.singleton_zero, Ideal.span_zero]
  -- Λ = 0: contradiction
  have hΛzero : Λ ∈ (⊥ : Ideal (MonoidAlgebra k G)) :=
    hbot ▸ Ideal.subset_span rfl
  rw [Ideal.mem_bot] at hΛzero
  exact hΛne hΛzero

end RepresentationTheory.SemisimpleGroupAlgebraCardinality
