/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: mathlib-initiative
-/

import Mathlib.Tactic.NoncommRing
import Mathlib.FieldTheory.PurelyInseparable.Basic
import Mathlib.RingTheory.SimpleModule.WedderburnArtin
import Mathlib.RingTheory.TensorProduct.Pi
import RepresentationTheory.Alignment.Attribute

/-!
# Jacobson ideals in tensor products

This module develops the distinguished ideal generated by the Jacobson ideals of two factors in
their tensor-product algebra. It establishes the corresponding quotient equivalences,
nilpotence results, semisimplicity criterion, and finite-dimensional radical formula.
-/

namespace RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct

open scoped _root_.TensorProduct

section Defs

variable (k A B : Type*) [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]

/-- The algebra homomorphism from a tensor product to the tensor product of the two factor algebras modulo their Jacobson radicals. -/
noncomputable def tensorProductQuotientMap :
    A ⊗[k] B →ₐ[k] (A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B) :=
  Algebra.TensorProduct.map (Ideal.Quotient.mkₐ k (Ring.jacobson A))
    (Ideal.Quotient.mkₐ k (Ring.jacobson B))

/-- A first auxiliary ideal of a tensor-product algebra. -/
noncomputable def tensorProductIdeal_aux1 : Ideal (A ⊗[k] B) :=
  Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B))
    (Ring.jacobson A)

/-- A second auxiliary ideal of a tensor-product algebra. -/
noncomputable def tensorProductIdeal_aux2 : Ideal (A ⊗[k] B) :=
  Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) (Ring.jacobson B)

/-- The distinguished ideal of a tensor-product algebra formed from the Jacobson radicals of its two factors. -/
noncomputable def tensorProductJacobsonIdeal : Ideal (A ⊗[k] B) :=
  tensorProductIdeal_aux1 k A B ⊔ tensorProductIdeal_aux2 k A B

end Defs

section Basic

variable {k A B : Type*} [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]

/-- The tensor-product quotient map sends a pure tensor to the pure tensor of the two quotient classes. -/
@[simp]
theorem tensorProductQuotientMap_tmul (a : A) (b : B) :
    tensorProductQuotientMap k A B (a ⊗ₜ[k] b) =
      (Ideal.Quotient.mk (Ring.jacobson A) a) ⊗ₜ[k] (Ideal.Quotient.mk (Ring.jacobson B) b) :=
  rfl

/-- The tensor-product map to the tensor product of the Jacobson-radical quotients is surjective. -/
theorem tensorProductQuotientMap_surjective : Function.Surjective (tensorProductQuotientMap k A B) :=
  Algebra.TensorProduct.map_surjective _ _ Ideal.Quotient.mk_surjective
    Ideal.Quotient.mk_surjective

/-- The distinguished tensor-product ideal is the kernel of the map to the tensor product of the Jacobson-radical quotients. -/
theorem tensorProductJacobsonIdeal_eq_ker :
    tensorProductJacobsonIdeal k A B = RingHom.ker (tensorProductQuotientMap k A B) := by
  have hA : RingHom.ker (Ideal.Quotient.mkₐ k (Ring.jacobson A)) = Ring.jacobson A :=
    Ideal.mk_ker
  have hB : RingHom.ker (Ideal.Quotient.mkₐ k (Ring.jacobson B)) = Ring.jacobson B :=
    Ideal.mk_ker
  rw [tensorProductQuotientMap, Algebra.TensorProduct.map_ker _ _ Ideal.Quotient.mk_surjective
    Ideal.Quotient.mk_surjective, hA, hB]
  rfl

/-- The distinguished Jacobson ideal in a tensor product of algebras is two-sided. -/
instance tensorProductJacobsonIdeal_isTwoSided : (tensorProductJacobsonIdeal k A B).IsTwoSided := by
  rw [tensorProductJacobsonIdeal_eq_ker]; infer_instance

/-- The quotient by the distinguished tensor-product ideal is algebra-equivalent to the tensor product of the factor algebras modulo their Jacobson radicals. -/
noncomputable def quotientTensorProductJacobsonIdealAlgEquiv :
    ((A ⊗[k] B) ⧸ tensorProductJacobsonIdeal k A B) ≃ₐ[k]
      (A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B) :=
  (Ideal.quotientEquivAlgOfEq k tensorProductJacobsonIdeal_eq_ker).trans
    (Ideal.quotientKerAlgEquivOfSurjective tensorProductQuotientMap_surjective)

end Basic

section Nilpotent

/-- Every nilpotent ideal of a ring is contained in its Jacobson radical. -/
theorem le_jacobson_of_isNilpotent {R : Type*} [Ring R] {I : Ideal R} (h : IsNilpotent I) :
    I ≤ Ring.jacobson R := by
  obtain ⟨n, hn⟩ := h
  intro x hx
  rw [← Ideal.jacobson_bot, Ideal.mem_jacobson_iff]
  intro y
  have hyx : y * x ∈ I := I.mul_mem_left y hx
  have hpow : (y * x) ^ n ∈ I ^ n := Ideal.pow_mem_pow hyx n
  rw [hn] at hpow
  have hnil : IsNilpotent (-(y * x)) :=
    IsNilpotent.neg (⟨n, by simpa using hpow⟩ : IsNilpotent (y * x))
  obtain ⟨u, hu⟩ := IsNilpotent.isUnit_one_sub hnil
  refine ⟨(↑u⁻¹ : R), ?_⟩
  have h1 : (↑u⁻¹ : R) * (1 + y * x) = 1 := by
    rw [show (1 : R) + y * x = (u : R) by rw [hu, sub_neg_eq_add]]
    exact u.inv_mul
  have h2 : (↑u⁻¹ : R) * y * x + (↑u⁻¹ : R) = (↑u⁻¹ : R) * (1 + y * x) := by noncomm_ring
  rw [h2, h1, sub_self]
  exact Ideal.zero_mem _

variable {k A B : Type*} [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]

/-- The product of two ideals mapped through the left tensor-product inclusion is contained in the image of their product. -/
theorem map_includeLeft_mul_le (I J : Ideal A) :
    Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) I *
        Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) J ≤
      Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B))
        (I * J) := by
  rw [Ideal.mul_le]
  have key : ∀ x ∈ Ideal.map
      (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) I,
      ∀ y ∈ Ideal.map
        (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) J,
      x * y ∈ Ideal.map
        (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) (I * J) := by
    intro x hx y hy
    have hx' : x ∈ LinearMap.range
        (LinearMap.rTensor B (Submodule.subtype (I.restrictScalars k))) := by
      rw [← Ideal.map_includeLeft_eq]; exact hx
    have hy' : y ∈ LinearMap.range
        (LinearMap.rTensor B (Submodule.subtype (J.restrictScalars k))) := by
      rw [← Ideal.map_includeLeft_eq]; exact hy
    obtain ⟨s, rfl⟩ := hx'
    obtain ⟨t, rfl⟩ := hy'
    clear hx hy
    induction s with
    | zero => simp
    | add s₁ s₂ h₁ h₂ => rw [map_add, add_mul]; exact Ideal.add_mem _ h₁ h₂
    | tmul a b =>
      induction t with
      | zero => simp
      | add t₁ t₂ h₁ h₂ => rw [map_add, mul_add]; exact Ideal.add_mem _ h₁ h₂
      | tmul a' b' =>
        simp only [LinearMap.rTensor_tmul, Submodule.coe_subtype,
          Algebra.TensorProduct.tmul_mul_tmul]
        have hmem : (a : A) * (a' : A) ∈ I * J :=
          Ideal.mul_mem_mul a.2 a'.2
        have : ((a : A) * (a' : A)) ⊗ₜ[k] ((b : B) * b') =
            ((1 : A) ⊗ₜ[k] ((b : B) * b')) *
              (((a : A) * (a' : A)) ⊗ₜ[k] (1 : B)) := by
          simp [Algebra.TensorProduct.tmul_mul_tmul]
        rw [this]
        exact Ideal.mul_mem_left _ _ (Ideal.mem_map_of_mem _ hmem)
  exact key

/-- A power of an ideal mapped through the left tensor-product inclusion is contained in the image of the corresponding ideal power. -/
theorem map_includeLeft_pow_le (I : Ideal A) (n : ℕ) :
    Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B)) I ^ n ≤
      Ideal.map (Algebra.TensorProduct.includeLeft (R := k) (S := k) (A := A) (B := B))
        (I ^ n) := by
  induction n with
  | zero =>
    rw [Submodule.pow_zero, Submodule.pow_zero, Ideal.one_eq_top, Ideal.one_eq_top,
      Ideal.map_top]
  | succ n ih =>
    rw [Submodule.pow_succ, Submodule.pow_succ]
    exact le_trans (Ideal.mul_mono ih le_rfl) (map_includeLeft_mul_le _ _)

/-- The first auxiliary ideal of the tensor product is nilpotent when the left factor is finite-dimensional. -/
theorem tensorProductIdeal_aux1_isNilpotent [FiniteDimensional k A] :
    IsNilpotent (tensorProductIdeal_aux1 k A B) := by
  haveI : IsArtinianRing A := IsArtinianRing.of_finite k A
  obtain ⟨n, hn⟩ := IsSemiprimaryRing.isNilpotent (R := A)
  refine ⟨n, le_bot_iff.mp ?_⟩
  refine le_trans (map_includeLeft_pow_le (B := B) (Ring.jacobson A) n) ?_
  rw [show Ring.jacobson A ^ n = ⊥ from hn, Ideal.map_bot]

/-- The product of two ideals mapped through the right tensor-product inclusion is contained in the image of their product. -/
theorem map_includeRight_mul_le (I J : Ideal B) :
    Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) I *
        Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) J ≤
      Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) (I * J) := by
  rw [Ideal.mul_le]
  intro x hx y hy
  have hx' : x ∈ LinearMap.range
      (LinearMap.lTensor A (Submodule.subtype (I.restrictScalars k))) := by
    rw [← Ideal.map_includeRight_eq]; exact hx
  have hy' : y ∈ LinearMap.range
      (LinearMap.lTensor A (Submodule.subtype (J.restrictScalars k))) := by
    rw [← Ideal.map_includeRight_eq]; exact hy
  obtain ⟨s, rfl⟩ := hx'
  obtain ⟨t, rfl⟩ := hy'
  clear hx hy
  induction s with
  | zero => simp
  | add s₁ s₂ h₁ h₂ => rw [map_add, add_mul]; exact Ideal.add_mem _ h₁ h₂
  | tmul a b =>
    induction t with
    | zero => simp
    | add t₁ t₂ h₁ h₂ => rw [map_add, mul_add]; exact Ideal.add_mem _ h₁ h₂
    | tmul a' b' =>
      simp only [LinearMap.lTensor_tmul, Submodule.coe_subtype,
        Algebra.TensorProduct.tmul_mul_tmul]
      have hmem : (b : B) * (b' : B) ∈ I * J := Ideal.mul_mem_mul b.2 b'.2
      have : (a * a') ⊗ₜ[k] ((b : B) * (b' : B)) =
          ((a * a') ⊗ₜ[k] (1 : B)) * ((1 : A) ⊗ₜ[k] ((b : B) * (b' : B))) := by
        simp [Algebra.TensorProduct.tmul_mul_tmul]
      rw [this]
      exact Ideal.mul_mem_left _ _ (Ideal.mem_map_of_mem _ hmem)

/-- A power of an ideal mapped through the right tensor-product inclusion is contained in the image of the corresponding ideal power. -/
theorem map_includeRight_pow_le (I : Ideal B) (n : ℕ) :
    Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) I ^ n ≤
      Ideal.map (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := B)) (I ^ n) := by
  induction n with
  | zero =>
    rw [Submodule.pow_zero, Submodule.pow_zero, Ideal.one_eq_top, Ideal.one_eq_top,
      Ideal.map_top]
  | succ n ih =>
    rw [Submodule.pow_succ, Submodule.pow_succ]
    exact le_trans (Ideal.mul_mono ih le_rfl) (map_includeRight_mul_le _ _)

/-- The second auxiliary ideal of the tensor product is nilpotent when the right factor is finite-dimensional. -/
theorem tensorProductIdeal_aux2_isNilpotent [FiniteDimensional k B] :
    IsNilpotent (tensorProductIdeal_aux2 k A B) := by
  haveI : IsArtinianRing B := IsArtinianRing.of_finite k B
  obtain ⟨n, hn⟩ := IsSemiprimaryRing.isNilpotent (R := B)
  refine ⟨n, le_bot_iff.mp ?_⟩
  refine le_trans (map_includeRight_pow_le (A := A) (Ring.jacobson B) n) ?_
  rw [show Ring.jacobson B ^ n = ⊥ from hn, Ideal.map_bot]

/-- For finite-dimensional factor algebras, the distinguished tensor-product ideal is contained in the Jacobson radical of the tensor product. -/
theorem tensorProductJacobsonIdeal_le_jacobson [FiniteDimensional k A] [FiniteDimensional k B] :
    tensorProductJacobsonIdeal k A B ≤ Ring.jacobson (A ⊗[k] B) :=
  sup_le (le_jacobson_of_isNilpotent tensorProductIdeal_aux1_isNilpotent)
    (le_jacobson_of_isNilpotent tensorProductIdeal_aux2_isNilpotent)

/-- The distinguished Jacobson ideal in the tensor product of two finite-dimensional algebras is nilpotent. -/
theorem tensorProductJacobsonIdeal_isNilpotent [FiniteDimensional k A] [FiniteDimensional k B] :
    IsNilpotent (tensorProductJacobsonIdeal k A B) := by
  haveI : IsArtinianRing (A ⊗[k] B) := IsArtinianRing.of_finite k (A ⊗[k] B)
  obtain ⟨n, hn⟩ := IsSemiprimaryRing.isNilpotent (R := A ⊗[k] B)
  refine ⟨n, le_bot_iff.mp ?_⟩
  refine le_trans (Ideal.pow_right_mono tensorProductJacobsonIdeal_le_jacobson n) ?_
  rw [show Ring.jacobson (A ⊗[k] B) ^ n = ⊥ from hn]

end Nilpotent

section Semisimple

variable {k A B : Type*} [Field k] [Ring A] [Ring B] [Algebra k A] [Algebra k B]

/-- If the tensor product of the semisimple quotients is semisimple, the Jacobson radical of the tensor product is contained in the distinguished tensor-product ideal. -/
theorem jacobson_le_tensorProductJacobsonIdeal_of_isSemisimpleRing
    (h : IsSemisimpleRing ((A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B))) :
    Ring.jacobson (A ⊗[k] B) ≤ tensorProductJacobsonIdeal k A B := by
  have hq : IsSemisimpleRing ((A ⊗[k] B) ⧸ tensorProductJacobsonIdeal k A B) :=
    (quotientTensorProductJacobsonIdealAlgEquiv (k := k) (A := A) (B := B)).symm.toRingEquiv.isSemisimpleRing
  exact Ring.jacobson_le_of_eq_bot (IsSemisimpleRing.jacobson_eq_bot _)

end Semisimple

section AlgClosed

variable {k : Type*} [Field k] [IsAlgClosed k]

/-- A finite-dimensional semisimple algebra over an algebraically closed field is equivalent to a finite product of nonzero-size full matrix algebras. -/
theorem exists_algEquiv_pi_matrix_of_isSemisimpleRing (A : Type*) [Ring A] [Algebra k A] [FiniteDimensional k A]
    [IsSemisimpleRing A] :
    ∃ (n : ℕ) (d : Fin n → ℕ), (∀ i, NeZero (d i)) ∧
      Nonempty (A ≃ₐ[k] ∀ i, Matrix (Fin (d i)) (Fin (d i)) k) := by
  obtain ⟨n, D, d, _, _, hDfin, hd, ⟨e⟩⟩ :=
    IsSemisimpleRing.exists_algEquiv_pi_matrix_divisionRing_finite (R₀ := k) (R := A)
  refine ⟨n, d, hd, ⟨e.trans (AlgEquiv.piCongrRight fun i => ?_)⟩⟩
  haveI := hDfin i
  have hbij : Function.Bijective (algebraMap k (D i)) :=
    IsAlgClosed.algebraMap_bijective_of_isIntegral
  exact (AlgEquiv.ofBijective (Algebra.ofId k (D i)) hbij).symm.mapMatrix

/-- The tensor product of two finite-dimensional semisimple algebras over an algebraically closed field is semisimple. -/
@[source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := supporting)]
theorem isSemisimpleRing_tensorProduct
    (A B : Type*) [Ring A] [Algebra k A] [FiniteDimensional k A] [IsSemisimpleRing A]
    [Ring B] [Algebra k B] [FiniteDimensional k B] [IsSemisimpleRing B] :
    IsSemisimpleRing (A ⊗[k] B) := by
  classical
  obtain ⟨n, d, hd, ⟨eA⟩⟩ := exists_algEquiv_pi_matrix_of_isSemisimpleRing (k := k) A
  obtain ⟨m, c, hc, ⟨eB⟩⟩ := exists_algEquiv_pi_matrix_of_isSemisimpleRing (k := k) B
  haveI model : ∀ (j : Fin m),
      IsSemisimpleRing ((∀ i, Matrix (Fin (d i)) (Fin (d i)) k) ⊗[k]
        Matrix (Fin (c j)) (Fin (c j)) k) := by
    intro j
    haveI : ∀ i, IsSemisimpleRing
        (Matrix (Fin (c j)) (Fin (c j)) k ⊗[k] Matrix (Fin (d i)) (Fin (d i)) k) := fun i =>
      (Matrix.kroneckerAlgEquiv (Fin (c j)) (Fin (d i)) k).symm.toRingEquiv.isSemisimpleRing
    have e1 : (∀ i, Matrix (Fin (d i)) (Fin (d i)) k) ⊗[k]
        Matrix (Fin (c j)) (Fin (c j)) k ≃ₐ[k]
        ∀ i, Matrix (Fin (c j)) (Fin (c j)) k ⊗[k] Matrix (Fin (d i)) (Fin (d i)) k :=
      (Algebra.TensorProduct.comm k _ _).trans (Algebra.TensorProduct.piRight k k _ _)
    exact e1.symm.toRingEquiv.isSemisimpleRing
  haveI : IsSemisimpleRing ((∀ i, Matrix (Fin (d i)) (Fin (d i)) k) ⊗[k]
      (∀ j, Matrix (Fin (c j)) (Fin (c j)) k)) :=
    (Algebra.TensorProduct.piRight k k (∀ i, Matrix (Fin (d i)) (Fin (d i)) k)
      (fun j => Matrix (Fin (c j)) (Fin (c j)) k)).symm.toRingEquiv.isSemisimpleRing
  exact (Algebra.TensorProduct.congr eA eB).symm.toRingEquiv.isSemisimpleRing

end AlgClosed

section Main

variable {k A B : Type*} [Field k] [IsAlgClosed k]
variable [Ring A] [Ring B] [Algebra k A] [Algebra k B]
variable [FiniteDimensional k A] [FiniteDimensional k B]

/-- For finite-dimensional algebras over an algebraically closed field, the Jacobson radical of their tensor product equals the distinguished tensor-product ideal. -/
theorem jacobson_tensorProduct_eq :
    Ring.jacobson (A ⊗[k] B) = tensorProductJacobsonIdeal k A B := by
  haveI : IsArtinianRing A := IsArtinianRing.of_finite k A
  haveI : IsArtinianRing B := IsArtinianRing.of_finite k B
  haveI : FiniteDimensional k (A ⧸ Ring.jacobson A) :=
    Module.Finite.of_surjective (Ideal.Quotient.mkₐ k (Ring.jacobson A)).toLinearMap
      Ideal.Quotient.mk_surjective
  haveI : FiniteDimensional k (B ⧸ Ring.jacobson B) :=
    Module.Finite.of_surjective (Ideal.Quotient.mkₐ k (Ring.jacobson B)).toLinearMap
      Ideal.Quotient.mk_surjective
  exact le_antisymm (jacobson_le_tensorProductJacobsonIdeal_of_isSemisimpleRing (isSemisimpleRing_tensorProduct _ _))
    tensorProductJacobsonIdeal_le_jacobson

/-- The quotient of a finite-dimensional tensor-product algebra by its Jacobson radical is algebra-equivalent to the tensor product of the two Jacobson-radical quotients. -/
@[source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := primary)]
noncomputable def quotientJacobsonTensorProductAlgEquiv :
    ((A ⊗[k] B) ⧸ Ring.jacobson (A ⊗[k] B)) ≃ₐ[k]
      (A ⧸ Ring.jacobson A) ⊗[k] (B ⧸ Ring.jacobson B) :=
  (Ideal.quotientEquivAlgOfEq k jacobson_tensorProduct_eq).trans quotientTensorProductJacobsonIdealAlgEquiv

end Main

section ImageAlgebras

/-- The algebra homomorphism from the tensor product of the ranges of two commuting actions to endomorphisms of their common module. -/
@[source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := supporting)]
noncomputable def tensorProductRangeAction
    {k A B M : Type*} [CommSemiring k] [Semiring A] [Semiring B]
    [Algebra k A] [Algebra k B] [AddCommMonoid M] [Module k M]
    (rhoA : A →ₐ[k] Module.End k M) (rhoB : B →ₐ[k] Module.End k M)
    (hcomm : ∀ a b, Commute (rhoA a) (rhoB b)) :
    rhoA.range ⊗[k] rhoB.range →ₐ[k] Module.End k M :=
  Algebra.TensorProduct.lift (Subalgebra.val rhoA.range) (Subalgebra.val rhoB.range) fun x y => by
    obtain ⟨a, ha⟩ := x.property
    obtain ⟨b, hb⟩ := y.property
    change Commute (x : Module.End k M) (y : Module.End k M)
    rw [← ha, ← hb]
    exact hcomm a b

/-- On a pure tensor from the two action ranges, the tensor-product action is the product of the corresponding endomorphisms. -/
@[simp, source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := supporting)]
theorem tensorProductRangeAction_tmul
    {k A B M : Type*} [CommSemiring k] [Semiring A] [Semiring B]
    [Algebra k A] [Algebra k B] [AddCommMonoid M] [Module k M]
    (rhoA : A →ₐ[k] Module.End k M) (rhoB : B →ₐ[k] Module.End k M)
    (hcomm : ∀ a b, Commute (rhoA a) (rhoB b)) (a : A) (b : B) :
    tensorProductRangeAction rhoA rhoB hcomm (rhoA.rangeRestrict a ⊗ₜ[k] rhoB.rangeRestrict b) =
      rhoA a * rhoB b := by
  exact Algebra.TensorProduct.lift_tmul _ _ _ _ _

/-- The module structure induced by two commuting algebra actions over the tensor product of their ranges. -/
@[reducible, source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := supporting)]
noncomputable def tensorProductRangeModule
    {k A B M : Type*} [CommSemiring k] [Semiring A] [Semiring B]
    [Algebra k A] [Algebra k B] [AddCommMonoid M] [Module k M]
    (rhoA : A →ₐ[k] Module.End k M) (rhoB : B →ₐ[k] Module.End k M)
    (hcomm : ∀ a b, Commute (rhoA a) (rhoB b)) :
    Module (rhoA.range ⊗[k] rhoB.range) M :=
  Module.compHom M (tensorProductRangeAction rhoA rhoB hcomm).toRingHom

variable (k : Type*) (A B M : Type*) [Field k] [IsAlgClosed k]
variable [Ring A] [Algebra k A] [Ring B] [Algebra k B]
variable [AddCommGroup M] [Module k M] [FiniteDimensional k M]
variable [Module A M] [IsScalarTower k A M] [Module B M] [IsScalarTower k B M]

/-- For two algebra actions on a finite-dimensional vector space over an algebraically closed field, the Jacobson radical of the tensor product of their ranges is the corresponding distinguished ideal. -/
theorem jacobson_tensorProduct_actionRange_eq :
    Ring.jacobson
        (↥(Algebra.lsmul k k M : A →ₐ[k] Module.End k M).range ⊗[k]
          ↥(Algebra.lsmul k k M : B →ₐ[k] Module.End k M).range) =
      tensorProductJacobsonIdeal k _ _ :=
  jacobson_tensorProduct_eq

end ImageAlgebras

end RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct

/--
If the tensor product of the Jacobson-radical quotients is semisimple, the Jacobson radical of
the tensor product is contained in the third auxiliary ideal.
-/
alias _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.jacobson_le_tensorProductIdeal_aux3_of_isSemisimpleRing := _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.jacobson_le_tensorProductJacobsonIdeal_of_isSemisimpleRing

/--
For two algebra actions on a finite-dimensional vector space over an algebraically closed field,
the Jacobson radical of the tensor product of their ranges equals the corresponding third
auxiliary ideal.
-/
alias _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.jacobson_tensorProduct_actionRange_eq_aux3 := _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.jacobson_tensorProduct_actionRange_eq

/--
For finite-dimensional algebras over an algebraically closed field, the Jacobson radical of
their tensor product equals the third auxiliary ideal.
-/
alias _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.jacobson_tensorProduct_eq_aux3 := _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.jacobson_tensorProduct_eq

/--
The quotient by the third auxiliary tensor-product ideal is algebra-equivalent to the tensor
product of the factor algebras modulo their Jacobson radicals.
-/
alias _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.quotientTensorProductIdealAux3AlgEquiv := _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.quotientTensorProductJacobsonIdealAlgEquiv

/-- A third auxiliary ideal of a tensor-product algebra. -/
alias _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductIdeal_aux3 := _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductJacobsonIdeal

/--
The third auxiliary tensor-product ideal is the kernel of the map to the tensor product of the
Jacobson-radical quotients.
-/
alias _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductIdeal_aux3_eq_ker := _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductJacobsonIdeal_eq_ker

/--
The third auxiliary ideal of the tensor product is nilpotent when both factors are
finite-dimensional.
-/
alias _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductIdeal_aux3_isNilpotent := _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductJacobsonIdeal_isNilpotent

/-- The third auxiliary ideal of the tensor product is two-sided. -/
alias _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductIdeal_aux3_isTwoSided := _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductJacobsonIdeal_isTwoSided

/--
For finite-dimensional factor algebras, the third auxiliary tensor-product ideal is contained in
the Jacobson radical of the tensor product.
-/
alias _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductIdeal_aux3_le_jacobson := _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductJacobsonIdeal_le_jacobson

attribute [source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := primary)] _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.jacobson_le_tensorProductIdeal_aux3_of_isSemisimpleRing

attribute [source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := primary)] _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.jacobson_tensorProduct_actionRange_eq_aux3

attribute [source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := primary)] _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.jacobson_tensorProduct_eq_aux3

attribute [source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := supporting)] _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.quotientTensorProductIdealAux3AlgEquiv

attribute [source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := supporting)] _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductIdeal_aux3_eq_ker

attribute [source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := supporting)] _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductIdeal_aux3_isNilpotent

attribute [source_ref "Chapter3/Discussion_proof_of_Theorem3.10.2" (role := supporting)] _root_.RepresentationTheory.RingTheory.JacobsonRadical.TensorProduct.tensorProductIdeal_aux3_le_jacobson
