/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENCE.
Authors: mathlib-initiative
-/

import Mathlib
import RepresentationTheory.LinearAlgebra.ModuleDecompositions
import RepresentationTheory.Alignment.Attribute

namespace RepresentationTheory.Algebra.DualModules

/-- The dual of an algebra over its base ring, equipped with the module action induced by right multiplication in the algebra. -/
@[source_ref "Chapter2/Problem2.5.2" (role := supporting)]
def RightAlgebraDual (k A : Type*) [CommRing k] [Ring A] [Algebra k A] : Type _ := Module.Dual k A

namespace RightAlgebraDual

variable {k A : Type*} [CommRing k] [Ring A] [Algebra k A]

/-- The additive commutative group structure on the right algebra dual. -/
instance instAddCommGroup : AddCommGroup (RightAlgebraDual k A) := inferInstanceAs (AddCommGroup (Module.Dual k A))

/-- The base-ring module structure on the right algebra dual. -/
instance instModuleBase : Module k (RightAlgebraDual k A) := inferInstanceAs (Module k (Module.Dual k A))

/-- The linear equivalence from the right algebra dual to the ordinary module dual. -/
def toModuleDual : RightAlgebraDual k A ≃ₗ[k] Module.Dual k A := LinearEquiv.refl k _

/-- Two elements of the right algebra dual are equal when their associated functionals agree on every algebra element. -/
@[ext]
theorem ext {f g : RightAlgebraDual k A} (h : ∀ a, toModuleDual f a = toModuleDual g a) : f = g :=
  toModuleDual.injective (LinearMap.ext h)

/-- The scalar action of the algebra on its right dual. -/
instance instSMulAlgebra : SMul A (RightAlgebraDual k A) where
  smul a f := toModuleDual.symm ((toModuleDual f).comp (LinearMap.mulRight k a))

/-- The algebra action on the right dual evaluates by right multiplication of the argument. -/
@[source_ref "Chapter2/Problem2.5.2" (role := primary), simp]
theorem toModuleDual_algebra_smul_apply (a : A) (f : RightAlgebraDual k A) (b : A) :
    toModuleDual (a • f) b = toModuleDual f (b * a) := rfl

/-- The functional associated with a sum evaluates as the sum of the evaluations. -/
@[simp]
theorem toModuleDual_add_apply (f g : RightAlgebraDual k A) (b : A) :
    toModuleDual (f + g) b = toModuleDual f b + toModuleDual g b := rfl

/-- The zero element of the right dual evaluates to zero. -/
@[simp]
theorem toModuleDual_zero_apply (b : A) : toModuleDual (0 : RightAlgebraDual k A) b = 0 := rfl

/-- The functional associated with a base scalar multiple evaluates as the corresponding scalar multiple. -/
@[simp]
theorem toModuleDual_smul_apply (c : k) (f : RightAlgebraDual k A) (b : A) :
    toModuleDual (c • f) b = c • toModuleDual f b := rfl

/-- The algebra module structure on the right algebra dual. -/
instance instModuleAlgebra : Module A (RightAlgebraDual k A) where
  one_smul f := by ext b; simp
  mul_smul a a' f := by ext b; simp [mul_assoc]
  smul_zero a := by ext b; simp
  smul_add a f g := by ext b; simp
  add_smul a a' f := by ext b; simp [mul_add]
  zero_smul f := by ext b; simp

/-- The base-ring, algebra, and right-dual scalar actions form a scalar tower. -/
instance instIsScalarTower : IsScalarTower k A (RightAlgebraDual k A) where
  smul_assoc c a f := by
    ext b
    rw [toModuleDual_smul_apply, toModuleDual_algebra_smul_apply, toModuleDual_algebra_smul_apply, mul_smul_comm, map_smul]

/-- The base-ring and algebra scalar actions on the right dual commute. -/
instance instSMulCommClass : SMulCommClass k A (RightAlgebraDual k A) where
  smul_comm c a f := by ext b; simp

/-- An algebra submodule of the right dual is closed under scalar multiplication by the base ring. -/
theorem smul_mem {W : Submodule A (RightAlgebraDual k A)} (c : k) {w : RightAlgebraDual k A}
    (hw : w ∈ W) : c • w ∈ W := by
  rw [← algebraMap_smul A c w]
  exact W.smul_mem _ hw

end RightAlgebraDual

end RepresentationTheory.Algebra.DualModules

namespace RepresentationTheory.Algebra.DualModules

section PartsAB

variable {A : Type*} [Ring A]

/-- The proposition that a vector generates its module. -/
@[source_ref "Chapter2/Problem2.5.2" (role := supporting)]
def IsCyclicVector {V : Type*} [AddCommGroup V] [Module A V] (v : V) : Prop :=
  Submodule.span A {v} = ⊤

/-- The proposition that a module is generated by a single vector. -/
@[source_ref "Chapter2/Problem2.5.2" (role := supporting)]
def IsCyclicModule (V : Type*) [AddCommGroup V] [Module A V] : Prop :=
  ∃ v : V, IsCyclicVector (A := A) v

/-- A nontrivial module is simple if and only if every nonzero vector is cyclic. -/
@[source_ref "Chapter2/Problem2.5.2" (role := primary)]
theorem isSimpleModule_iff_forall_ne_zero_isCyclicVector (V : Type*) [AddCommGroup V] [Module A V] [Nontrivial V] :
    IsSimpleModule A V ↔ ∀ v : V, v ≠ 0 → IsCyclicVector (A := A) v := by
  change IsSimpleModule A V ↔ ∀ v : V, v ≠ 0 → Submodule.span A {v} = ⊤
  constructor
  ·
    intro h v hv
    rcases h.eq_bot_or_eq_top (Submodule.span A {v}) with hbot | htop
    · exfalso
      have hmem : v ∈ Submodule.span A {v} := Submodule.mem_span_singleton_self v
      rw [hbot, Submodule.mem_bot] at hmem
      exact hv hmem
    · exact htop
  ·
    intro h
    exact
      { eq_bot_or_eq_top := fun p => by
          rcases eq_or_ne p ⊥ with hp | hp
          · exact Or.inl hp
          · refine Or.inr ?_
            obtain ⟨v, hvp, hv0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hp
            have hspan : Submodule.span A {v} = ⊤ := h v hv0
            have hle : Submodule.span A {v} ≤ p :=
              Submodule.span_le.mpr (Set.singleton_subset_iff.mpr hvp)
            rw [hspan] at hle
            exact top_le_iff.mp hle }

/-- For a nontrivial module, cyclicity is equivalent to the existence of a linear equivalence with a quotient of its coefficient ring by an ideal. -/
@[source_ref "Chapter2/Problem2.5.2" (role := supporting)]
theorem isCyclicModule_iff_nonempty_linearEquiv_quotient (V : Type*) [AddCommGroup V] [Module A V] [Nontrivial V] :
    IsCyclicModule (A := A) V ↔
      ∃ I : Submodule A A, Nonempty (V ≃ₗ[A] (A ⧸ I)) := by
  change (∃ v : V, Submodule.span A {v} = ⊤) ↔
    ∃ I : Submodule A A, Nonempty (V ≃ₗ[A] (A ⧸ I))
  constructor
  ·
    rintro ⟨v, hv⟩
    set f := LinearMap.toSpanSingleton A V v with hf
    have hrange : LinearMap.range f = ⊤ := by
      rw [hf, ← LinearMap.span_singleton_eq_range]; exact hv
    have hsurj : Function.Surjective f := LinearMap.range_eq_top.mp hrange
    exact ⟨LinearMap.ker f, ⟨(LinearMap.quotKerEquivOfSurjective f hsurj).symm⟩⟩
  ·
    rintro ⟨I, ⟨e⟩⟩
    have h1 : Submodule.span A {(I.mkQ 1 : A ⧸ I)} = ⊤ := by
      rw [eq_top_iff]
      intro x _
      obtain ⟨a, rfl⟩ := I.mkQ_surjective x
      rw [Submodule.mem_span_singleton]
      refine ⟨a, ?_⟩
      rw [← map_smul]; congr 1; simp
    refine ⟨e.symm (I.mkQ 1), ?_⟩
    have hmap : Submodule.span A {e.symm (I.mkQ 1)}
        = Submodule.map e.symm.toLinearMap (Submodule.span A {I.mkQ 1}) := by
      rw [Submodule.map_span]; simp
    rw [hmap, h1, Submodule.map_top]
    exact LinearMap.range_eq_top.mpr e.symm.surjective

end PartsAB

open TrivSqZeroExt MvPolynomial

/-- The complex square-zero extension algebra with a two-dimensional nilpotent summand. -/
abbrev SquareZeroPlaneAlgebra : Type := TrivSqZeroExt ℂ (Fin 2 → ℂ)

/-- The first distinguished nilpotent element of the square-zero plane algebra. -/
noncomputable def firstNilpotent : SquareZeroPlaneAlgebra := inr (Pi.single 0 1)

/-- The second distinguished nilpotent element of the square-zero plane algebra. -/
noncomputable def secondNilpotent : SquareZeroPlaneAlgebra := inr (Pi.single 1 1)

/-- The square of the first distinguished nilpotent element is zero. -/
@[simp] theorem firstNilpotent_sq : firstNilpotent * firstNilpotent = 0 := by simp [firstNilpotent, inr_mul_inr]

/-- The product of the first and second distinguished nilpotent elements is zero. -/
@[simp] theorem firstNilpotent_mul_secondNilpotent : firstNilpotent * secondNilpotent = 0 := by simp [firstNilpotent, secondNilpotent, inr_mul_inr]

/-- The product of the second and first distinguished nilpotent elements is zero. -/
@[simp] theorem secondNilpotent_mul_firstNilpotent : secondNilpotent * firstNilpotent = 0 := by simp [firstNilpotent, secondNilpotent, inr_mul_inr]

/-- The square of the second distinguished nilpotent element is zero. -/
@[simp] theorem secondNilpotent_sq : secondNilpotent * secondNilpotent = 0 := by simp [secondNilpotent, inr_mul_inr]

/-- A complex-linear equivalence from the square-zero plane algebra to the product of its scalar and two-dimensional nilpotent parts. -/

noncomputable def squareZeroPlaneLinearEquivProd : SquareZeroPlaneAlgebra ≃ₗ[ℂ] ℂ × (Fin 2 → ℂ) where
  toFun a := (a.fst, a.snd)
  invFun p := (p.1, p.2)
  left_inv _ := rfl
  right_inv _ := rfl
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- The square-zero plane algebra is finite as a complex module. -/
instance squareZeroPlaneAlgebra_moduleFinite : Module.Finite ℂ SquareZeroPlaneAlgebra := Module.Finite.equiv squareZeroPlaneLinearEquivProd.symm

/-- The square-zero plane algebra has complex finrank three. -/
theorem finrank_squareZeroPlaneAlgebra : Module.finrank ℂ SquareZeroPlaneAlgebra = 3 := by
  rw [squareZeroPlaneLinearEquivProd.finrank_eq]; simp

/-- One and the two nilpotent basis elements are linearly independent over the complex numbers. -/
theorem linearIndependent_one_firstNilpotent_secondNilpotent : LinearIndependent ℂ ![(1 : SquareZeroPlaneAlgebra), firstNilpotent, secondNilpotent] := by
  rw [Fintype.linearIndependent_iff]
  intro g hg i
  rw [Fin.sum_univ_three] at hg
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two,
    Matrix.tail_cons, firstNilpotent, secondNilpotent] at hg
  rw [TrivSqZeroExt.ext_iff] at hg
  obtain ⟨h1, h2⟩ := hg
  simp only [Fin.isValue, fst_add, fst_smul, fst_one, smul_eq_mul, mul_one, fst_inr,
    mul_zero, add_zero, fst_zero] at h1
  have e0 := congrFun h2 0
  have e1 := congrFun h2 1
  simp only [Fin.isValue, snd_add, snd_smul, snd_one, smul_zero, snd_inr, zero_add,
    Pi.add_apply, Pi.smul_apply, Pi.single_eq_same, smul_eq_mul, mul_one, ne_eq, zero_ne_one,
    not_false_eq_true, Pi.single_eq_of_ne, mul_zero, add_zero, snd_zero, Pi.zero_apply,
    one_ne_zero] at e0 e1
  fin_cases i
  · exact h1
  · exact e0
  · exact e1

/-- The complex basis of the square-zero plane algebra indexed by `Fin 3`. -/
@[source_ref "Chapter2/Problem2.5.2" (role := supporting)]
noncomputable def squareZeroPlaneBasis : Module.Basis (Fin 3) ℂ SquareZeroPlaneAlgebra :=
  basisOfLinearIndependentOfCardEqFinrank linearIndependent_one_firstNilpotent_secondNilpotent (by simp [finrank_squareZeroPlaneAlgebra])

/-- The square-zero plane basis consists of one followed by the two nilpotent basis elements. -/
@[simp] theorem squareZeroPlaneBasis_eq : ⇑squareZeroPlaneBasis = ![(1 : SquareZeroPlaneAlgebra), firstNilpotent, secondNilpotent] :=
  coe_basisOfLinearIndependentOfCardEqFinrank _ _

/-- The ideal of two-variable complex polynomials generated by terms of total degree at least two. -/
noncomputable def degreeAtLeastTwoIdeal : Ideal (MvPolynomial (Fin 2) ℂ) :=
  Ideal.span (Set.range fun p : Fin 2 × Fin 2 => X p.1 * X p.2)

/-- The ideal generated by terms of degree at least two is the square of the ideal generated by the variables. -/
theorem degreeAtLeastTwoIdeal_eq_square :
    degreeAtLeastTwoIdeal = MvPolynomial.idealOfVars (Fin 2) ℂ ^ 2 := by
  rw [degreeAtLeastTwoIdeal, pow_two, MvPolynomial.idealOfVars, Ideal.span_mul_span']
  congr 1
  ext p
  simp [Set.mem_mul]

/-- The degree-at-least-two ideal is spanned by homogeneous polynomials of degree at least two. -/
@[source_ref "Chapter2/Problem2.5.2" (role := primary)]
theorem degreeAtLeastTwoIdeal_eq_span_homogeneous :
    degreeAtLeastTwoIdeal = Ideal.span {p : MvPolynomial (Fin 2) ℂ |
      ∃ d : ℕ, 2 ≤ d ∧ p.IsHomogeneous d} := by
  apply le_antisymm
  · rw [degreeAtLeastTwoIdeal, Ideal.span_le]
    rintro _ ⟨⟨i, j⟩, rfl⟩
    apply Ideal.subset_span
    exact ⟨2, le_rfl, by simpa using (isHomogeneous_X ℂ i).mul (isHomogeneous_X ℂ j)⟩
  · rw [Ideal.span_le]
    rintro p ⟨d, hd, hp⟩
    rw [degreeAtLeastTwoIdeal_eq_square]
    apply (MvPolynomial.mem_pow_idealOfVars_iff 2 p).2
    intro s hs
    have hsd : Finsupp.degree s = d := by
      simpa [MvPolynomial.IsHomogeneous, Finsupp.degree_eq_weight_one, Pi.one_def] using
        hp (MvPolynomial.mem_support_iff.mp hs)
    exact hsd.symm ▸ hd

/-- The image in the quotient of a product of two polynomial variables is zero. -/
theorem quotient_mk_variable_mul_variable (i j : Fin 2) :
    (Ideal.Quotient.mk degreeAtLeastTwoIdeal (X i * X j) : MvPolynomial (Fin 2) ℂ ⧸ degreeAtLeastTwoIdeal) = 0 :=
  Ideal.Quotient.eq_zero_iff_mem.2 <| Ideal.subset_span ⟨(i, j), rfl⟩

/-- The linear map sending a pair of coefficients to the corresponding linear polynomial class in the quotient. -/
noncomputable def linearTermMap : (Fin 2 → ℂ) →ₗ[ℂ] MvPolynomial (Fin 2) ℂ ⧸ degreeAtLeastTwoIdeal :=
  ∑ i : Fin 2, (LinearMap.proj i : (Fin 2 → ℂ) →ₗ[ℂ] ℂ).smulRight
    (Ideal.Quotient.mk degreeAtLeastTwoIdeal (X i) : MvPolynomial (Fin 2) ℂ ⧸ degreeAtLeastTwoIdeal)

/-- The linear-term map is the sum of the variable classes weighted by their coefficients. -/
theorem linearTermMap_apply (m : Fin 2 → ℂ) :
    linearTermMap m = ∑ i : Fin 2, m i • (Ideal.Quotient.mk degreeAtLeastTwoIdeal (X i) : MvPolynomial (Fin 2) ℂ ⧸ degreeAtLeastTwoIdeal) := by
  simp [linearTermMap]

/-- The product of any two values of the linear-term map is zero. -/
theorem linearTermMap_mul_linearTermMap (m n : Fin 2 → ℂ) : linearTermMap m * linearTermMap n = 0 := by
  simp only [linearTermMap_apply, Finset.sum_mul, Finset.mul_sum, smul_mul_smul_comm,
    ← map_mul, quotient_mk_variable_mul_variable, smul_zero, Finset.sum_const_zero]

/-- An algebra homomorphism from the square-zero plane algebra to the polynomial quotient. -/
noncomputable def squareZeroPlaneToQuotient : SquareZeroPlaneAlgebra →ₐ[ℂ] MvPolynomial (Fin 2) ℂ ⧸ degreeAtLeastTwoIdeal :=
  TrivSqZeroExt.liftEquivOfComm ⟨linearTermMap, linearTermMap_mul_linearTermMap⟩

/-- An algebra homomorphism from the polynomial quotient to the square-zero plane algebra. -/
noncomputable def quotientToSquareZeroPlane : (MvPolynomial (Fin 2) ℂ ⧸ degreeAtLeastTwoIdeal) →ₐ[ℂ] SquareZeroPlaneAlgebra :=
  Ideal.Quotient.liftₐ degreeAtLeastTwoIdeal (aeval fun i => (inr (Pi.single i 1) : SquareZeroPlaneAlgebra)) (by
    intro p hp
    refine Submodule.span_induction ?_ (by simp) (by intros; simp_all) (by intros; simp_all) hp
    rintro _ ⟨⟨i, j⟩, rfl⟩
    simp [inr_mul_inr])

/-- The nilpotent summand maps to the corresponding linear polynomial class in the quotient. -/
@[simp] theorem squareZeroPlaneToQuotient_inr (m : Fin 2 → ℂ) : squareZeroPlaneToQuotient (inr m) = linearTermMap m := by
  simp [squareZeroPlaneToQuotient]

/-- A polynomial variable class maps to the corresponding coordinate vector in the nilpotent summand. -/
@[simp] theorem quotientToSquareZeroPlane_variable (i : Fin 2) :
    quotientToSquareZeroPlane (Ideal.Quotient.mk degreeAtLeastTwoIdeal (X i)) = (inr (Pi.single i 1) : SquareZeroPlaneAlgebra) := by
  simp [quotientToSquareZeroPlane]

/-- The composite from the square-zero plane algebra to the quotient and back is the identity. -/
theorem quotientToSquareZeroPlane_comp_squareZeroPlaneToQuotient : quotientToSquareZeroPlane.comp squareZeroPlaneToQuotient = AlgHom.id ℂ SquareZeroPlaneAlgebra := by
  apply TrivSqZeroExt.algHom_ext
  intro m
  rw [AlgHom.comp_apply, squareZeroPlaneToQuotient_inr, linearTermMap_apply, map_sum]
  simp only [map_smul, quotientToSquareZeroPlane_variable, ← inr_smul, ← inr_sum, AlgHom.id_apply]
  congr 1
  funext i
  fin_cases i <;> simp [Fin.sum_univ_two]

/-- The composite from the polynomial quotient to the square-zero plane algebra and back is the identity. -/
theorem squareZeroPlaneToQuotient_comp_quotientToSquareZeroPlane :
    squareZeroPlaneToQuotient.comp quotientToSquareZeroPlane = AlgHom.id ℂ (MvPolynomial (Fin 2) ℂ ⧸ degreeAtLeastTwoIdeal) := by
  apply Ideal.Quotient.algHom_ext
  apply MvPolynomial.algHom_ext
  intro i
  simp [squareZeroPlaneToQuotient, quotientToSquareZeroPlane, linearTermMap_apply]

/-- An algebra equivalence between the square-zero plane algebra and the quotient by the degree-at-least-two ideal. -/
@[source_ref "Chapter2/Problem2.5.2" (role := primary)]
noncomputable def squareZeroPlaneAlgEquivQuotient : SquareZeroPlaneAlgebra ≃ₐ[ℂ] MvPolynomial (Fin 2) ℂ ⧸ degreeAtLeastTwoIdeal :=
  AlgEquiv.ofAlgHom squareZeroPlaneToQuotient quotientToSquareZeroPlane squareZeroPlaneToQuotient_comp_quotientToSquareZeroPlane quotientToSquareZeroPlane_comp_squareZeroPlaneToQuotient

/-- The first nilpotent basis element corresponds to the image of the first polynomial variable in the quotient. -/
@[simp] theorem squareZeroPlaneAlgEquivQuotient_firstNilpotent : squareZeroPlaneAlgEquivQuotient firstNilpotent = Ideal.Quotient.mk degreeAtLeastTwoIdeal (X 0) := by
  simp [squareZeroPlaneAlgEquivQuotient, firstNilpotent, linearTermMap_apply]

/-- The second nilpotent basis element corresponds to the image of the second polynomial variable in the quotient. -/
@[simp] theorem squareZeroPlaneAlgEquivQuotient_secondNilpotent : squareZeroPlaneAlgEquivQuotient secondNilpotent = Ideal.Quotient.mk degreeAtLeastTwoIdeal (X 1) := by
  simp [squareZeroPlaneAlgEquivQuotient, secondNilpotent, linearTermMap_apply]

/-- The right algebra dual of the square-zero plane algebra. -/
abbrev SquareZeroPlaneDual : Type := RightAlgebraDual ℂ SquareZeroPlaneAlgebra

/-- Multiplication in the square-zero plane algebra expands using the scalar parts and the nilpotent part of the right factor. -/
theorem mul_eq_fst_smul_add_fst_smul_inr (a b : SquareZeroPlaneAlgebra) : b * a = a.fst • b + b.fst • (inr a.snd : SquareZeroPlaneAlgebra) := by
  ext
  · simp [mul_comm]
  · simp [mul_comm, add_comm]

/-- The distinguished dual element that extracts the scalar part of the square-zero plane algebra. -/
noncomputable def scalarPartDual : SquareZeroPlaneDual :=
  RightAlgebraDual.toModuleDual.symm (TrivSqZeroExt.fstHom ℂ ℂ (Fin 2 → ℂ)).toLinearMap

/-- The scalar-part dual element evaluates an algebra element to its scalar component. -/
@[simp] theorem scalarPartDual_apply (a : SquareZeroPlaneAlgebra) : RightAlgebraDual.toModuleDual scalarPartDual a = a.fst := rfl

/-- The action of an algebra element on a dual functional is the sum of scalar-part scaling and evaluation on the nilpotent part times the scalar-part dual element. -/
theorem smul_dual_eq_fst_smul_add_eval_smul_scalarPartDual (a : SquareZeroPlaneAlgebra) (f : SquareZeroPlaneDual) :
    a • f = a.fst • f + (RightAlgebraDual.toModuleDual f (inr a.snd)) • scalarPartDual := by
  ext b
  rw [RightAlgebraDual.toModuleDual_algebra_smul_apply, mul_eq_fst_smul_add_fst_smul_inr]
  simp [mul_comm]

/-- The square-zero plane dual is finite as a complex module. -/
instance squareZeroPlaneDual_moduleFinite : Module.Finite ℂ SquareZeroPlaneDual := Module.Finite.equiv RightAlgebraDual.toModuleDual.symm

/-- The right dual of the square-zero plane algebra has complex finrank three. -/
theorem finrank_squareZeroPlaneDual : Module.finrank ℂ SquareZeroPlaneDual = 3 := by
  rw [RightAlgebraDual.toModuleDual.finrank_eq, Subspace.dual_finrank_eq, finrank_squareZeroPlaneAlgebra]

/-- The scalar-part dual element is nonzero. -/
theorem scalarPartDual_ne_zero : scalarPartDual ≠ (0 : SquareZeroPlaneDual) := by
  intro h
  have h1 : RightAlgebraDual.toModuleDual scalarPartDual (1 : SquareZeroPlaneAlgebra) = 0 := by rw [h]; rfl
  rw [scalarPartDual_apply] at h1
  simp at h1

/-- The square-zero plane dual is nontrivial. -/
instance squareZeroPlaneDual_nontrivial : Nontrivial SquareZeroPlaneDual := ⟨⟨scalarPartDual, 0, scalarPartDual_ne_zero⟩⟩

/-- An auxiliary linear map from a pair of complex scalars into the square-zero plane dual, parameterized by a dual element. -/
noncomputable def auxiliarySpanRangeMap (f : SquareZeroPlaneDual) : (ℂ × ℂ) →ₗ[ℂ] SquareZeroPlaneDual :=
  (LinearMap.fst ℂ ℂ ℂ).smulRight f + (LinearMap.snd ℂ ℂ ℂ).smulRight scalarPartDual

/-- The cyclic span of a dual element is contained in the range of its associated auxiliary linear map. -/
theorem span_singleton_le_range_auxiliarySpanRangeMap (f : SquareZeroPlaneDual) :
    (Submodule.span SquareZeroPlaneAlgebra {f} : Set SquareZeroPlaneDual) ⊆ LinearMap.range (auxiliarySpanRangeMap f) := by
  intro g hg
  rw [SetLike.mem_coe, Submodule.mem_span_singleton] at hg
  obtain ⟨a, rfl⟩ := hg
  exact ⟨(a.fst, RightAlgebraDual.toModuleDual f (inr a.snd)), by simp [auxiliarySpanRangeMap, smul_dual_eq_fst_smul_add_eval_smul_scalarPartDual]⟩

/-- No singleton spans the square-zero plane dual as a module over the square-zero plane algebra. -/
theorem span_singleton_ne_top_squareZeroPlaneDual (f : SquareZeroPlaneDual) : Submodule.span SquareZeroPlaneAlgebra {f} ≠ ⊤ := by
  intro h
  have hrange : LinearMap.range (auxiliarySpanRangeMap f) = ⊤ := by
    rw [eq_top_iff]
    intro g _
    exact span_singleton_le_range_auxiliarySpanRangeMap f (by rw [h]; trivial)
  have h1 : Module.finrank ℂ SquareZeroPlaneDual ≤ 2 := by
    have h2 := LinearMap.finrank_range_le (auxiliarySpanRangeMap f)
    rw [hrange, finrank_top] at h2
    simpa using h2
  rw [finrank_squareZeroPlaneDual] at h1
  omega

/-- The square-zero plane dual is not a cyclic module over the square-zero plane algebra. -/
theorem not_isCyclicModule_squareZeroPlaneDual : ¬ IsCyclicModule (A := SquareZeroPlaneAlgebra) SquareZeroPlaneDual := by
  rw [IsCyclicModule]
  rintro ⟨f, hf⟩
  exact span_singleton_ne_top_squareZeroPlaneDual f hf

/-- A dual functional that vanishes on the nilpotent summand is its value at one times the scalar-part dual element. -/
theorem eq_smul_scalarPartDual_of_vanishes_nilpotent {g : SquareZeroPlaneDual} (hm : ∀ m : Fin 2 → ℂ, RightAlgebraDual.toModuleDual g (inr m) = 0) :
    g = (RightAlgebraDual.toModuleDual g 1) • scalarPartDual := by
  ext b
  conv_lhs => rw [← inl_fst_add_inr_snd_eq b]
  rw [map_add, hm, add_zero, ← algebraMap_eq_inl, Algebra.algebraMap_eq_smul_one, map_smul]
  simp [mul_comm]

/-- Every nonzero submodule of the square-zero plane dual contains the scalar-part dual element. -/
theorem scalarPartDual_mem_of_ne_bot {W : Submodule SquareZeroPlaneAlgebra SquareZeroPlaneDual} (hW : W ≠ ⊥) : scalarPartDual ∈ W := by
  obtain ⟨g, hgW, hg0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hW
  by_cases hm : ∀ m : Fin 2 → ℂ, RightAlgebraDual.toModuleDual g (inr m) = 0
  · set c := RightAlgebraDual.toModuleDual g 1 with hc_def
    have hg : g = c • scalarPartDual := eq_smul_scalarPartDual_of_vanishes_nilpotent hm
    have hc : c ≠ 0 := fun h0 => hg0 (by rw [hg, h0, zero_smul])
    have h3 : c⁻¹ • g ∈ W := RightAlgebraDual.smul_mem _ hgW
    rwa [hg, smul_smul, inv_mul_cancel₀ hc, one_smul] at h3
  · push Not at hm
    obtain ⟨m, hmne⟩ := hm
    set c := RightAlgebraDual.toModuleDual g (inr m) with hc_def
    have hmem : (inr m : SquareZeroPlaneAlgebra) • g ∈ W := W.smul_mem _ hgW
    rw [smul_dual_eq_fst_smul_add_eval_smul_scalarPartDual] at hmem
    simp only [fst_inr, snd_inr, zero_smul, zero_add, ← hc_def] at hmem
    have h3 : c⁻¹ • (c • scalarPartDual) ∈ W := RightAlgebraDual.smul_mem _ hmem
    rwa [smul_smul, inv_mul_cancel₀ hmne, one_smul] at h3

/-- The square-zero plane dual satisfies the displayed auxiliary module property. -/
theorem auxiliaryModuleProperty_squareZeroPlaneDual : _root_.RepresentationTheory.LinearAlgebra.ModuleDecompositions.AuxiliaryDecompositionPredicate SquareZeroPlaneAlgebra SquareZeroPlaneDual := by
  refine ⟨inferInstance, fun W₁ W₂ hc => ?_⟩
  by_contra hcon
  push Not at hcon
  obtain ⟨h1, h2⟩ := hcon
  exact scalarPartDual_ne_zero
    (by simpa using hc.disjoint.le_bot (⟨scalarPartDual_mem_of_ne_bot h1, scalarPartDual_mem_of_ne_bot h2⟩ : scalarPartDual ∈ W₁ ⊓ W₂))

/-- The square-zero plane dual satisfies the displayed auxiliary module property but is not cyclic. -/
@[source_ref "Chapter2/Problem2.5.2" (role := supporting)]
theorem auxiliaryModuleProperty_and_not_isCyclicModule :
    _root_.RepresentationTheory.LinearAlgebra.ModuleDecompositions.AuxiliaryDecompositionPredicate SquareZeroPlaneAlgebra SquareZeroPlaneDual ∧ ¬ IsCyclicModule (A := SquareZeroPlaneAlgebra) SquareZeroPlaneDual :=
  ⟨auxiliaryModuleProperty_squareZeroPlaneDual, not_isCyclicModule_squareZeroPlaneDual⟩

example : Module.finrank ℂ SquareZeroPlaneDual = 3 := finrank_squareZeroPlaneDual

example : firstNilpotent ≠ secondNilpotent := by
  intro h
  have := congrFun (congrArg TrivSqZeroExt.snd h) 0
  simp [firstNilpotent, secondNilpotent] at this

example : ¬ IsSimpleModule SquareZeroPlaneAlgebra SquareZeroPlaneDual := by
  rw [isSimpleModule_iff_forall_ne_zero_isCyclicVector]
  push Not
  exact ⟨scalarPartDual, scalarPartDual_ne_zero, span_singleton_ne_top_squareZeroPlaneDual scalarPartDual⟩

end RepresentationTheory.Algebra.DualModules
