/-
Copyright (c) 2026 mathlib-initiative. All rights reserved.
Released under Apache 2.0 license as described in the file LICENCE.
Authors: mathlib-initiative
-/

import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.KrullDimension.Basic
import Mathlib.RingTheory.Jacobson.Semiprimary
import RepresentationTheory.Alignment.Attribute

/-!
# Matrix and truncated-polynomial simple modules

Develops simple modules and Jacobson radicals for truncated-polynomial and upper-triangular matrix algebras.
-/

open Polynomial

namespace RepresentationTheory.Algebra.SimpleModule.MatrixAndTruncatedPolynomial


section TruncatedPolynomial

variable (k : Type*) [Field k] (n : ℕ)


/-- For a positive exponent, an auxiliary algebra homomorphism from the corresponding adjoin-root algebra to the ground field. -/
noncomputable def adjoinRootAuxiliaryAlgHom (hn : 0 < n) : AdjoinRoot (X ^ n : k[X]) →ₐ[k] k :=
  AdjoinRoot.liftAlgHom _ (AlgHom.id k k) 0 (by simp [eval₂_pow, zero_pow hn.ne'])


/-- The auxiliary adjoin-root algebra homomorphism sends the adjoined root to zero. -/
@[simp]
theorem adjoinRootAuxiliaryAlgHom_root (hn : 0 < n) :
    adjoinRootAuxiliaryAlgHom k n hn (AdjoinRoot.root (X ^ n : k[X])) = 0 :=
  AdjoinRoot.liftAlgHom_root _ _ _ _


/-- The auxiliary adjoin-root algebra homomorphism applied to the image of a polynomial equals that polynomial evaluated at zero. -/
@[simp]
theorem adjoinRootAuxiliaryAlgHom_mk (hn : 0 < n) (p : k[X]) :
    adjoinRootAuxiliaryAlgHom k n hn (AdjoinRoot.mk (X ^ n : k[X]) p) = p.eval 0 := by
  simp [adjoinRootAuxiliaryAlgHom, eval₂_eq_eval_map]


/-- The auxiliary adjoin-root algebra homomorphism is surjective. -/
theorem adjoinRootAuxiliaryAlgHom_surjective (hn : 0 < n) :
    Function.Surjective (adjoinRootAuxiliaryAlgHom k n hn) := fun c =>
  ⟨AdjoinRoot.of _ c, by simp [adjoinRootAuxiliaryAlgHom]⟩


/-- The kernel of the auxiliary algebra homomorphism from the adjoin-root algebra is the ideal generated by the adjoined root. -/
theorem ker_adjoinRootAuxiliaryAlgHom (hn : 0 < n) :
    RingHom.ker (adjoinRootAuxiliaryAlgHom k n hn) =
      Ideal.span {AdjoinRoot.root (X ^ n : k[X])} := by
  apply le_antisymm
  · intro a ha
    obtain ⟨p, rfl⟩ := AdjoinRoot.mk_surjective a
    rw [RingHom.mem_ker, adjoinRootAuxiliaryAlgHom_mk] at ha
    obtain ⟨q, rfl⟩ := X_dvd_iff.mpr (by simpa [coeff_zero_eq_eval_zero] using ha)
    exact Ideal.mem_span_singleton.mpr ⟨AdjoinRoot.mk _ q, by
      rw [← AdjoinRoot.mk_X, ← map_mul]⟩
  · rw [Ideal.span_le]
    rintro _ rfl
    simp [RingHom.mem_ker]


/-- For a positive exponent, the ideal generated by the adjoined root of X raised to that exponent is maximal. -/
theorem span_root_isMaximal (hn : 0 < n) :
    (Ideal.span {AdjoinRoot.root (X ^ n : k[X])}).IsMaximal :=
  ker_adjoinRootAuxiliaryAlgHom k n hn ▸
    RingHom.ker_isMaximal_of_surjective _ (adjoinRootAuxiliaryAlgHom_surjective k n hn)


/-- For a positive exponent, the Jacobson radical of the corresponding adjoin-root algebra is the ideal generated by its adjoined root. -/
@[source_ref "Chapter3/Example3.5.6" (role := primary)]
theorem jacobson_eq_span_root (hn : 0 < n) :
    Ring.jacobson (AdjoinRoot (X ^ n : k[X])) =
      Ideal.span {AdjoinRoot.root (X ^ n : k[X])} := by
  set f := (X ^ n : k[X])
  set A := AdjoinRoot f
  set r := AdjoinRoot.root f
  
  have hr_nil : IsNilpotent r := ⟨n, by
    change (AdjoinRoot.mk f X) ^ n = 0
    rw [← map_pow, AdjoinRoot.mk_self]⟩
  have h_ge : Ideal.span {r} ≤ Ring.jacobson A := by
    rw [Ideal.span_le]
    intro x hx
    simp only [Set.mem_singleton_iff] at hx
    subst hx
    exact nilradical_le_jacobson A (mem_nilradical.mpr hr_nil)
  
  haveI : (Ideal.span {r}).IsMaximal := span_root_isMaximal k n hn
  exact le_antisymm (Ring.jacobson_le_of_isMaximal (Ideal.span {r})) h_ge




/-- An auxiliary type depending on a field and a natural number. -/
@[source_ref "Chapter3/Example3.5.6" (role := supporting)]
abbrev fieldNatAuxiliaryType : Type _ :=
  AdjoinRoot (X ^ n : k[X]) ⧸ Ideal.span {AdjoinRoot.root (X ^ n : k[X])}


/-- For a positive exponent, the field-and-natural-number auxiliary type is simple over the corresponding adjoin-root algebra. -/
@[source_ref "Chapter3/Example3.5.6" (role := supporting)]
theorem isSimpleModule_fieldNatAuxiliaryType (hn : 0 < n) :
    IsSimpleModule (AdjoinRoot (X ^ n : k[X])) (fieldNatAuxiliaryType k n) :=
  isSimpleModule_iff_isCoatom.mpr (Ideal.isMaximal_def.mp (span_root_isMaximal k n hn))


/-- The adjoined root acts as zero on the field-and-natural-number auxiliary type. -/
@[source_ref "Chapter3/Example3.5.6" (role := supporting)]
theorem root_smul_fieldNatAuxiliaryType (m : fieldNatAuxiliaryType k n) :
    AdjoinRoot.root (X ^ n : k[X]) • m = 0 := by
  induction m using Submodule.Quotient.induction_on with
  | H a =>
    exact (Submodule.Quotient.mk_eq_zero _).mpr
      (Ideal.mul_mem_right a _ (Ideal.mem_span_singleton_self _))


/-- For a positive exponent, the field-and-natural-number auxiliary type is algebra-equivalent to the ground field. -/
noncomputable def fieldNatAuxiliaryTypeAlgEquiv (hn : 0 < n) : fieldNatAuxiliaryType k n ≃ₐ[k] k :=
  (Ideal.quotientEquivAlgOfEq k (ker_adjoinRootAuxiliaryAlgHom k n hn).symm).trans
    (Ideal.quotientKerAlgEquivOfSurjective (adjoinRootAuxiliaryAlgHom_surjective k n hn))


/-- For a positive natural-number parameter, the corresponding field-indexed auxiliary type has dimension one over the ground field. -/
@[source_ref "Chapter3/Example3.5.6" (role := supporting)]
theorem finrank_fieldNatAuxiliaryType (hn : 0 < n) :
    Module.finrank k (fieldNatAuxiliaryType k n) = 1 := by
  rw [(fieldNatAuxiliaryTypeAlgEquiv k n hn).toLinearEquiv.finrank_eq, Module.finrank_self]


/-- For a positive exponent, every simple module over the corresponding adjoin-root algebra is linearly equivalent to the field-and-natural-number auxiliary type. -/
@[source_ref "Chapter3/Example3.5.6" (role := supporting)]
theorem nonempty_equiv_fieldNatAuxiliaryType (hn : 0 < n) (M : Type*) [AddCommGroup M]
    [Module (AdjoinRoot (X ^ n : k[X])) M] [IsSimpleModule (AdjoinRoot (X ^ n : k[X])) M] :
    Nonempty (M ≃ₗ[AdjoinRoot (X ^ n : k[X])] fieldNatAuxiliaryType k n) := by
  obtain ⟨I, hI, ⟨e⟩⟩ := isSimpleModule_iff_quot_maximal.mp ‹_›
  haveI := hI
  have hle : Ideal.span {AdjoinRoot.root (X ^ n : k[X])} ≤ I := by
    rw [← jacobson_eq_span_root k n hn]
    exact Ring.jacobson_le_of_isMaximal I
  exact ⟨e.trans (Submodule.quotEquivOfEq _ _
    ((span_root_isMaximal k n hn).eq_of_le hI.ne_top hle).symm)⟩

end TruncatedPolynomial

section UpperTriangular


/-- An auxiliary subalgebra of square matrices over a field, parameterized by their finite index size. -/
def auxiliaryMatrixSubalgebra (k : Type*) [Field k] (n : ℕ) :
    Subalgebra k (Matrix (Fin n) (Fin n) k) where
  carrier := {M | ∀ i j, j < i → M i j = 0}
  mul_mem' {a b} ha hb i j hij := by
    simp only [Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro l _
    by_cases hlj : l < i
    · simp [ha i l hlj]
    · push Not at hlj
      simp [hb l j (lt_of_lt_of_le hij hlj)]
  one_mem' i j hij := by
    rw [Matrix.one_apply, if_neg (ne_of_gt hij)]
  add_mem' {a b} ha hb i j hij := by simp [ha i j hij, hb i j hij]
  zero_mem' _ _ _ := by simp
  algebraMap_mem' r i j hij := by
    rw [Algebra.algebraMap_eq_smul_one, Matrix.smul_apply, Matrix.one_apply,
      if_neg (ne_of_gt hij), smul_zero]


/-- An auxiliary ideal of the auxiliary matrix subalgebra. -/
def auxiliaryIdeal (k : Type*) [Field k] (n : ℕ) :
    Ideal (↥(auxiliaryMatrixSubalgebra k n)) where
  carrier := {M | ∀ i j, j ≤ i → (M : Matrix (Fin n) (Fin n) k) i j = 0}
  add_mem' {a b} ha hb i j hij := by simp [ha i j hij, hb i j hij]
  zero_mem' _ _ _ := by simp
  smul_mem' c x hx i j hij := by
    have : (c • x).val = (c : Matrix (Fin n) (Fin n) k) * (x : Matrix (Fin n) (Fin n) k) := rfl
    rw [this, Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro l _
    by_cases hli : i ≤ l
    · simp [hx l j (le_trans hij hli)]
    · push Not at hli
      simp [c.2 i l hli]


/-- The auxiliary ideal is two-sided. -/
instance auxiliaryIdeal.isTwoSided (k : Type*) [Field k] (n : ℕ) :
    (auxiliaryIdeal k n).IsTwoSided where
  mul_mem_of_left b ha i j hij := by
    have hmul : ∀ (a b : ↥(auxiliaryMatrixSubalgebra k n)),
        (a * b).val = (a : Matrix (Fin n) (Fin n) k) * (b : Matrix (Fin n) (Fin n) k) :=
      fun _ _ => rfl
    rw [hmul]
    simp only [Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro l _
    by_cases hli : l ≤ i
    · simp [ha i l hli]
    · push Not at hli
      simp [b.2 l j (lt_of_le_of_lt hij hli)]


/-- An auxiliary algebra homomorphism from the matrix subalgebra to the ground field, associated with a finite index. -/
def indexedAuxiliaryAlgHom (k : Type*) [Field k] (n : ℕ) (i : Fin n) :
    auxiliaryMatrixSubalgebra k n →ₐ[k] k where
  toFun M := M.val i i
  map_one' := by simp
  map_mul' a b := by
    change (a.1 * b.1) i i = a.1 i i * b.1 i i
    simp only [Matrix.mul_apply]
    apply Finset.sum_eq_single i
    · intro l _ hli
      rcases lt_or_gt_of_ne hli with h | h
      · simp [a.2 i l h]
      · simp [b.2 l i h]
    · intro h; exact absurd (Finset.mem_univ i) h
  map_zero' := by simp
  map_add' a b := by simp
  commutes' c := by
    change (algebraMap k (Matrix (Fin n) (Fin n) k) c) i i = c
    simp [Matrix.algebraMap_matrix_apply]


/-- The indexed auxiliary algebra homomorphism evaluates an element at the corresponding diagonal position. -/
@[simp]
theorem indexedAuxiliaryAlgHom_apply (k : Type*) [Field k] (n : ℕ) (i : Fin n)
    (M : auxiliaryMatrixSubalgebra k n) :
    indexedAuxiliaryAlgHom k n i M = M.val i i := rfl


/-- Each indexed auxiliary algebra homomorphism is surjective. -/
theorem indexedAuxiliaryAlgHom_surjective (k : Type*) [Field k] (n : ℕ) (i : Fin n) :
    Function.Surjective (indexedAuxiliaryAlgHom k n i) := fun c =>
  ⟨algebraMap k _ c, (indexedAuxiliaryAlgHom k n i).commutes c⟩


/-- The Jacobson radical of the auxiliary matrix subalgebra is the auxiliary ideal. -/
@[source_ref "Chapter3/Example3.5.6" (role := primary)]
theorem jacobson_auxiliaryMatrixSubalgebra (k : Type*) [Field k] (n : ℕ) :
    Ring.jacobson (↥(auxiliaryMatrixSubalgebra k n)) =
      auxiliaryIdeal k n := by
  set S := auxiliaryMatrixSubalgebra k n
  set I := auxiliaryIdeal k n
  apply le_antisymm
  · 
    intro x hx
    change ∀ i j : Fin n, j ≤ i → (x : Matrix (Fin n) (Fin n) k) i j = 0
    intro i j hij
    rcases hij.eq_or_lt with rfl | hlt
    · 
      let π : ↥S →+* k := (indexedAuxiliaryAlgHom k n j).toRingHom
      haveI : (RingHom.ker π).IsMaximal :=
        RingHom.ker_isMaximal_of_surjective _ (indexedAuxiliaryAlgHom_surjective k n j)
      exact Ring.jacobson_le_of_isMaximal (RingHom.ker π) hx
    · 
      exact x.2 i j hlt
  · 
    
    have nil_of_mem : ∀ z : ↥S, z ∈ I → IsNilpotent z := by
      intro z hz
      refine ⟨n, Subtype.ext ?_⟩
      change ((z ^ n : ↥S) : Matrix (Fin n) (Fin n) k) = 0
      ext p q; simp only [Matrix.zero_apply]
      suffices ∀ (m : ℕ) (p q : Fin n), (q : ℕ) < (p : ℕ) + m →
          ((z ^ m : ↥S) : Matrix (Fin n) (Fin n) k) p q = 0 by
        exact this n p q (by omega)
      intro m; induction m with
      | zero =>
        intro p q h; simp only [pow_zero]
        change (1 : Matrix (Fin n) (Fin n) k) p q = 0
        rw [Matrix.one_apply, if_neg (Fin.ne_of_val_ne (by omega))]
      | succ m ih =>
        intro p q h
        have : ((z ^ (m + 1) : ↥S) : Matrix _ _ k) p q =
            ∑ l, ((z ^ m : ↥S) : Matrix _ _ k) p l * z.val l q := by
          change ((z ^ m).val * z.val) p q = _
          rw [Matrix.mul_apply]
        rw [this]
        apply Finset.sum_eq_zero; intro l _
        by_cases hl : (l : ℕ) < (p : ℕ) + m
        · simp [ih p l hl]
        · push Not at hl; simp [hz l q (show (q : ℕ) ≤ (l : ℕ) by omega)]
    
    rw [Ring.jacobson_eq_sInf_isMaximal]
    intro x hx
    simp only [Ideal.mem_sInf, Set.mem_setOf_eq]
    intro J hJ
    
    
    
    by_contra hxJ
    apply hJ.ne_top
    have hlt : J < J ⊔ Ideal.span {x} := by
      refine lt_of_le_of_ne le_sup_left fun heq => hxJ ?_
      exact heq ▸ SetLike.le_def.mp le_sup_right (Ideal.mem_span_singleton_self x)
    have htop := hJ.1.2 _ hlt
    rw [Ideal.eq_top_iff_one] at htop
    obtain ⟨a, ha, b, hb, hab⟩ := Submodule.mem_sup.mp htop
    obtain ⟨r, rfl⟩ := Ideal.mem_span_singleton'.mp hb
    have ha_eq : a = 1 - r * x := (eq_sub_iff_add_eq).mpr hab
    exact J.eq_top_of_isUnit_mem ha (ha_eq ▸ (nil_of_mem _ (I.smul_mem r hx)).isUnit_one_sub)



variable (k : Type*) [Field k] (n : ℕ)


/-- An auxiliary family of types indexed by the elements of a finite type. -/
@[source_ref "Chapter3/Example3.5.6" (role := supporting), nolint unusedArguments]
def finiteIndexAuxiliaryType (_i : Fin n) : Type _ := k

namespace finiteIndexAuxiliaryType

variable {k n}

/-- The additive commutative group structure on a finite-index auxiliary type. -/
instance instAddCommGroup (i : Fin n) : AddCommGroup (finiteIndexAuxiliaryType k n i) :=
  inferInstanceAs (AddCommGroup k)


/-- Each finite-index auxiliary type is nontrivial. -/
instance nontrivial (i : Fin n) : Nontrivial (finiteIndexAuxiliaryType k n i) :=
  inferInstanceAs (Nontrivial k)

/-- The scalar-module structure over the ground field on a finite-index auxiliary type. -/
instance instModuleField (i : Fin n) : Module k (finiteIndexAuxiliaryType k n i) :=
  inferInstanceAs (Module k k)

/-- The module structure over the auxiliary matrix subalgebra on a finite-index auxiliary type. -/
instance instModuleAuxiliaryMatrixSubalgebra (i : Fin n) : Module (auxiliaryMatrixSubalgebra k n) (finiteIndexAuxiliaryType k n i) :=
  Module.compHom (finiteIndexAuxiliaryType k n i) (indexedAuxiliaryAlgHom k n i).toRingHom


/-- Scalar multiplication by an element of the auxiliary matrix subalgebra is multiplication by its corresponding diagonal entry. -/
@[source_ref "Chapter3/Example3.5.6" (role := supporting)]
theorem smul_eq_diagonalEntry_mul (i : Fin n) (s : auxiliaryMatrixSubalgebra k n)
    (v : finiteIndexAuxiliaryType k n i) :
    s • v = (show k from s.val i i) * (show k from v) := rfl

end finiteIndexAuxiliaryType


/-- Every finite-index auxiliary type has dimension one over the ground field. -/
@[source_ref "Chapter3/Example3.5.6" (role := supporting)]
theorem finrank_finiteIndexAuxiliaryType (i : Fin n) :
    Module.finrank k (finiteIndexAuxiliaryType k n i) = 1 :=
  Module.finrank_self k


/-- Each finite-index auxiliary type is simple over the auxiliary matrix subalgebra. -/
@[source_ref "Chapter3/Example3.5.6" (role := supporting)]
theorem isSimpleModule_finiteIndexAuxiliaryType (i : Fin n) :
    IsSimpleModule (auxiliaryMatrixSubalgebra k n) (finiteIndexAuxiliaryType k n i) := by
  rw [isSimpleModule_iff_toSpanSingleton_surjective]
  refine ⟨inferInstance, fun x hx z => ?_⟩
  have hx' : (show k from x) ≠ 0 := hx
  obtain ⟨s, hs⟩ := indexedAuxiliaryAlgHom_surjective k n i ((show k from z) * (show k from x)⁻¹)
  refine ⟨s, ?_⟩
  change s • x = z
  rw [finiteIndexAuxiliaryType.smul_eq_diagonalEntry_mul]
  change s.val i i * (show k from x) = (show k from z)
  rw [show s.val i i = indexedAuxiliaryAlgHom k n i s from rfl, hs]
  field_simp


/-- An auxiliary element of the matrix subalgebra associated with a finite index. -/
def indexedAuxiliaryElement (i : Fin n) : auxiliaryMatrixSubalgebra k n :=
  ⟨Matrix.single i i 1, fun p q hpq => by
    rw [Matrix.single_apply, if_neg]
    rintro ⟨rfl, rfl⟩
    exact absurd hpq (lt_irrefl _)⟩


/-- The underlying matrix of an indexed auxiliary element is the corresponding diagonal single-entry matrix. -/
@[simp]
theorem coe_indexedAuxiliaryElement (i : Fin n) :
    (indexedAuxiliaryElement k n i).val = Matrix.single i i (1 : k) := rfl


/-- Applying an indexed auxiliary algebra homomorphism to an indexed auxiliary element gives one at matching indices and zero otherwise. -/
theorem indexedAuxiliaryAlgHom_indexedAuxiliaryElement (i j : Fin n) :
    indexedAuxiliaryAlgHom k n j (indexedAuxiliaryElement k n i) = if j = i then 1 else 0 := by
  rcases eq_or_ne j i with rfl | h
  · simp [indexedAuxiliaryAlgHom_apply]
  · simp [indexedAuxiliaryAlgHom_apply, h, Ne.symm h]


/-- Left multiplication of a matrix by a diagonal matrix unit retains the indexed row and vanishes on all other rows. -/
theorem diagonalMatrixUnit_mul_apply (i : Fin n) (T : Matrix (Fin n) (Fin n) k) (p q : Fin n) :
    (Matrix.single i i (1 : k) * T) p q = if p = i then T i q else 0 := by
  rcases eq_or_ne p i with rfl | hp
  · simp
  · simp [hp]


/-- Right multiplication of a matrix by a diagonal matrix unit retains the indexed column and vanishes on all other columns. -/
theorem mul_diagonalMatrixUnit_apply (i : Fin n) (T : Matrix (Fin n) (Fin n) k) (p q : Fin n) :
    (T * Matrix.single i i (1 : k)) p q = if q = i then T p i else 0 := by
  rcases eq_or_ne q i with rfl | hq
  · simp
  · simp [hq]


/-- Finite-index auxiliary types at distinct indices are not linearly equivalent over the auxiliary matrix subalgebra. -/
@[source_ref "Chapter3/Example3.5.6" (role := supporting)]
theorem not_nonempty_equiv_finiteIndexAuxiliaryType {i j : Fin n} (hij : i ≠ j) :
    ¬ Nonempty (finiteIndexAuxiliaryType k n i ≃ₗ[auxiliaryMatrixSubalgebra k n]
      finiteIndexAuxiliaryType k n j) := by
  rintro ⟨e⟩
  let one' : finiteIndexAuxiliaryType k n i := (1 : k)
  have hL : indexedAuxiliaryElement k n i • one' = one' := by
    rw [finiteIndexAuxiliaryType.smul_eq_diagonalEntry_mul]
    change Matrix.single i i (1 : k) i i * (1 : k) = (1 : k)
    simp
  have hR : indexedAuxiliaryElement k n i • e one' = 0 := by
    rw [finiteIndexAuxiliaryType.smul_eq_diagonalEntry_mul]
    change Matrix.single i i (1 : k) j j * (show k from e one') = 0
    simp [hij]
  have h0 : e one' = 0 := by rw [← hR, ← e.map_smul, hL]
  exact one_ne_zero (α := k) (e.injective (h0.trans (map_zero e).symm))


/-- The sum of all indexed auxiliary elements in the matrix subalgebra is one. -/
theorem sum_indexedAuxiliaryElement : ∑ i : Fin n, indexedAuxiliaryElement k n i = 1 := by
  refine Subtype.ext ?_
  have hval : ((∑ i : Fin n, indexedAuxiliaryElement k n i : auxiliaryMatrixSubalgebra k n) :
      Matrix (Fin n) (Fin n) k) = ∑ i : Fin n, Matrix.single i i (1 : k) := by
    push_cast [coe_indexedAuxiliaryElement]
    rfl
  rw [hval, show ((1 : auxiliaryMatrixSubalgebra k n) : Matrix (Fin n) (Fin n) k) = 1 from rfl]
  ext p q
  simp only [Matrix.sum_apply, Matrix.one_apply, Matrix.single_apply]
  rcases eq_or_ne p q with rfl | h
  · rw [if_pos rfl, Finset.sum_eq_single p]
    · simp
    · intro b _ hb; simp [hb]
    · intro hp; exact absurd (Finset.mem_univ p) hp
  · rw [if_neg h]
    exact Finset.sum_eq_zero fun b _ => if_neg (by rintro ⟨rfl, rfl⟩; exact h rfl)


/-- The commutator of an indexed auxiliary element with an element of the auxiliary matrix subalgebra belongs to the auxiliary ideal. -/
theorem commutator_indexedAuxiliaryElement_mem_auxiliaryIdeal (i : Fin n) (s : auxiliaryMatrixSubalgebra k n) :
    indexedAuxiliaryElement k n i * s - s * indexedAuxiliaryElement k n i ∈ auxiliaryIdeal k n := by
  intro p q hqp
  have hval : ((indexedAuxiliaryElement k n i * s - s * indexedAuxiliaryElement k n i : auxiliaryMatrixSubalgebra k n) :
      Matrix (Fin n) (Fin n) k) =
      Matrix.single i i (1 : k) * s.val - s.val * Matrix.single i i (1 : k) := rfl
  rw [hval, Matrix.sub_apply, diagonalMatrixUnit_mul_apply, mul_diagonalMatrixUnit_apply]
  split_ifs with hp hq hq'
  · rw [hp, hq, sub_self]
  · rw [s.2 i q (lt_of_le_of_ne (hp ▸ hqp) hq), sub_zero]
  · rw [s.2 p i (lt_of_le_of_ne (hq' ▸ hqp) (Ne.symm hp)), sub_zero]
  · rw [sub_zero]


/-- The product of the difference between an algebra element and the scalar obtained from its indexed auxiliary homomorphism with the associated indexed auxiliary element belongs to the auxiliary ideal. -/
theorem sub_indexedScalar_mul_indexedAuxiliaryElement_mem_auxiliaryIdeal (i : Fin n) (s : auxiliaryMatrixSubalgebra k n) :
    (s - algebraMap k _ (indexedAuxiliaryAlgHom k n i s)) * indexedAuxiliaryElement k n i ∈
      auxiliaryIdeal k n := by
  intro p q hqp
  have hval : (((s - algebraMap k _ (indexedAuxiliaryAlgHom k n i s)) * indexedAuxiliaryElement k n i :
      auxiliaryMatrixSubalgebra k n) : Matrix (Fin n) (Fin n) k) =
      (s.val - algebraMap k (Matrix (Fin n) (Fin n) k) (s.val i i)) *
        Matrix.single i i (1 : k) := rfl
  rw [hval, mul_diagonalMatrixUnit_apply]
  split_ifs with hq
  · rw [Matrix.sub_apply, Matrix.algebraMap_matrix_apply]
    by_cases hp : p = i
    · rw [if_pos hp, hp]; simp
    · rw [if_neg hp, s.2 p i (lt_of_le_of_ne (hq ▸ hqp) (Ne.symm hp)), sub_zero]
  · rfl

section Classification

variable {k n} (M : Type*) [AddCommGroup M] [Module (auxiliaryMatrixSubalgebra k n) M]
  [IsSimpleModule (auxiliaryMatrixSubalgebra k n) M]


/-- Every element of the auxiliary ideal acts as zero on every simple module over the auxiliary matrix subalgebra. -/
theorem auxiliaryIdeal_smul_eq_zero_of_isSimpleModule {z : auxiliaryMatrixSubalgebra k n}
    (hz : z ∈ auxiliaryIdeal k n) (m : M) : z • m = 0 := by
  have hle : Ring.jacobson (auxiliaryMatrixSubalgebra k n) ≤
      Module.annihilator (auxiliaryMatrixSubalgebra k n) M :=
    IsSemisimpleModule.jacobson_le_annihilator (auxiliaryMatrixSubalgebra k n) M
  exact Module.mem_annihilator.mp (hle (by rwa [jacobson_auxiliaryMatrixSubalgebra])) m


/-- Every simple module over the auxiliary matrix subalgebra is linearly equivalent to a finite-index auxiliary type at some index. -/
@[source_ref "Chapter3/Example3.5.6" (role := supporting)]
theorem exists_equiv_finiteIndexAuxiliaryType :
    ∃ i : Fin n, Nonempty (M ≃ₗ[auxiliaryMatrixSubalgebra k n] finiteIndexAuxiliaryType k n i) := by
  haveI : Nontrivial M := IsSimpleModule.nontrivial (auxiliaryMatrixSubalgebra k n) M
  obtain ⟨m₀, hm₀⟩ := exists_ne (0 : M)
  
  have hsum : ∑ i : Fin n, indexedAuxiliaryElement k n i • m₀ = m₀ := by
    rw [← Finset.sum_smul, sum_indexedAuxiliaryElement, one_smul]
  obtain ⟨i, -, hi⟩ : ∃ i ∈ Finset.univ, indexedAuxiliaryElement k n i • m₀ ≠ 0 := by
    by_contra h
    push Not at h
    exact hm₀ (by rw [← hsum, Finset.sum_eq_zero h])
  refine ⟨i, ?_⟩
  
  let φ : M →ₗ[auxiliaryMatrixSubalgebra k n] M :=
    { toFun := fun m => indexedAuxiliaryElement k n i • m
      map_add' := fun a b => smul_add _ _ _
      map_smul' := fun s m => by
        have h := auxiliaryIdeal_smul_eq_zero_of_isSimpleModule M (commutator_indexedAuxiliaryElement_mem_auxiliaryIdeal k n i s) m
        rw [sub_smul, sub_eq_zero, mul_smul, mul_smul] at h
        exact h }
  have hidem : indexedAuxiliaryElement k n i * indexedAuxiliaryElement k n i = indexedAuxiliaryElement k n i := by
    refine Subtype.ext ?_
    change Matrix.single i i (1 : k) * Matrix.single i i 1 = Matrix.single i i 1
    simp
  have hker : LinearMap.ker φ = ⊥ := by
    rcases eq_bot_or_eq_top (LinearMap.ker φ) with h | h
    · exact h
    · exact absurd (LinearMap.mem_ker.mp (h ▸ Submodule.mem_top : m₀ ∈ LinearMap.ker φ)) hi
  have hφid : ∀ m : M, indexedAuxiliaryElement k n i • m = m := fun m =>
    LinearMap.ker_eq_bot.mp hker (show φ (φ m) = φ m by
      change indexedAuxiliaryElement k n i • indexedAuxiliaryElement k n i • m = indexedAuxiliaryElement k n i • m
      rw [← mul_smul, hidem])
  
  have hact : ∀ (s : auxiliaryMatrixSubalgebra k n) (m : M),
      s • m = (algebraMap k (auxiliaryMatrixSubalgebra k n) (indexedAuxiliaryAlgHom k n i s)) • m := by
    intro s m
    have h := auxiliaryIdeal_smul_eq_zero_of_isSimpleModule M (sub_indexedScalar_mul_indexedAuxiliaryElement_mem_auxiliaryIdeal k n i s) m
    rw [sub_mul, sub_smul, sub_eq_zero, mul_smul, mul_smul, hφid] at h
    exact h
  
  let g : finiteIndexAuxiliaryType k n i →ₗ[auxiliaryMatrixSubalgebra k n] M :=
    { toFun := fun c => (algebraMap k (auxiliaryMatrixSubalgebra k n) (show k from c)) • m₀
      map_add' := fun a b => by
        change (algebraMap k _ ((show k from a) + (show k from b))) • m₀ = _
        rw [map_add, add_smul]
      map_smul' := fun s c => by
        change (algebraMap k _ (show k from s • c)) • m₀ =
          s • ((algebraMap k _ (show k from c)) • m₀)
        rw [finiteIndexAuxiliaryType.smul_eq_diagonalEntry_mul, map_mul, mul_smul]
        exact (hact s _).symm }
  let one' : finiteIndexAuxiliaryType k n i := (1 : k)
  have hg1 : g one' = m₀ := by
    change (algebraMap k (auxiliaryMatrixSubalgebra k n) (1 : k)) • m₀ = m₀
    rw [map_one, one_smul]
  haveI := isSimpleModule_finiteIndexAuxiliaryType k n i
  have hinj : Function.Injective g := by
    rcases eq_bot_or_eq_top (LinearMap.ker g) with h | h
    · exact LinearMap.ker_eq_bot.mp h
    · exact absurd (hg1 ▸ LinearMap.mem_ker.mp (h ▸ Submodule.mem_top : one' ∈ LinearMap.ker g))
        hm₀
  have hsurj : Function.Surjective g := by
    rcases eq_bot_or_eq_top (LinearMap.range g) with h | h
    · exact absurd (hg1 ▸ (Submodule.mem_bot _).mp (h ▸ LinearMap.mem_range_self g one')) hm₀
    · exact LinearMap.range_eq_top.mp h
  exact ⟨(LinearEquiv.ofBijective g ⟨hinj, hsurj⟩).symm⟩

end Classification

end UpperTriangular

end RepresentationTheory.Algebra.SimpleModule.MatrixAndTruncatedPolynomial
